---
title: "Use jSurvival in R"
author: "ClinicoPath Development Team"
date: "`r Sys.Date()`"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  eval = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ClinicoPath)
```


```{r data-histopathology}
data("histopathology")
```

```{r}
#| glimpse histopathology

dplyr::glimpse(histopathology)
```


```{r}
ClinicoPath::survival(
    data = histopathology,
    elapsedtime = "OverallTime",
    tint = TRUE,
    dxdate = "SurgeryDate",
    fudate = "LastFollowUpDate",
    explanatory = "LVI",
    outcome = "Outcome",
    outcomeLevel = NULL,
    dod = NULL,
    dooc = NULL,
    awd = NULL,
    awod = NULL,
    timetypedata = "ymdhms",
    sc = TRUE,
    ce = TRUE,
    ch = TRUE
    )
```




```{r}
overall_survival <- ClinicoPath::survival(
    data = histopathology,
    elapsedtime = "OverallTime",
    tint = TRUE,
    dxdate = "SurgeryDate",
    fudate = "LastFollowUpDate",
    explanatory = "LVI",
    outcome = "Outcome",
    outcomeLevel = NULL,
    dod = NULL,
    dooc = NULL,
    awd = NULL,
    awod = NULL,
    timetypedata = "ymdhms",
    sc = TRUE,
    ce = TRUE,
    ch = TRUE
    )
```


```{r}
ls(overall_survival)
```



```{r}
overall_survival$tCoxtext2
```


```{r}
overall_survival$survTableSummary
```


```{r}
overall_survival$survTable
```



```{r}
overall_survival$subtitle
```



```{r}
overall_survival$plot3
```



```{r}
overall_survival$plot2
```



```{r}
overall_survival$plot
```



```{r}
overall_survival$medianTable
```


```{r}
overall_survival$medianSummary
```



```{r}
overall_survival$coxTable
```



```{r}
overall_survival$coxTable$asDF
```




```{r}
overall_survival$coxSummary
```




```{r}
overall_survival$plot
```


```{r}
# Tip: Save a high-resolution PNG
# overall_survival$plot$saveAs("overall_survival.png")
# Convert to TIFF if needed for journals:
# img <- png::readPNG("overall_survival.png")
# tiff::writeTIFF(what = img, where = "overall_survival.tiff", compression = "none")
```
 
 



Notes
-----
- This vignette shows how to call the same analysis from R that you access in jamovi’s GUI.
- Keep event coding and time units consistent with your dataset.
