---
title: "Troubleshooting Guide for ClinicoPath"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Troubleshooting Guide for ClinicoPath}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE, eval = FALSE)
```

# Troubleshooting Guide

This guide will help you solve the most common issues you might encounter when using the ClinicoPath module in jamovi.

## Common Problems and Solutions

### "My plot is blank or doesn't show up!"

This is a common issue. Here are a few things to check:

1.  **Are the variables in the right boxes?** Make sure you have moved your variables from the list on the left into the correct analysis boxes on the right (e.g., `Dependent Variable`, `Grouping Variable`).

2.  **Is there enough data?** Some plots require a minimum amount of data. For example, if you are comparing groups, you need to have at least a few patients in each group.

3.  **Are you using the correct variable type?** Make sure you are using continuous variables (like age or lab values) and categorical variables (like treatment groups or diagnosis) in the correct places. If a variable is being treated as text instead of a number or a category, it can cause problems.

***
[Screenshot of the jamovi data view showing how to change a variable's data type from "Text" to "Continuous" or "Nominal".]
***

### "I get an error message about 'insufficient data' or 'missing values'."

This usually means that there are gaps in your dataset.

*   **Check for empty cells**: Look at your data spreadsheet in jamovi. If there are a lot of empty cells for the variables you are trying to analyze, the analysis might fail. You may need to decide if you should remove the patients with missing data or use a different analysis method.

*   **Check group sizes**: If you are comparing groups, make sure each group has enough patients. You can do this by running a simple frequency table (`Analyses` -> `Exploration` -> `Descriptives` and move your grouping variable to the `Variables` box).

### "The text on my plot is too small or overlapping."

*   **Resize the plot**: You can make the plot bigger by clicking and dragging the bottom-right corner of the plot in the jamovi results window. This will often fix overlapping text.

*   **Export at a higher resolution**: When you export the plot as an image, you can increase the resolution (DPI) in the export options. This will make the text sharper and easier to read.

***
[Screenshot of the jamovi export dialog showing the resolution (DPI) setting.]
***

## For R Users: Common Issues

If you are using the `ClinicoPath` package directly in R, here are some common issues:

*   **`Error: object 'variable_name' not found`**: This almost always means you have a typo in a variable name or the variable does not exist in your data frame. Use `names(your_data)` to check the exact spelling of your variable names.

*   **`Error: Aesthetics must be either length 1 or the same as the data`**: This error often happens when there are missing values (`NA`) in your grouping variable. Make sure to filter out rows with missing values before plotting.

*   **Blank plots**: If you are using a grouped analysis (with the `grvar` argument), the plot is stored in the `plot2` element of the results object (e.g., `result$plot2`).

## When to Ask for Help

If you have tried these solutions and are still having trouble, you can ask for help. The best place to do this is on the **ClinicoPath GitHub Issues page**:

[https://github.com/sbalci/ClinicoPathJamoviModule/issues](https://github.com/sbalci/ClinicoPathJamoviModule/issues)

When you report an issue, please include the following information:

1.  The version of jamovi you are using (`Help` -> `About`).
2.  The version of the ClinicoPath module you have installed.
3.  A description of the problem and the steps you took to get there.
4.  The exact error message you are seeing.
5.  If possible, a screenshot of the problem.