---
title: "Visualising Clinicopathological Data"
author: "ClinicoPathDescriptives Team"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualising Clinicopathological Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

This article covers the visualisation functions available in the package.

## Age Pyramid

```{r vig-agepyramid, eval=FALSE}
agepyramid(
  data = histopathology,
  age = "Age",
  gender = "Sex",
  female = "Female"
)
```

## Alluvial Diagrams

```{r vig-alluvial, eval=FALSE}
alluvial(
  data = histopathology,
  vars = vars(Grade, LVI, PNI),
  fill = "first_variable"
)
```

## Benford Analysis

```{r vig-benford, eval=FALSE}
benford(data = histopathology, var = "TumorSize")
```

## Venn Diagrams

```{r vig-venn, eval=FALSE}
venn(data = histopathology, vars = vars(LVI, PNI, PreinvasiveComponent))
```

## Variable Trees

```{r vig-vartree, eval=FALSE}
vartree(
  data = histopathology,
  vars = vars(Grade, LVI, PNI),
  percvar = "Grade",
  percvarLevel = "High"
)
```

## Waterfall and Spider Plots

```{r vig-waterfall, eval=FALSE}
waterfall(
  data = treatmentResponse,
  patientID = "PatientID",
  responseVar = "Response",
  timeVar = "Month",
  inputType = "percentage",
  showWaterfallPlot = TRUE,
  showSpiderPlot = TRUE
)
```

These code snippets illustrate the core visualisation tools included in `ClinicoPathDescriptives`.

