---
title: "Function Workflows"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE,message=FALSE, cache=FALSE)
```


```{r setup}
library(ClinicoPath)
```



```{r}

functionsClinicoPath <- getNamespaceExports(ns = "ClinicoPath")

functionsClinicoPath <- c(
    "tableone",
    "summarydata",
    "reportcat",
    "alluvial",
    "agepyramid",

    "crosstable",

    # Survival
    "survival",
    "multisurvival",
    "oddsratio",

    # Agreement
    "agreement",

    # Decision
    "decision",
    "decisioncalculator",

    # JJ Functions
    "statsplot2",
    "jjbarstats",
    "jjbetweenstats",
    "jjcorrmat",
    "jjdotplotstats",
    "jjhistostats",
    "jjpiestats",
    "jjscatterstats",
    "jjwithinstats"
)

```



```{r include=FALSE}

out = NULL
for (i in 1:length(functionsClinicoPath)) {
  value.to.match <- functionsClinicoPath[i]
  out = c(out,
          knitr::knit_expand(here::here('vignettes', '_wf_child.Rmd'))
  )
  }

```

`r paste(knitr::knit(text = out), collapse = '\n')`

