<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ClinicoPath Tutorial Series">

<title>Decision Curve Analysis – ClinicoPath Tutorial Series</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-08eeb69f393412681a6547633e23c35d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ClinicoPath Tutorial Series</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./README.md"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tutorials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tutorials</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tutorials">    
        <li>
    <a class="dropdown-item" href="./01-getting-started.html">
 <span class="dropdown-text">1. Getting Started</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02-table-one-clinical-trial.html">
 <span class="dropdown-text">2. Table One (Clinical Trial)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-survival-analysis-cancer.html">
 <span class="dropdown-text">3. Survival Analysis (Cancer)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04-roc-diagnostic-test.html">
 <span class="dropdown-text">4. ROC Analysis (Diagnostic Test)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05-decision-curve-analysis.html">
 <span class="dropdown-text">5. Decision Curve Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./06-reproducible-reports.html">
 <span class="dropdown-text">6. Reproducible Reports</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Resources</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="./VIDEO_SCRIPTS.html">
 <span class="dropdown-text">Video Scripts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./VISUAL_DIAGRAMS.html">
 <span class="dropdown-text">Visual Diagrams</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./TUTORIAL_SERIES_COMPLETE.html">
 <span class="dropdown-text">Project Summary</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/sbalci/ClinicoPathJamoviModule"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.serdarbalci.com/ClinicoPath/"> <i class="bi bi-house" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-roc-diagnostic-test.html">Advanced Techniques</a></li><li class="breadcrumb-item"><a href="./05-decision-curve-analysis.html">Decision Curve Analysis</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting Started with ClinicoPath</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Core Analyses</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-table-one-clinical-trial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Table One for Clinical Trials</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-survival-analysis-cancer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Survival Analysis in Oncology</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Techniques</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-roc-diagnostic-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ROC Analysis for Diagnostic Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-decision-curve-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Decision Curve Analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Reproducibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-reproducible-reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Creating Reproducible Reports</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Production Resources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./VIDEO_SCRIPTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ClinicoPath Tutorial Series - Video Scripts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./VISUAL_DIAGRAMS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ClinicoPath Tutorial Series - Visual Diagrams &amp; Workflow Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./TUTORIAL_SERIES_COMPLETE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ClinicoPath Tutorial Series - Complete Package</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-overview" id="toc-sec-overview" class="nav-link active" data-scroll-target="#sec-overview"><span class="header-section-number">1</span> Overview</a></li>
  <li><a href="#sec-scenario" id="toc-sec-scenario" class="nav-link" data-scroll-target="#sec-scenario"><span class="header-section-number">2</span> Clinical Scenario</a>
  <ul class="collapse">
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design"><span class="header-section-number">2.1</span> Study Design</a></li>
  <li><a href="#the-problem-with-statistical-metrics" id="toc-the-problem-with-statistical-metrics" class="nav-link" data-scroll-target="#the-problem-with-statistical-metrics"><span class="header-section-number">2.2</span> The Problem with Statistical Metrics</a></li>
  </ul></li>
  <li><a href="#sec-understanding" id="toc-sec-understanding" class="nav-link" data-scroll-target="#sec-understanding"><span class="header-section-number">3</span> Understanding Decision Curves</a>
  <ul class="collapse">
  <li><a href="#key-concepts" id="toc-key-concepts" class="nav-link" data-scroll-target="#key-concepts"><span class="header-section-number">3.1</span> Key Concepts</a>
  <ul class="collapse">
  <li><a href="#what-is-net-benefit" id="toc-what-is-net-benefit" class="nav-link" data-scroll-target="#what-is-net-benefit"><span class="header-section-number">3.1.1</span> What is Net Benefit?</a></li>
  <li><a href="#interpreting-decision-curves" id="toc-interpreting-decision-curves" class="nav-link" data-scroll-target="#interpreting-decision-curves"><span class="header-section-number">3.1.2</span> Interpreting Decision Curves</a></li>
  <li><a href="#threshold-probability-pt" id="toc-threshold-probability-pt" class="nav-link" data-scroll-target="#threshold-probability-pt"><span class="header-section-number">3.1.3</span> Threshold Probability (pt)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#sec-basic-dca" id="toc-sec-basic-dca" class="nav-link" data-scroll-target="#sec-basic-dca"><span class="header-section-number">4</span> Step 1: Basic Decision Curve Analysis</a>
  <ul class="collapse">
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data"><span class="header-section-number">4.1</span> Load Data</a></li>
  <li><a href="#run-decision-curve-analysis" id="toc-run-decision-curve-analysis" class="nav-link" data-scroll-target="#run-decision-curve-analysis"><span class="header-section-number">4.2</span> Run Decision Curve Analysis</a>
  <ul class="collapse">
  <li><a href="#essential-options" id="toc-essential-options" class="nav-link" data-scroll-target="#essential-options"><span class="header-section-number">4.2.1</span> Essential Options</a></li>
  </ul></li>
  <li><a href="#interpret-results" id="toc-interpret-results" class="nav-link" data-scroll-target="#interpret-results"><span class="header-section-number">4.3</span> Interpret Results</a>
  <ul class="collapse">
  <li><a href="#decision-curve-output" id="toc-decision-curve-output" class="nav-link" data-scroll-target="#decision-curve-output"><span class="header-section-number">4.3.1</span> Decision Curve Output</a></li>
  <li><a href="#net-interventions-avoided" id="toc-net-interventions-avoided" class="nav-link" data-scroll-target="#net-interventions-avoided"><span class="header-section-number">4.3.2</span> Net Interventions Avoided</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#sec-comparing" id="toc-sec-comparing" class="nav-link" data-scroll-target="#sec-comparing"><span class="header-section-number">5</span> Step 2: Comparing Multiple Models</a>
  <ul class="collapse">
  <li><a href="#add-comparison-models" id="toc-add-comparison-models" class="nav-link" data-scroll-target="#add-comparison-models"><span class="header-section-number">5.1</span> Add Comparison Models</a>
  <ul class="collapse">
  <li><a href="#comparison-results" id="toc-comparison-results" class="nav-link" data-scroll-target="#comparison-results"><span class="header-section-number">5.1.1</span> Comparison Results</a></li>
  <li><a href="#cost-benefit-of-biomarkers" id="toc-cost-benefit-of-biomarkers" class="nav-link" data-scroll-target="#cost-benefit-of-biomarkers"><span class="header-section-number">5.1.2</span> Cost-Benefit of Biomarkers</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#sec-timedependent" id="toc-sec-timedependent" class="nav-link" data-scroll-target="#sec-timedependent"><span class="header-section-number">6</span> Step 3: Time-Dependent DCA for Survival</a>
  <ul class="collapse">
  <li><a href="#example-5-year-recurrence-free-survival" id="toc-example-5-year-recurrence-free-survival" class="nav-link" data-scroll-target="#example-5-year-recurrence-free-survival"><span class="header-section-number">6.1</span> Example: 5-Year Recurrence-Free Survival</a>
  <ul class="collapse">
  <li><a href="#time-dependent-results" id="toc-time-dependent-results" class="nav-link" data-scroll-target="#time-dependent-results"><span class="header-section-number">6.1.1</span> Time-Dependent Results</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#sec-sensitivity" id="toc-sec-sensitivity" class="nav-link" data-scroll-target="#sec-sensitivity"><span class="header-section-number">7</span> Step 4: Sensitivity Analysis</a>
  <ul class="collapse">
  <li><a href="#vary-harm-to-benefit-ratio" id="toc-vary-harm-to-benefit-ratio" class="nav-link" data-scroll-target="#vary-harm-to-benefit-ratio"><span class="header-section-number">7.1</span> Vary Harm-to-Benefit Ratio</a>
  <ul class="collapse">
  <li><a href="#results-across-scenarios" id="toc-results-across-scenarios" class="nav-link" data-scroll-target="#results-across-scenarios"><span class="header-section-number">7.1.1</span> Results Across Scenarios</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#sec-reporting" id="toc-sec-reporting" class="nav-link" data-scroll-target="#sec-reporting"><span class="header-section-number">8</span> Manuscript Reporting</a>
  <ul class="collapse">
  <li><a href="#methods-section" id="toc-methods-section" class="nav-link" data-scroll-target="#methods-section"><span class="header-section-number">8.1</span> Methods Section</a></li>
  <li><a href="#results-section" id="toc-results-section" class="nav-link" data-scroll-target="#results-section"><span class="header-section-number">8.2</span> Results Section</a></li>
  <li><a href="#figure-legend" id="toc-figure-legend" class="nav-link" data-scroll-target="#figure-legend"><span class="header-section-number">8.3</span> Figure Legend</a></li>
  </ul></li>
  <li><a href="#sec-communicating" id="toc-sec-communicating" class="nav-link" data-scroll-target="#sec-communicating"><span class="header-section-number">9</span> Communicating to Stakeholders</a>
  <ul class="collapse">
  <li><a href="#for-clinicians" id="toc-for-clinicians" class="nav-link" data-scroll-target="#for-clinicians"><span class="header-section-number">9.1</span> For Clinicians</a></li>
  <li><a href="#for-hospital-administrators" id="toc-for-hospital-administrators" class="nav-link" data-scroll-target="#for-hospital-administrators"><span class="header-section-number">9.2</span> For Hospital Administrators</a></li>
  <li><a href="#for-patients" id="toc-for-patients" class="nav-link" data-scroll-target="#for-patients"><span class="header-section-number">9.3</span> For Patients</a></li>
  </ul></li>
  <li><a href="#sec-mistakes" id="toc-sec-mistakes" class="nav-link" data-scroll-target="#sec-mistakes"><span class="header-section-number">10</span> Common Mistakes to Avoid</a>
  <ul class="collapse">
  <li><a href="#mistake-1-confusing-dca-with-roc" id="toc-mistake-1-confusing-dca-with-roc" class="nav-link" data-scroll-target="#mistake-1-confusing-dca-with-roc"><span class="header-section-number">10.1</span> ❌ Mistake 1: Confusing DCA with ROC</a></li>
  <li><a href="#mistake-2-ignoring-threshold-context" id="toc-mistake-2-ignoring-threshold-context" class="nav-link" data-scroll-target="#mistake-2-ignoring-threshold-context"><span class="header-section-number">10.2</span> ❌ Mistake 2: Ignoring Threshold Context</a></li>
  <li><a href="#mistake-3-treating-interventions-avoided-as-gospel" id="toc-mistake-3-treating-interventions-avoided-as-gospel" class="nav-link" data-scroll-target="#mistake-3-treating-interventions-avoided-as-gospel"><span class="header-section-number">10.3</span> ❌ Mistake 3: Treating Interventions Avoided as Gospel</a></li>
  </ul></li>
  <li><a href="#sec-summary" id="toc-sec-summary" class="nav-link" data-scroll-target="#sec-summary"><span class="header-section-number">11</span> Summary</a>
  <ul class="collapse">
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">11.1</span> Key Takeaways</a></li>
  <li><a href="#dca-vs.-other-metrics" id="toc-dca-vs.-other-metrics" class="nav-link" data-scroll-target="#dca-vs.-other-metrics"><span class="header-section-number">11.2</span> DCA vs.&nbsp;Other Metrics</a></li>
  <li><a href="#decision-framework" id="toc-decision-framework" class="nav-link" data-scroll-target="#decision-framework"><span class="header-section-number">11.3</span> Decision Framework</a></li>
  <li><a href="#next-tutorial" id="toc-next-tutorial" class="nav-link" data-scroll-target="#next-tutorial"><span class="header-section-number">11.4</span> Next Tutorial</a></li>
  </ul></li>
  <li><a href="#sec-references" id="toc-sec-references" class="nav-link" data-scroll-target="#sec-references"><span class="header-section-number">12</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-roc-diagnostic-test.html">Advanced Techniques</a></li><li class="breadcrumb-item"><a href="./05-decision-curve-analysis.html">Decision Curve Analysis</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Decision Curve Analysis</h1>
<p class="subtitle lead">Evaluating Clinical Utility of Prediction Models</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>ClinicoPath Tutorial Series </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="sec-overview" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Overview</h1>
<p>Learn how to assess <strong>clinical utility</strong> using Decision Curve Analysis (DCA):</p>
<ul>
<li>✅ Understand net benefit framework</li>
<li>✅ Create decision curves</li>
<li>✅ Compare prediction models</li>
<li>✅ Determine optimal threshold probabilities</li>
<li>✅ Calculate interventions avoided</li>
<li>✅ Communicate clinical value to stakeholders</li>
</ul>
<p><strong>Prerequisites:</strong> <a href="./01-getting-started.html">Tutorial 1</a>, <a href="./04-roc-diagnostic-test.html">Tutorial 4: ROC Analysis</a> <strong>Time Required:</strong> 50 minutes <strong>Dataset:</strong> <code>breast_recurrence_prediction</code> (n=300, 5-year recurrence prediction)</p>
<hr>
</section>
<section id="sec-scenario" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Clinical Scenario</h1>
<section id="study-design" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="study-design"><span class="header-section-number">2.1</span> Study Design</h2>
<p>You developed a <strong>recurrence risk prediction model</strong> for breast cancer patients after surgery:</p>
<ul>
<li><strong>Outcome:</strong> 5-year recurrence (yes/no)</li>
<li><strong>Predictors:</strong> Age, stage, grade, ER/PR status, Ki-67</li>
<li><strong>Clinical Decision:</strong> Adjuvant chemotherapy (yes/no)</li>
<li><strong>Trade-off:</strong>
<ul>
<li>Give chemotherapy → Prevent recurrence, but toxicity if patient wouldn’t recur anyway</li>
<li>No chemotherapy → Avoid toxicity, but risk recurrence if patient would benefit</li>
</ul></li>
</ul>
</section>
<section id="the-problem-with-statistical-metrics" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="the-problem-with-statistical-metrics"><span class="header-section-number">2.2</span> The Problem with Statistical Metrics</h2>
<p><strong>Your model has:</strong> - AUC = 0.78 (good discrimination) - Sensitivity = 82%, Specificity = 71% at optimal cutpoint - Calibration slope = 0.95 (well-calibrated)</p>
<p><strong>But clinicians ask:</strong> &gt; “Great statistics, but… <strong>should I actually use this model?</strong> Will it improve patient outcomes compared to treating everyone or treating no one?”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Decision Curve Analysis Answers
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>DCA quantifies clinical usefulness</strong> by comparing net benefit of using your model vs.&nbsp;default strategies across different risk thresholds.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-understanding" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Understanding Decision Curves</h1>
<section id="key-concepts" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="key-concepts"><span class="header-section-number">3.1</span> Key Concepts</h2>
<section id="what-is-net-benefit" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="what-is-net-benefit"><span class="header-section-number">3.1.1</span> What is Net Benefit?</h3>
<p><strong>Net Benefit</strong> = Clinical benefit minus clinical harm, weighted by relative values</p>
<pre><code>Net Benefit = (True Positives / N) - (False Positives / N) × (pt / (1 - pt))

where:
- pt = threshold probability (below which you wouldn't treat)
- (pt / (1 - pt)) = harm-to-benefit ratio</code></pre>
</section>
<section id="interpreting-decision-curves" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="interpreting-decision-curves"><span class="header-section-number">3.1.2</span> Interpreting Decision Curves</h3>
<pre><code>Net Benefit
    ↑
0.20│         Model ——————— (Best)
    │       /
0.15│     / Treat All ————
    │    /    /
0.10│  /    /
    │ /   /
0.05│/  / Treat None ——————— (Baseline)
    │ /
0.00└────────────────────────────→
   0%  10%  20%  30%  40%  50%
        Threshold Probability</code></pre>
<p><strong>Key Components:</strong></p>
<ol type="1">
<li><strong>Treat None (grey line):</strong> Net benefit = 0 (baseline)
<ul>
<li>Never treat anyone → No benefits, no harms</li>
</ul></li>
<li><strong>Treat All (blue line):</strong> Decreases with threshold
<ul>
<li>Treat everyone → Benefits all who need it, harms all who don’t</li>
</ul></li>
<li><strong>Model (red line):</strong> Your prediction model
<ul>
<li>Treat only those above threshold</li>
<li><strong>Model above both lines = Clinically useful</strong></li>
</ul></li>
</ol>
</section>
<section id="threshold-probability-pt" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="threshold-probability-pt"><span class="header-section-number">3.1.3</span> Threshold Probability (pt)</h3>
<p><strong>Definition:</strong> Minimum predicted risk at which treatment is warranted</p>
<p><strong>Clinical Interpretation:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Threshold</th>
<th>Meaning</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>pt = 5%</td>
<td>Treat if risk ≥ 5%</td>
<td>Very aggressive (screening context)</td>
</tr>
<tr class="even">
<td>pt = 10%</td>
<td>Treat if risk ≥ 10%</td>
<td>Standard for many cancers</td>
</tr>
<tr class="odd">
<td>pt = 20%</td>
<td>Treat if risk ≥ 20%</td>
<td>Moderate threshold</td>
</tr>
<tr class="even">
<td>pt = 30%</td>
<td>Treat if risk ≥ 30%</td>
<td>Conservative (toxic treatments)</td>
</tr>
</tbody>
</table>
<p><strong>How to Choose pt:</strong></p>
<pre><code>pt = Harm / (Harm + Benefit)

Example: Chemotherapy for breast cancer
- Benefit: Prevent 1 death
- Harm: Severe toxicity in 4 patients (death equivalent)
- pt = 4 / (4 + 1) = 0.80 (treat if risk ≥80%)</code></pre>
<hr>
</section>
</section>
</section>
<section id="sec-basic-dca" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Step 1: Basic Decision Curve Analysis</h1>
<section id="load-data" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="load-data"><span class="header-section-number">4.1</span> Load Data</h2>
<ol type="1">
<li>Open jamovi</li>
<li><strong>File</strong> → <strong>Open</strong> → <strong>Data Library</strong></li>
<li>Select <code>breast_recurrence_prediction</code></li>
</ol>
<p><strong>Dataset Structure:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>PatientID</code></td>
<td>ID</td>
<td>Patient identifier</td>
</tr>
<tr class="even">
<td><code>Recurrence</code></td>
<td>Nominal</td>
<td>Yes / No (outcome at 5 years)</td>
</tr>
<tr class="odd">
<td><code>Age</code></td>
<td>Continuous</td>
<td>Age at diagnosis</td>
</tr>
<tr class="even">
<td><code>Stage</code></td>
<td>Ordinal</td>
<td>I / II / III</td>
</tr>
<tr class="odd">
<td><code>Grade</code></td>
<td>Ordinal</td>
<td>1 / 2 / 3</td>
</tr>
<tr class="even">
<td><code>ER_Status</code></td>
<td>Nominal</td>
<td>Positive / Negative</td>
</tr>
<tr class="odd">
<td><code>PR_Status</code></td>
<td>Nominal</td>
<td>Positive / Negative</td>
</tr>
<tr class="even">
<td><code>Ki67</code></td>
<td>Continuous</td>
<td>Ki-67 proliferation index (%)</td>
</tr>
<tr class="odd">
<td><code>Model_Risk</code></td>
<td>Continuous</td>
<td>Predicted 5-year recurrence risk (0-1)</td>
</tr>
</tbody>
</table>
</section>
<section id="run-decision-curve-analysis" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="run-decision-curve-analysis"><span class="header-section-number">4.2</span> Run Decision Curve Analysis</h2>
<ol type="1">
<li><strong>Analyses</strong> → <strong>meddecideD</strong> → <strong>Decision Curve Analysis</strong></li>
<li>Configure:
<ul>
<li><strong>Outcome variable:</strong> <code>Recurrence</code> (binary)</li>
<li><strong>Outcome value:</strong> <code>Yes</code> (event of interest)</li>
<li><strong>Prediction model:</strong> <code>Model_Risk</code> (predicted probabilities 0-1)</li>
</ul></li>
</ol>
<section id="essential-options" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="essential-options"><span class="header-section-number">4.2.1</span> Essential Options</h3>
<p><strong>Threshold Range:</strong> - Minimum: 0% (everyone treated) - Maximum: 50% (beyond this, “treat none” is better) - <strong>Recommended:</strong> 0-30% for most cancer decisions</p>
<p><strong>Reference Strategies:</strong> - ☑ Treat all (assume everyone has disease) - ☑ Treat none (assume no one has disease) - ☑ Show net benefit - ☑ Show net interventions avoided</p>
<p><strong>Smoothing:</strong> - ☑ LOESS smoothing (reduces noise) - Span: 0.3 (balance between smoothness and detail)</p>
<p><strong>Confidence Intervals:</strong> - ☑ Bootstrap 95% CI (1000 iterations) - Helps assess uncertainty in net benefit</p>
</section>
</section>
<section id="interpret-results" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="interpret-results"><span class="header-section-number">4.3</span> Interpret Results</h2>
<section id="decision-curve-output" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="decision-curve-output"><span class="header-section-number">4.3.1</span> Decision Curve Output</h3>
<pre><code>════════════════════════════════════════════════════════
Decision Curve Analysis: Recurrence Prediction Model
════════════════════════════════════════════════════════

Summary Across Threshold Probabilities 0-30%:
────────────────────────────────────────────────────────
Model Net Benefit Range:     0.000 to 0.165
Treat All Net Benefit Range: 0.000 to 0.120
Treat None Net Benefit:      0.000 (constant)

Model Superior to Both Strategies: 3-28% threshold range
────────────────────────────────────────────────────────

Standardized Net Benefit (at key thresholds):
────────────────────────────────────────────────────────
Threshold    Model NB    Treat All NB    Difference
   5%         0.145         0.118          +0.027
  10%         0.165         0.105          +0.060
  15%         0.158         0.082          +0.076
  20%         0.138         0.053          +0.085
  25%         0.108         0.023          +0.085
  30%         0.072        -0.008          +0.080
────────────────────────────────────────────────────────</code></pre>
<p><strong>Interpretation:</strong></p>
<p>✅ <strong>Model is clinically useful</strong> (curve above both reference lines)</p>
<p>✅ <strong>Optimal threshold range: 10-25%</strong> - Maximum net benefit at 10% (NB = 0.165) - Largest improvement over “treat all” at 20-25% (NB difference = 0.085)</p>
<p>✅ <strong>At 15% threshold:</strong> - Model: NB = 0.158 - Treat All: NB = 0.082 - <strong>Improvement: +0.076</strong></p>
<p><strong>What does NB = 0.158 mean?</strong> &gt; “Using the model is equivalent to a strategy that identifies 15.8 true positives per 100 patients with no false positives.”</p>
</section>
<section id="net-interventions-avoided" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="net-interventions-avoided"><span class="header-section-number">4.3.2</span> Net Interventions Avoided</h3>
<pre><code>Interventions Avoided per 100 Patients:
────────────────────────────────────────────────────────
Threshold    Model vs. Treat All
   5%              8 fewer treatments
  10%             18 fewer treatments
  15%             25 fewer treatments
  20%             31 fewer treatments
  25%             34 fewer treatments
  30%             36 fewer treatments
────────────────────────────────────────────────────────</code></pre>
<p><strong>Clinical Interpretation at 15% threshold:</strong></p>
<p>✅ <strong>25 unnecessary treatments avoided per 100 patients</strong> - Without model: Treat 100% of patients - With model: Treat only 75% of patients - <strong>25% reduction in chemotherapy use</strong> - While maintaining or improving recurrence prevention</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Real-World Impact
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a clinic seeing 200 breast cancer patients/year: - <strong>50 patients</strong> spared unnecessary chemotherapy - <strong>Cost savings:</strong> 50 × $50,000 = $2.5 million - <strong>Toxicity avoided:</strong> 50 patients avoid severe side effects</p>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="sec-comparing" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Step 2: Comparing Multiple Models</h1>
<p>Now compare your full model to simpler alternatives:</p>
<ol type="1">
<li><strong>Model 1 (Full):</strong> Age + Stage + Grade + ER + PR + Ki-67</li>
<li><strong>Model 2 (Clinical):</strong> Age + Stage + Grade only</li>
<li><strong>Model 3 (Single marker):</strong> Ki-67 only</li>
</ol>
<section id="add-comparison-models" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="add-comparison-models"><span class="header-section-number">5.1</span> Add Comparison Models</h2>
<ol type="1">
<li>In <strong>Decision Curve Analysis</strong>, click <strong>Add Model</strong></li>
<li><strong>Model 2 prediction:</strong> <code>Model_Clinical_Risk</code></li>
<li><strong>Model 3 prediction:</strong> <code>Model_Ki67_Risk</code></li>
<li>Keep same outcome and thresholds</li>
</ol>
<section id="comparison-results" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="comparison-results"><span class="header-section-number">5.1.1</span> Comparison Results</h3>
<pre><code>════════════════════════════════════════════════════════
Model Comparison at Threshold 15%:
════════════════════════════════════════════════════════
Strategy              Net Benefit    Rank    Difference vs. Best
────────────────────────────────────────────────────────────────
Full Model              0.158         1st         --
Clinical Model          0.142         2nd       -0.016
Ki-67 Only              0.098         3rd       -0.060
Treat All               0.082         4th       -0.076
Treat None              0.000         5th       -0.158
════════════════════════════════════════════════════════

Interventions Avoided (vs. Treat All):
────────────────────────────────────────────────────────
Full Model:       25 per 100 patients
Clinical Model:   21 per 100 patients
Ki-67 Only:       12 per 100 patients
════════════════════════════════════════════════════════</code></pre>
<p><strong>Interpretation:</strong></p>
<p>✅ <strong>Full model is best</strong> across 5-30% threshold range ✅ <strong>Clinical model is close</strong> (NB difference = 0.016) - Only 4 more interventions per 100 patients - May prefer for simplicity (fewer biomarkers) ✅ <strong>Ki-67 alone insufficient</strong> (only modest improvement over treat-all)</p>
</section>
<section id="cost-benefit-of-biomarkers" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="cost-benefit-of-biomarkers"><span class="header-section-number">5.1.2</span> Cost-Benefit of Biomarkers</h3>
<p><strong>Question:</strong> Is adding ER/PR/Ki-67 worth the cost?</p>
<p><strong>Analysis:</strong></p>
<pre><code>Incremental Net Benefit (Full vs. Clinical):
  = 0.158 - 0.142 = 0.016
  = 1.6 true positives per 100 patients
  = 4 unnecessary treatments avoided per 100 patients

Cost of biomarker panel: $500 × 100 = $50,000
Savings from avoided treatments: 4 × $50,000 = $200,000
Net savings: $150,000 per 100 patients</code></pre>
<p><strong>Decision:</strong> Full model is cost-effective (benefits exceed costs 4:1)</p>
<hr>
</section>
</section>
</section>
<section id="sec-timedependent" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Step 3: Time-Dependent DCA for Survival</h1>
<p>When outcome is time-to-event (survival), use <strong>time-dependent DCA</strong>.</p>
<section id="example-5-year-recurrence-free-survival" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="example-5-year-recurrence-free-survival"><span class="header-section-number">6.1</span> Example: 5-Year Recurrence-Free Survival</h2>
<p><strong>Dataset:</strong> <code>breast_survival_rfs</code> (recurrence-free survival with censoring)</p>
<ol type="1">
<li><strong>Analyses</strong> → <strong>meddecideD</strong> → <strong>Time-Dependent Decision Curve Analysis</strong></li>
<li>Configure:
<ul>
<li><strong>Time variable:</strong> <code>RFS_time</code> (months to recurrence or last follow-up)</li>
<li><strong>Event variable:</strong> <code>RFS_status</code> (0=censored, 1=recurrence)</li>
<li><strong>Prediction model:</strong> <code>Model_Risk_60months</code> (predicted risk at 60 months)</li>
<li><strong>Time point:</strong> 60 months (5 years)</li>
</ul></li>
</ol>
<section id="time-dependent-results" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="time-dependent-results"><span class="header-section-number">6.1.1</span> Time-Dependent Results</h3>
<pre><code>════════════════════════════════════════════════════════
Time-Dependent DCA at 60 Months (5 years):
════════════════════════════════════════════════════════

Kaplan-Meier Event Rate at 60 months: 28.5%
Censoring Rate: 12.3%

Net Benefit at Threshold 15%:
────────────────────────────────────────────────────────
Model:              0.152 (adjusted for censoring)
Treat All:          0.078
Treat None:         0.000
────────────────────────────────────────────────────────

Interventions Avoided: 24 per 100 patients
════════════════════════════════════════════════════════</code></pre>
<p><strong>Key Difference from Standard DCA:</strong> - Accounts for censoring (patients lost to follow-up) - Uses time-specific risk estimates - More appropriate for survival outcomes</p>
<hr>
</section>
</section>
</section>
<section id="sec-sensitivity" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Step 4: Sensitivity Analysis</h1>
<p>Test robustness of conclusions to assumptions.</p>
<section id="vary-harm-to-benefit-ratio" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="vary-harm-to-benefit-ratio"><span class="header-section-number">7.1</span> Vary Harm-to-Benefit Ratio</h2>
<p><strong>Base case:</strong> pt = 15% (harm = 1, benefit = 5.67)</p>
<p><strong>Sensitivity scenarios:</strong> 1. <strong>Conservative:</strong> pt = 25% (more weight on harm) 2. <strong>Aggressive:</strong> pt = 5% (more weight on benefit)</p>
<section id="results-across-scenarios" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="results-across-scenarios"><span class="header-section-number">7.1.1</span> Results Across Scenarios</h3>
<pre><code>═══════════════════════════════════════════════════════
Sensitivity Analysis: Model Net Benefit
═══════════════════════════════════════════════════════
Scenario         Threshold    Net Benefit    Model Best?
───────────────────────────────────────────────────────
Aggressive          5%          0.145          YES
Base case          15%          0.158          YES
Conservative       25%          0.108          YES
═══════════════════════════════════════════────────────

Conclusion: Model remains superior across plausible range
           of harm-to-benefit ratios
═══════════════════════════════════════════════════════</code></pre>
<p><strong>Robustness:</strong> Model is useful even if clinicians disagree on exact threshold</p>
<hr>
</section>
</section>
</section>
<section id="sec-reporting" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Manuscript Reporting</h1>
<section id="methods-section" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="methods-section"><span class="header-section-number">8.1</span> Methods Section</h2>
<blockquote class="blockquote">
<p><strong>Decision Curve Analysis.</strong> Clinical utility of the recurrence prediction model was evaluated using decision curve analysis (DCA), which quantifies net benefit across a range of threshold probabilities. Net benefit represents the difference between the proportion of true positives and false positives, weighted by the relative harm of false positives vs.&nbsp;false negatives. We compared the model to two default strategies: treat all patients (assume all will recur) and treat none (assume no recurrences). The model was considered clinically useful if its decision curve was above both reference strategies within a clinically reasonable threshold range (5-30%). Net interventions avoided quantified the reduction in unnecessary treatments compared to treating all patients. Threshold probabilities reflect the minimum predicted risk at which a patient and clinician would opt for adjuvant chemotherapy, accounting for treatment toxicity. Confidence intervals were estimated using 1000 bootstrap replicates. Analyses used ClinicoPath v0.0.32 for jamovi.</p>
</blockquote>
</section>
<section id="results-section" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="results-section"><span class="header-section-number">8.2</span> Results Section</h2>
<blockquote class="blockquote">
<p><strong>Clinical Utility.</strong> Decision curve analysis demonstrated that the recurrence prediction model provides net benefit compared to default strategies of treating all or no patients across threshold probabilities of 3-28% (Figure 1). At a threshold of 15% (reflecting current treatment decision-making), the model achieved net benefit of 0.158, compared to 0.082 for treating all patients (difference: 0.076, 95% CI: 0.052-0.101). This translates to 25 unnecessary treatments avoided per 100 patients (95% CI: 18-32) while maintaining recurrence prevention. The full model (including biomarkers) outperformed the clinical-only model (net benefit 0.142, difference 0.016, p = 0.03), justifying biomarker costs through reduced overtreatment. Model performance was robust across sensitivity analyses varying the harm-to-benefit ratio (threshold 5-25%).</p>
</blockquote>
</section>
<section id="figure-legend" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="figure-legend"><span class="header-section-number">8.3</span> Figure Legend</h2>
<blockquote class="blockquote">
<p><strong>Figure 1. Decision Curve Analysis for Recurrence Prediction Model.</strong> Net benefit of using the prediction model (red line) compared to treating all patients (blue line) or treating no patients (grey line) across threshold probabilities 0-50%. The model provides net benefit over both strategies between 3-28% thresholds. Shaded area shows 95% bootstrap confidence interval. At the 15% threshold (vertical dashed line), the model achieves net benefit of 0.158, avoiding 25 unnecessary treatments per 100 patients compared to treating all.</p>
</blockquote>
<hr>
</section>
</section>
<section id="sec-communicating" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Communicating to Stakeholders</h1>
<section id="for-clinicians" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="for-clinicians"><span class="header-section-number">9.1</span> For Clinicians</h2>
<p><strong>Simple Message:</strong></p>
<blockquote class="blockquote">
<p>“Using this model at our clinic (200 patients/year), we would: - Avoid giving chemotherapy to <strong>50 patients</strong> who wouldn’t benefit - Still prevent recurrence in <strong>90% of high-risk patients</strong> - Save patients from unnecessary toxicity - Maintain excellent clinical outcomes”</p>
</blockquote>
</section>
<section id="for-hospital-administrators" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="for-hospital-administrators"><span class="header-section-number">9.2</span> For Hospital Administrators</h2>
<p><strong>Business Case:</strong></p>
<pre><code>Annual Impact at 200 patients/year:

Cost Savings:
  - 50 avoided chemotherapy treatments × $50,000 = $2,500,000
  - Biomarker testing cost: 200 × $500 = $100,000
  - Net savings: $2,400,000/year

Quality Metrics:
  - Reduce chemotherapy-related toxicity by 25%
  - Improve patient satisfaction (avoid unnecessary treatment)
  - Reduce chemo suite utilization → capacity for more patients

Return on Investment: 2400%
Payback period: 2 weeks</code></pre>
</section>
<section id="for-patients" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="for-patients"><span class="header-section-number">9.3</span> For Patients</h2>
<p><strong>Patient-Friendly Explanation:</strong></p>
<blockquote class="blockquote">
<p>“This test helps us predict your risk of cancer coming back. If your risk is low (below 15%), you may not need chemotherapy – avoiding the side effects while staying safe. If your risk is high, chemotherapy will help prevent recurrence. The test is like a personalized recommendation based on your specific cancer.”</p>
</blockquote>
<hr>
</section>
</section>
<section id="sec-mistakes" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Common Mistakes to Avoid</h1>
<section id="mistake-1-confusing-dca-with-roc" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="mistake-1-confusing-dca-with-roc"><span class="header-section-number">10.1</span> ❌ Mistake 1: Confusing DCA with ROC</h2>
<p><strong>Wrong:</strong> &gt; “AUC is 0.78, so the model is useful.”</p>
<p><strong>Why Wrong:</strong> - AUC measures discrimination, not clinical utility - High AUC doesn’t guarantee net benefit - Example: Model with AUC 0.90 could have negative net benefit if poorly calibrated</p>
<p><strong>Correct:</strong> &gt; “AUC is 0.78 (good discrimination). DCA shows the model provides net benefit over treat-all/treat-none strategies at clinically relevant thresholds (10-25%), confirming clinical usefulness.”</p>
</section>
<section id="mistake-2-ignoring-threshold-context" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="mistake-2-ignoring-threshold-context"><span class="header-section-number">10.2</span> ❌ Mistake 2: Ignoring Threshold Context</h2>
<p><strong>Wrong:</strong> &gt; “Maximum net benefit is at 10% threshold, so use 10%.”</p>
<p><strong>Why Wrong:</strong> - Optimal threshold depends on patient/clinician preferences - Harm-to-benefit ratio varies by individual - No single “right” threshold</p>
<p><strong>Correct:</strong> &gt; “The model shows positive net benefit across 5-30% thresholds. Clinicians should choose threshold based on shared decision-making, considering patient values regarding chemotherapy toxicity vs.&nbsp;recurrence risk.”</p>
</section>
<section id="mistake-3-treating-interventions-avoided-as-gospel" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="mistake-3-treating-interventions-avoided-as-gospel"><span class="header-section-number">10.3</span> ❌ Mistake 3: Treating Interventions Avoided as Gospel</h2>
<p><strong>Wrong:</strong> &gt; “The model avoids exactly 25 interventions per 100 patients.”</p>
<p><strong>Why Wrong:</strong> - This assumes perfect adherence to model recommendations - Clinicians may override model in practice - Requires prospective validation</p>
<p><strong>Correct:</strong> &gt; “If the model were used as intended, it would potentially avoid 25 interventions per 100 patients (95% CI: 18-32). Prospective implementation study needed to confirm real-world impact.”</p>
<hr>
</section>
</section>
<section id="sec-summary" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Summary</h1>
<section id="key-takeaways" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">11.1</span> Key Takeaways</h2>
<p>✅ <strong>DCA quantifies clinical usefulness</strong> (not just statistical performance) ✅ <strong>Net benefit</strong> = Benefits - Harms (weighted appropriately) ✅ <strong>Model must beat both reference strategies</strong> to be useful ✅ <strong>Threshold probability</strong> reflects harm-to-benefit ratio ✅ <strong>Interventions avoided</strong> shows real-world impact ✅ <strong>Compare multiple models</strong> to justify complexity ✅ <strong>Sensitivity analysis</strong> tests robustness</p>
</section>
<section id="dca-vs.-other-metrics" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="dca-vs.-other-metrics"><span class="header-section-number">11.2</span> DCA vs.&nbsp;Other Metrics</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 47%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>What It Measures</th>
<th>Limitation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AUC</strong></td>
<td>Discrimination</td>
<td>Doesn’t consider clinical consequences</td>
</tr>
<tr class="even">
<td><strong>Calibration</strong></td>
<td>Prediction accuracy</td>
<td>Doesn’t weigh harms vs.&nbsp;benefits</td>
</tr>
<tr class="odd">
<td><strong>Sensitivity/Specificity</strong></td>
<td>Performance at one cutpoint</td>
<td>Doesn’t compare to alternatives</td>
</tr>
<tr class="even">
<td><strong>Net Benefit (DCA)</strong></td>
<td>Clinical value across thresholds</td>
<td>✅ Comprehensive assessment</td>
</tr>
</tbody>
</table>
</section>
<section id="decision-framework" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="decision-framework"><span class="header-section-number">11.3</span> Decision Framework</h2>
<pre><code>1. Build prediction model
   ↓
2. Assess discrimination (ROC/AUC)
   ↓
3. Check calibration (calibration plot)
   ↓
4. Evaluate clinical utility (DCA)
   ↓
   Model above both reference lines?
   ↓ YES
5. Determine threshold range where model is useful
   ↓
6. Calculate interventions avoided
   ↓
7. Compare to simpler models (cost-benefit)
   ↓
8. Prospective validation</code></pre>
</section>
<section id="next-tutorial" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="next-tutorial"><span class="header-section-number">11.4</span> Next Tutorial</h2>
<p><a href="./06-reproducible-reports.html"><strong>Tutorial 6: Creating Reproducible Reports</strong></a> - Automating analyses with R and Quarto - Batch processing multiple datasets - Version control with Git - Manuscript templates</p>
<hr>
</section>
</section>
<section id="sec-references" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> References</h1>
<p><strong>Decision Curve Analysis:</strong></p>
<ol type="1">
<li><p>Vickers AJ, Elkin EB. Decision curve analysis: a novel method for evaluating prediction models. <em>Med Decis Making</em>. 2006;26(6):565-574.</p></li>
<li><p>Vickers AJ, Van Calster B, Steyerberg EW. Net benefit approaches to the evaluation of prediction models, molecular markers, and diagnostic tests. <em>BMJ</em>. 2016;352:i6.</p></li>
<li><p>Van Calster B, Wynants L, Verbeek JFM, et al.&nbsp;Reporting and Interpreting Decision Curve Analysis: A Guide for Investigators. <em>Eur Urol</em>. 2018;74(6):796-804.</p></li>
</ol>
<p><strong>Time-Dependent DCA:</strong></p>
<ol start="4" type="1">
<li>Vickers AJ, Cronin AM, Begg CB. One statistical test is sufficient for assessing new predictive markers. <em>BMC Med Res Methodol</em>. 2011;11:13.</li>
</ol>
<p><strong>Clinical Applications:</strong></p>
<ol start="5" type="1">
<li>Localio AR, Goodman S. Beyond the usual prediction accuracy metrics: reporting results for clinical decision making. <em>Ann Intern Med</em>. 2012;157(4):294-295.</li>
</ol>
<hr>
<p><strong>Tutorial Author:</strong> Serdar Balci, MD, PhD <strong>Last Updated:</strong> December 13, 2025 <strong>License:</strong> CC-BY-4.0 <strong>Tutorial Version:</strong> 1.0</p>
<p><strong>Continue learning:</strong> <a href="./06-reproducible-reports.html">Tutorial 6: Reproducible Reports →</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, ClinicoPath Development Team</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>