---
title: "R packages"
output: html_notebook
---

library(devtools)
library(roxygen2)
library(testthat)
devtools::session_info()
library(tidyverse)
library(fs)

---

<!-- create_package("~/path/to/foofactors") -->


---

use_r("toplain")

---

load_all()


---

exists("toplain", where = ".GlobalEnv", inherits = FALSE)






<!-- ############## -->


---


**add template data**


---

**make function**

rmarkdown::draft(file = "myfile",
template = "clinicopathological", package = "histopathR", create_dir = TRUE, edit = TRUE)






# R packages  

http://r-pkgs.had.co.nz/intro.html  

https://r-pkgs.org  


## library load


```
library(devtools)
library(tidyverse)
library(fs)
```

install.packages(c("devtools", "roxygen2", "testthat", "knitr"))

install.packages("rstudioapi")
rstudioapi::isAvailable("0.99.149")

devtools::install_github("r-lib/devtools")


library(devtools)
has_devel()


## begin package

```
devtools::create("path/to/package/pkgname")
```

## buildignore

devtools::use_build_ignore("notes")





## make new function 


```
fnumeric <- function(x) {
  as.numeric(as.character(x))
}
```


add Roxygen skeleton here:

```
use_r("fnumeric")
use_r("generateDescriptiveCode")
use_r("describeContinious")
```

use_r("toplain")



```
devtools::document()
```




```
# devtools::load_all()
devtools::load_all(".")
```


```
devtools::check()
```



```
usethis::use_test("fnumeric")
```

usethis::use_test("toplain")


```
devtools::test()
```




```
devtools::install()
```


```
devtools::check()
```




## testthat

```
usethis::use_testthat()
```

## namespace

add Roxygen comments

```
devtools::document()
```




===========================



```
old <- options(stringsAsFactors = FALSE)
on.exit(options(old), add = TRUE)
```


```
old <- setwd(tempdir())
on.exit(setwd(old), add = TRUE)
```


## build page

```
pkgdown::build_site()
```


```
.onAttach <- function(libname, pkgname) {
  packageStartupMessage("Welcome to histopathR")
}
```


```
.onLoad <- function(libname, pkgname) {
  op <- options()
  op.devtools <- list(
    devtools.path = "~/R-dev",
    devtools.install.args = "",
    devtools.name = "Serdar Balci",
    devtools.desc.author = "Serdar Balci <drserdarbalci@gmail.com> [aut, cre]",
    devtools.desc.license = "MIT",
    devtools.desc.suggests = NULL,
    devtools.desc = list()
  )
  toset <- !(names(op.devtools) %in% names(op))
  if(any(toset)) options(op.devtools[toset])

  invisible()
}
```


```
getOption("histopathR")
```


```
tools::vignetteEngine()
```


```
cat(stringi::stri_escape_unicode(
    readr::read_lines(here::here("R/generateDescriptiveCode.R"
    )
)))
```



```
# You need the suggested package for this function    
my_fun <- function(a, b) {
  if (!requireNamespace("pkg", quietly = TRUE)) {
    stop("Package \"pkg\" needed for this function to work. Please install it.",
      call. = FALSE)
  }
}
```




```
# There's a fallback method if the package isn't available
my_fun <- function(a, b) {
  if (requireNamespace("pkg", quietly = TRUE)) {
    pkg::f()
  } else {
    g()
  }
}
```



```
devtools::use_package("dplyr") # Defaults to imports
#> Adding dplyr to Imports
#> Refer to functions with dplyr::fun()
devtools::use_package("dplyr", "Suggests")
#> Adding dplyr to Suggests
#> Use requireNamespace("dplyr", quietly = TRUE) to test if package is 
#>  installed, then use dplyr::fun() to refer to functions.
```

## vignette


```
usethis::use_vignette("Data-Preperation-Histopathology-Research")
```




## make package



```
devtools::check()
```


```
devtools::install()
```



```
usethis::use_testthat()
```




```
devtools::test()
```



## build binary package

```
devtools::build(binary = TRUE)
```







## other details



```
usethis::use_mit_license("Serdar Balci")
```



```
devtools::use_readme_rmd()
```




```
usethis::use_build_ignore("exampleRCodes")
```




## add other packages


```
usethis::use_coverage()
```

```
usethis::use_package("forcats")
usethis::use_package("dplyr")
usethis::use_package("readxl")
usethis::use_package("janitor")
usethis::use_package("report")
usethis::use_package("finalfit")
usethis::use_package("ggstatsplot")
usethis::use_package("jmv")
usethis::use_package("lubridate")
usethis::use_package("summarytools")
usethis::use_package("survival")
usethis::use_package("psycho")
usethis::use_package("knitr")
usethis::use_package("kableExtra")
usethis::use_package("magicfor")
```


```
.libPaths()
```

```
lapply(.libPaths(), dir)
```

```
pkgnet::CreatePackageReport('histopathR')
```


- Using ggplot2 in packages

https://ggplot2.tidyverse.org/dev/articles/ggplot2-in-packages.html


- {{ }} for simpler interpolation

<blockquote class="twitter-tweet" data-lang="en"><p lang="da" dir="ltr">🎉 Meet {{ }} for simpler interpolation!<br>&quot;rlang 0.4.0&quot; ✍️ <a href="https://twitter.com/_lionelhenry?ref_src=twsrc%5Etfw">@_lionelhenry</a> <a href="https://t.co/OBiDehkO5B">https://t.co/OBiDehkO5B</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/tidyeval?src=hash&amp;ref_src=twsrc%5Etfw">#tidyeval</a> <a href="https://t.co/2aY36xAyKe">pic.twitter.com/2aY36xAyKe</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1144575197636415488?ref_src=twsrc%5Etfw">June 28, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>





## data

```
x <- sample(1000)
usethis::use_data(x, mtcars)
```

```
usethis::use_data_raw()
```

internal data
```
x <- sample(1000)
devtools::use_data(x, mtcars, internal = TRUE)
```


raw data

```
system.file("extdata", "mtcars.csv", package = "readr", mustWork = TRUE)
```

tools::checkRdaFiles()

devtools::use_data()

tools::resaveRdaFiles()


## citation

```
citEntry()
```


## style


```
install.packages("formatR")
formatR::tidy_dir("R")
```

```
install.packages("lintr")
lintr::lint_package()
```

```
install.packages("styler") 
# install.packages("remotes") 
remotes::install_github("r-lib/styler") 
```

# add CI


## appveyor

https://github.com/krlmlr/r-appveyor



## travis

```
devtools::use_travis()
```

http://packages.ubuntu.com/ (use for binary packages)



## covr

https://github.com/r-lib/covr



```
usethis::use_coverage()
```







========



# template

Creating a basic template package in R

http://ismayc.github.io/ecots2k16/template_pkg/

```
dir.create("~/histopathR/inst/rmarkdown/templates/report/skeleton",
    recursive = TRUE)

```



# CRAN submission



<iframe width="560" height="315" src="https://www.youtube.com/embed/-zID-rVDEHQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



devtools::check_win_devel()




