
# This file is automatically generated, you probably don't want to edit this

categorizeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "categorizeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            method = "quantile",
            nbins = 4,
            breaks = "",
            sdmult = 1,
            labels = "auto",
            customlabels = "",
            newvarname = "",
            excludeoutofrange = FALSE,
            includelowest = TRUE,
            rightclosed = TRUE,
            ordered = TRUE,
            excl = TRUE,
            showcode = TRUE,
            showplot = TRUE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="categorize",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                default=NULL,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "equal",
                    "quantile",
                    "manual",
                    "meansd",
                    "median",
                    "jenks"),
                default="quantile")
            private$..nbins <- jmvcore::OptionInteger$new(
                "nbins",
                nbins,
                min=2,
                max=20,
                default=4)
            private$..breaks <- jmvcore::OptionString$new(
                "breaks",
                breaks,
                default="")
            private$..sdmult <- jmvcore::OptionNumber$new(
                "sdmult",
                sdmult,
                min=0.5,
                max=3,
                default=1)
            private$..labels <- jmvcore::OptionList$new(
                "labels",
                labels,
                options=list(
                    "auto",
                    "semantic",
                    "numbered",
                    "lettered",
                    "custom"),
                default="auto")
            private$..customlabels <- jmvcore::OptionString$new(
                "customlabels",
                customlabels,
                default="")
            private$..newvarname <- jmvcore::OptionString$new(
                "newvarname",
                newvarname,
                default="")
            private$..addtodata <- jmvcore::OptionOutput$new(
                "addtodata")
            private$..excludeoutofrange <- jmvcore::OptionBool$new(
                "excludeoutofrange",
                excludeoutofrange,
                default=FALSE)
            private$..includelowest <- jmvcore::OptionBool$new(
                "includelowest",
                includelowest,
                default=TRUE)
            private$..rightclosed <- jmvcore::OptionBool$new(
                "rightclosed",
                rightclosed,
                default=TRUE)
            private$..ordered <- jmvcore::OptionBool$new(
                "ordered",
                ordered,
                default=TRUE)
            private$..excl <- jmvcore::OptionBool$new(
                "excl",
                excl,
                default=TRUE)
            private$..showcode <- jmvcore::OptionBool$new(
                "showcode",
                showcode,
                default=TRUE)
            private$..showplot <- jmvcore::OptionBool$new(
                "showplot",
                showplot,
                default=TRUE)

            self$.addOption(private$..var)
            self$.addOption(private$..method)
            self$.addOption(private$..nbins)
            self$.addOption(private$..breaks)
            self$.addOption(private$..sdmult)
            self$.addOption(private$..labels)
            self$.addOption(private$..customlabels)
            self$.addOption(private$..newvarname)
            self$.addOption(private$..addtodata)
            self$.addOption(private$..excludeoutofrange)
            self$.addOption(private$..includelowest)
            self$.addOption(private$..rightclosed)
            self$.addOption(private$..ordered)
            self$.addOption(private$..excl)
            self$.addOption(private$..showcode)
            self$.addOption(private$..showplot)
        }),
    active = list(
        var = function() private$..var$value,
        method = function() private$..method$value,
        nbins = function() private$..nbins$value,
        breaks = function() private$..breaks$value,
        sdmult = function() private$..sdmult$value,
        labels = function() private$..labels$value,
        customlabels = function() private$..customlabels$value,
        newvarname = function() private$..newvarname$value,
        addtodata = function() private$..addtodata$value,
        excludeoutofrange = function() private$..excludeoutofrange$value,
        includelowest = function() private$..includelowest$value,
        rightclosed = function() private$..rightclosed$value,
        ordered = function() private$..ordered$value,
        excl = function() private$..excl$value,
        showcode = function() private$..showcode$value,
        showplot = function() private$..showplot$value),
    private = list(
        ..var = NA,
        ..method = NA,
        ..nbins = NA,
        ..breaks = NA,
        ..sdmult = NA,
        ..labels = NA,
        ..customlabels = NA,
        ..newvarname = NA,
        ..addtodata = NA,
        ..excludeoutofrange = NA,
        ..includelowest = NA,
        ..rightclosed = NA,
        ..ordered = NA,
        ..excl = NA,
        ..showcode = NA,
        ..showplot = NA)
)

categorizeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "categorizeResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        notices = function() private$.items[["notices"]],
        summaryText = function() private$.items[["summaryText"]],
        freqTable = function() private$.items[["freqTable"]],
        breakpointsTable = function() private$.items[["breakpointsTable"]],
        plot = function() private$.items[["plot"]],
        rcode = function() private$.items[["rcode"]],
        addtodata = function() private$.items[["addtodata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Categorize Continuous Variables",
                refs=list(
                    "ClinicoPathJamoviModule",
                    "classInt",
                    "dichotomizing"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="Instructions",
                clearWith=list(
                    "var")))
            self$add(jmvcore::Html$new(
                options=options,
                name="notices",
                title="Notes",
                clearWith=list(
                    "var",
                    "method",
                    "nbins",
                    "breaks",
                    "excludeoutofrange",
                    "labels",
                    "customlabels",
                    "sdmult",
                    "includelowest",
                    "rightclosed",
                    "excl")))
            self$add(jmvcore::Html$new(
                options=options,
                name="summaryText",
                title="Variable Summary",
                visible="(var)",
                clearWith=list(
                    "var",
                    "excl")))
            self$add(jmvcore::Table$new(
                options=options,
                name="freqTable",
                title="Category Frequencies",
                visible="(var)",
                clearWith=list(
                    "var",
                    "method",
                    "nbins",
                    "breaks",
                    "excludeoutofrange",
                    "sdmult",
                    "labels",
                    "customlabels",
                    "includelowest",
                    "rightclosed",
                    "excl"),
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="range", 
                        `title`="Range", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="Count", 
                        `type`="integer"),
                    list(
                        `name`="percent", 
                        `title`="%", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="cumPercent", 
                        `title`="Cum %", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="breakpointsTable",
                title="Break Points",
                visible="(var)",
                clearWith=list(
                    "var",
                    "method",
                    "nbins",
                    "breaks",
                    "excludeoutofrange",
                    "sdmult",
                    "excl"),
                columns=list(
                    list(
                        `name`="index", 
                        `title`="#", 
                        `type`="integer"),
                    list(
                        `name`="value", 
                        `title`="Break Value", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Distribution Plot",
                width=600,
                height=400,
                renderFun=".plot",
                requiresData=TRUE,
                visible="(showplot)",
                clearWith=list(
                    "var",
                    "method",
                    "nbins",
                    "breaks",
                    "excludeoutofrange",
                    "sdmult",
                    "excl")))
            self$add(jmvcore::Html$new(
                options=options,
                name="rcode",
                title="R Code",
                visible="(showcode)",
                clearWith=list(
                    "var",
                    "method",
                    "nbins",
                    "breaks",
                    "excludeoutofrange",
                    "sdmult",
                    "labels",
                    "customlabels",
                    "newvarname",
                    "includelowest",
                    "rightclosed",
                    "ordered",
                    "excl")))
            self$add(jmvcore::Output$new(
                options=options,
                name="addtodata",
                title="Categorized Variable",
                varTitle="`${ var }_cat`",
                varDescription="`Categorized version of ${ var } using ${ method } method`",
                measureType="nominal",
                clearWith=list(
                    "var",
                    "method",
                    "nbins",
                    "breaks",
                    "excludeoutofrange",
                    "sdmult",
                    "labels",
                    "customlabels",
                    "newvarname",
                    "includelowest",
                    "rightclosed",
                    "ordered",
                    "excl")))}))

categorizeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "categorizeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "categorize",
                version = c(1,0,8),
                options = options,
                results = categorizeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Categorize Continuous Variables
#'
#' Converts a continuous numeric variable into an ordered set of categories 
#' using equal-width intervals, sample quantiles, hand-entered break points, 
#' mean +/- SD bands, a median split, or Fisher-Jenks natural breaks. Reports 
#' the break points and the resulting category frequencies, draws the 
#' distribution with the boundaries marked, and can add the categorised 
#' variable straight to the dataset.
#' 
#'
#' @examples
#' \donttest{
#' # Age split into quartiles
#' categorize(
#'     data = histopathology,
#'     var = Age,
#'     method = 'quantile',
#'     nbins = 4)
#'}
#' @param data The data as a data frame.
#' @param var A numeric variable to be categorized into bins.
#' @param method Method for creating bins. Options are 'equal' for equal-width
#'   intervals, 'quantile' for quantile-based bins, 'manual' for custom break
#'   points, 'meansd' for cut points at the mean and at mean +/- k SD (four
#'   bands, as in SPSS Visual Binning; a band that falls outside the data is
#'   dropped and reported), 'median' for median split, or 'jenks' for
#'   Fisher-Jenks natural breaks clustering. Jenks breaks are computed exactly
#'   up to 20000 observations; above that classInt works from a fixed-seed
#'   subsample and a note reports its size. Repeated runs always give identical
#'   break points.
#' @param nbins Number of categories to create (2-20). Used for equal,
#'   quantile, and jenks methods.
#' @param breaks Comma-separated break points for manual binning (e.g., "0,
#'   25, 50, 75, 100"). Entries are sorted and duplicates removed, and the data
#'   minimum and maximum are added around them unless out-of-range exclusion is
#'   on.
#' @param sdmult Multiplier for standard deviation when using meansd method
#'   (default = 1).
#' @param labels How to label the resulting categories.
#' @param customlabels Comma-separated custom labels (e.g., "Low, Medium,
#'   High"). Must match the number of categories.
#' @param newvarname Name for the new categorized variable, used both for the
#'   column added to the dataset and in the generated R code. Leave empty to
#'   name it after the source variable with a '_cat' suffix.
#' @param excludeoutofrange Applies to the 'manual' method only. By default
#'   the break points are extended to the data minimum and maximum, so every
#'   observation falls in a category and no case is lost. Set this to TRUE to
#'   keep the break points exactly as entered and drop observations that fall
#'   outside them; the number excluded is reported. Has no effect on the
#'   computed methods, whose break points already span the data.
#' @param includelowest If TRUE, the first interval will be left-closed
#'   (include.lowest in cut).
#' @param rightclosed If TRUE, intervals are right-closed (left-open). If
#'   FALSE, left-closed (right-open).
#' @param ordered If TRUE, creates an ordered factor to preserve category
#'   ordering, and the variable added to the dataset is marked as ordinal rather
#'   than nominal so the category order is kept in later analyses.
#' @param excl If TRUE (default), the percentages in the frequency table are
#'   taken over the categorized observations only, and missing or out-of-range
#'   rows carry no percentage. If FALSE, every row of the data is used as the
#'   denominator, so the missing and out-of-range rows carry their own share and
#'   the category percentages no longer sum to 100 on their own. Break points
#'   are always computed from the non-missing values.
#' @param showcode Display R code to reproduce the categorization.
#' @param showplot Display a histogram/density plot showing the original
#'   distribution and cut points.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notices} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$summaryText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$freqTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$breakpointsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$rcode} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$addtodata} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$freqTable$asDF}
#'
#' \code{as.data.frame(results$freqTable)}
#'
#' @export
categorize <- function(
    data,
    var = NULL,
    method = "quantile",
    nbins = 4,
    breaks = "",
    sdmult = 1,
    labels = "auto",
    customlabels = "",
    newvarname = "",
    excludeoutofrange = FALSE,
    includelowest = TRUE,
    rightclosed = TRUE,
    ordered = TRUE,
    excl = TRUE,
    showcode = TRUE,
    showplot = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("categorize requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL))


    options <- categorizeOptions$new(
        var = var,
        method = method,
        nbins = nbins,
        breaks = breaks,
        sdmult = sdmult,
        labels = labels,
        customlabels = customlabels,
        newvarname = newvarname,
        excludeoutofrange = excludeoutofrange,
        includelowest = includelowest,
        rightclosed = rightclosed,
        ordered = ordered,
        excl = excl,
        showcode = showcode,
        showplot = showplot)

    analysis <- categorizeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

