
# This file is automatically generated, you probably don't want to edit this

competingsurvivalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "competingsurvivalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            explanatory = NULL,
            overalltime = NULL,
            outcome = NULL,
            dod = NULL,
            dooc = NULL,
            awd = NULL,
            awod = NULL,
            analysistype = "overall",
            graystest = FALSE,
            subdistribution = FALSE,
            timepoints = "12,24,36,60",
            confidencelevel = 0.95,
            showrisksets = FALSE,
            showStackedPlot = FALSE,
            showKMvsCIF = FALSE,
            cifColors = "default", ...) {

            super$initialize(
                package="ClinicoPath",
                name="competingsurvival",
                requiresData=TRUE,
                ...)

            private$..explanatory <- jmvcore::OptionVariable$new(
                "explanatory",
                explanatory,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..overalltime <- jmvcore::OptionVariable$new(
                "overalltime",
                overalltime,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..dod <- jmvcore::OptionLevel$new(
                "dod",
                dod,
                variable="(outcome)",
                allowNone=TRUE)
            private$..dooc <- jmvcore::OptionLevel$new(
                "dooc",
                dooc,
                variable="(outcome)",
                allowNone=TRUE)
            private$..awd <- jmvcore::OptionLevel$new(
                "awd",
                awd,
                variable="(outcome)",
                allowNone=TRUE)
            private$..awod <- jmvcore::OptionLevel$new(
                "awod",
                awod,
                variable="(outcome)",
                allowNone=TRUE)
            private$..analysistype <- jmvcore::OptionList$new(
                "analysistype",
                analysistype,
                options=list(
                    "overall",
                    "cause",
                    "compete"),
                default="overall")
            private$..graystest <- jmvcore::OptionBool$new(
                "graystest",
                graystest,
                default=FALSE)
            private$..subdistribution <- jmvcore::OptionBool$new(
                "subdistribution",
                subdistribution,
                default=FALSE)
            private$..timepoints <- jmvcore::OptionString$new(
                "timepoints",
                timepoints,
                default="12,24,36,60")
            private$..confidencelevel <- jmvcore::OptionNumber$new(
                "confidencelevel",
                confidencelevel,
                default=0.95,
                min=0.5,
                max=0.99)
            private$..showrisksets <- jmvcore::OptionBool$new(
                "showrisksets",
                showrisksets,
                default=FALSE)
            private$..showStackedPlot <- jmvcore::OptionBool$new(
                "showStackedPlot",
                showStackedPlot,
                default=FALSE)
            private$..showKMvsCIF <- jmvcore::OptionBool$new(
                "showKMvsCIF",
                showKMvsCIF,
                default=FALSE)
            private$..cifColors <- jmvcore::OptionList$new(
                "cifColors",
                cifColors,
                options=list(
                    "default",
                    "colorblind",
                    "grayscale"),
                default="default")

            self$.addOption(private$..explanatory)
            self$.addOption(private$..overalltime)
            self$.addOption(private$..outcome)
            self$.addOption(private$..dod)
            self$.addOption(private$..dooc)
            self$.addOption(private$..awd)
            self$.addOption(private$..awod)
            self$.addOption(private$..analysistype)
            self$.addOption(private$..graystest)
            self$.addOption(private$..subdistribution)
            self$.addOption(private$..timepoints)
            self$.addOption(private$..confidencelevel)
            self$.addOption(private$..showrisksets)
            self$.addOption(private$..showStackedPlot)
            self$.addOption(private$..showKMvsCIF)
            self$.addOption(private$..cifColors)
        }),
    active = list(
        explanatory = function() private$..explanatory$value,
        overalltime = function() private$..overalltime$value,
        outcome = function() private$..outcome$value,
        dod = function() private$..dod$value,
        dooc = function() private$..dooc$value,
        awd = function() private$..awd$value,
        awod = function() private$..awod$value,
        analysistype = function() private$..analysistype$value,
        graystest = function() private$..graystest$value,
        subdistribution = function() private$..subdistribution$value,
        timepoints = function() private$..timepoints$value,
        confidencelevel = function() private$..confidencelevel$value,
        showrisksets = function() private$..showrisksets$value,
        showStackedPlot = function() private$..showStackedPlot$value,
        showKMvsCIF = function() private$..showKMvsCIF$value,
        cifColors = function() private$..cifColors$value),
    private = list(
        ..explanatory = NA,
        ..overalltime = NA,
        ..outcome = NA,
        ..dod = NA,
        ..dooc = NA,
        ..awd = NA,
        ..awod = NA,
        ..analysistype = NA,
        ..graystest = NA,
        ..subdistribution = NA,
        ..timepoints = NA,
        ..confidencelevel = NA,
        ..showrisksets = NA,
        ..showStackedPlot = NA,
        ..showKMvsCIF = NA,
        ..cifColors = NA)
)

competingsurvivalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "competingsurvivalResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        summary = function() private$.items[["summary"]],
        survivalTable = function() private$.items[["survivalTable"]],
        cuminc = function() private$.items[["cuminc"]],
        comprisksPlot = function() private$.items[["comprisksPlot"]],
        stackedPlot = function() private$.items[["stackedPlot"]],
        kmvscifPlot = function() private$.items[["kmvscifPlot"]],
        interpretation = function() private$.items[["interpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Overall, Cause Specific, and Competing Survival",
                refs=list(
                    "ClinicoPathJamoviModule",
                    "janitor",
                    "labelled",
                    "glue",
                    "finalfit",
                    "survival",
                    "cmprsk",
                    "scales"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do",
                clearWith=list(
                    "explanatory",
                    "outcome",
                    "overalltime")))
            self$add(jmvcore::Html$new(
                options=options,
                name="summary",
                title="Analysis Summary",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="survivalTable",
                title="Survival Analysis Results",
                visible=TRUE,
                rows=0,
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="hr", 
                        `title`="HR", 
                        `type`="number"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cuminc",
                title="Cumulative Incidence Function",
                visible="(analysistype:compete)",
                rows=1,
                columns=list(
                    list(
                        `name`="time", 
                        `title`="Time", 
                        `type`="number"),
                    list(
                        `name`="est_1", 
                        `title`="CIF Disease Death", 
                        `type`="number"),
                    list(
                        `name`="est_2", 
                        `title`="CIF Other Death", 
                        `type`="number"),
                    list(
                        `name`="var_1", 
                        `title`="Variance 1", 
                        `type`="number"),
                    list(
                        `name`="var_2", 
                        `title`="Variance 2", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="comprisksPlot",
                title="Competing Risks Plot",
                width=700,
                height=400,
                renderFun=".plotCompetingRisks",
                visible="(analysistype:compete)",
                clearWith=list(
                    "explanatory",
                    "outcome",
                    "overalltime",
                    "analysistype")))
            self$add(jmvcore::Image$new(
                options=options,
                name="stackedPlot",
                title="Stacked Probability Plot",
                width=700,
                height=500,
                renderFun=".stackedPlot",
                visible="(showStackedPlot && analysistype:compete)",
                clearWith=list(
                    "explanatory",
                    "outcome",
                    "overalltime")))
            self$add(jmvcore::Image$new(
                options=options,
                name="kmvscifPlot",
                title="1-KM vs CIF Comparison",
                width=700,
                height=500,
                renderFun=".kmvscifPlot",
                visible="(showKMvsCIF && analysistype:compete)",
                clearWith=list(
                    "explanatory",
                    "outcome",
                    "overalltime")))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Clinical Interpretation",
                visible=TRUE))}))

competingsurvivalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "competingsurvivalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "competingsurvival",
                version = c(0,0,3),
                options = options,
                results = competingsurvivalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Overall, Cause Specific, and Competing Survival
#'
#' Overall, Cause Specific, and Competing Survival.
#'
#' @examples
#' \donttest{
#' # example will be added
#'}
#' @param data The data as a data frame.
#' @param explanatory .
#' @param overalltime .
#' @param outcome .
#' @param dod .
#' @param dooc .
#' @param awd .
#' @param awod .
#' @param analysistype .
#' @param graystest Perform Gray's test to compare cumulative incidence
#'   functions between groups
#' @param subdistribution Use Fine-Gray subdistribution hazard model for
#'   competing risks regression
#' @param timepoints Comma-separated time points (in months) for cumulative
#'   incidence estimates
#' @param confidencelevel Confidence level for hazard ratio confidence
#'   intervals
#' @param showrisksets Display number at risk table below cumulative incidence
#'   plot
#' @param showStackedPlot Display stacked probability plot with all competing
#'   events
#' @param showKMvsCIF Plot comparison between 1-KM and CIF to show competing
#'   risk bias
#' @param cifColors Color scheme for CIF plots
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$survivalTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cuminc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comprisksPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$stackedPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$kmvscifPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$survivalTable$asDF}
#'
#' \code{as.data.frame(results$survivalTable)}
#'
#' @export
competingsurvival <- function(
    data,
    explanatory,
    overalltime,
    outcome,
    dod,
    dooc,
    awd,
    awod,
    analysistype = "overall",
    graystest = FALSE,
    subdistribution = FALSE,
    timepoints = "12,24,36,60",
    confidencelevel = 0.95,
    showrisksets = FALSE,
    showStackedPlot = FALSE,
    showKMvsCIF = FALSE,
    cifColors = "default") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("competingsurvival requires jmvcore to be installed (restart may be required)")

    if ( ! missing(explanatory)) explanatory <- jmvcore::resolveQuo(jmvcore::enquo(explanatory))
    if ( ! missing(overalltime)) overalltime <- jmvcore::resolveQuo(jmvcore::enquo(overalltime))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(explanatory), explanatory, NULL),
            `if`( ! missing(overalltime), overalltime, NULL),
            `if`( ! missing(outcome), outcome, NULL))

    for (v in explanatory) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in outcome) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- competingsurvivalOptions$new(
        explanatory = explanatory,
        overalltime = overalltime,
        outcome = outcome,
        dod = dod,
        dooc = dooc,
        awd = awd,
        awod = awod,
        analysistype = analysistype,
        graystest = graystest,
        subdistribution = subdistribution,
        timepoints = timepoints,
        confidencelevel = confidencelevel,
        showrisksets = showrisksets,
        showStackedPlot = showStackedPlot,
        showKMvsCIF = showKMvsCIF,
        cifColors = cifColors)

    analysis <- competingsurvivalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

