
# This file is automatically generated, you probably don't want to edit this

continuousrelationshipOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "continuousrelationshipOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            outcome = NULL,
            predictor = NULL,
            covariates = NULL,
            modelType = "spline",
            nKnots = "4",
            knotPositions = "quantile",
            plotType = "doseresponse",
            referenceValue = NULL,
            showCI = TRUE,
            showRug = TRUE,
            showGuidance = TRUE,
            compareWithLinear = TRUE,
            showCategorizedPitfall = FALSE,
            testLinearity = TRUE,
            showModelFit = TRUE,
            showModel = FALSE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="continuousrelationship",
                requiresData=TRUE,
                ...)

            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                suggested=list(
                    "continuous",
                    "nominal"))
            private$..predictor <- jmvcore::OptionVariable$new(
                "predictor",
                predictor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous",
                    "nominal"),
                default=NULL)
            private$..modelType <- jmvcore::OptionList$new(
                "modelType",
                modelType,
                options=list(
                    "spline",
                    "fp",
                    "linear",
                    "categorized"),
                default="spline")
            private$..nKnots <- jmvcore::OptionList$new(
                "nKnots",
                nKnots,
                options=list(
                    "3",
                    "4",
                    "5"),
                default="4")
            private$..knotPositions <- jmvcore::OptionList$new(
                "knotPositions",
                knotPositions,
                options=list(
                    "quantile",
                    "equal",
                    "clinical"),
                default="quantile")
            private$..plotType <- jmvcore::OptionList$new(
                "plotType",
                plotType,
                options=list(
                    "doseresponse",
                    "partial",
                    "comparison"),
                default="doseresponse")
            private$..referenceValue <- jmvcore::OptionNumber$new(
                "referenceValue",
                referenceValue)
            private$..showCI <- jmvcore::OptionBool$new(
                "showCI",
                showCI,
                default=TRUE)
            private$..showRug <- jmvcore::OptionBool$new(
                "showRug",
                showRug,
                default=TRUE)
            private$..showGuidance <- jmvcore::OptionBool$new(
                "showGuidance",
                showGuidance,
                default=TRUE)
            private$..compareWithLinear <- jmvcore::OptionBool$new(
                "compareWithLinear",
                compareWithLinear,
                default=TRUE)
            private$..showCategorizedPitfall <- jmvcore::OptionBool$new(
                "showCategorizedPitfall",
                showCategorizedPitfall,
                default=FALSE)
            private$..testLinearity <- jmvcore::OptionBool$new(
                "testLinearity",
                testLinearity,
                default=TRUE)
            private$..showModelFit <- jmvcore::OptionBool$new(
                "showModelFit",
                showModelFit,
                default=TRUE)
            private$..showModel <- jmvcore::OptionBool$new(
                "showModel",
                showModel,
                default=FALSE)
            private$..exportPredictions <- jmvcore::OptionOutput$new(
                "exportPredictions")

            self$.addOption(private$..outcome)
            self$.addOption(private$..predictor)
            self$.addOption(private$..covariates)
            self$.addOption(private$..modelType)
            self$.addOption(private$..nKnots)
            self$.addOption(private$..knotPositions)
            self$.addOption(private$..plotType)
            self$.addOption(private$..referenceValue)
            self$.addOption(private$..showCI)
            self$.addOption(private$..showRug)
            self$.addOption(private$..showGuidance)
            self$.addOption(private$..compareWithLinear)
            self$.addOption(private$..showCategorizedPitfall)
            self$.addOption(private$..testLinearity)
            self$.addOption(private$..showModelFit)
            self$.addOption(private$..showModel)
            self$.addOption(private$..exportPredictions)
        }),
    active = list(
        outcome = function() private$..outcome$value,
        predictor = function() private$..predictor$value,
        covariates = function() private$..covariates$value,
        modelType = function() private$..modelType$value,
        nKnots = function() private$..nKnots$value,
        knotPositions = function() private$..knotPositions$value,
        plotType = function() private$..plotType$value,
        referenceValue = function() private$..referenceValue$value,
        showCI = function() private$..showCI$value,
        showRug = function() private$..showRug$value,
        showGuidance = function() private$..showGuidance$value,
        compareWithLinear = function() private$..compareWithLinear$value,
        showCategorizedPitfall = function() private$..showCategorizedPitfall$value,
        testLinearity = function() private$..testLinearity$value,
        showModelFit = function() private$..showModelFit$value,
        showModel = function() private$..showModel$value,
        exportPredictions = function() private$..exportPredictions$value),
    private = list(
        ..outcome = NA,
        ..predictor = NA,
        ..covariates = NA,
        ..modelType = NA,
        ..nKnots = NA,
        ..knotPositions = NA,
        ..plotType = NA,
        ..referenceValue = NA,
        ..showCI = NA,
        ..showRug = NA,
        ..showGuidance = NA,
        ..compareWithLinear = NA,
        ..showCategorizedPitfall = NA,
        ..testLinearity = NA,
        ..showModelFit = NA,
        ..showModel = NA,
        ..exportPredictions = NA)
)

continuousrelationshipResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "continuousrelationshipResults",
    inherit = jmvcore::Group,
    active = list(
        guidance = function() private$.items[["guidance"]],
        warningMessage = function() private$.items[["warningMessage"]],
        modelFormula = function() private$.items[["modelFormula"]],
        linearityTest = function() private$.items[["linearityTest"]],
        modelFit = function() private$.items[["modelFit"]],
        doseResponsePlot = function() private$.items[["doseResponsePlot"]],
        partialEffectPlot = function() private$.items[["partialEffectPlot"]],
        comparisonPlot = function() private$.items[["comparisonPlot"]],
        categorizedPlot = function() private$.items[["categorizedPlot"]],
        interpretationGuide = function() private$.items[["interpretationGuide"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Continuous Variable Relationship Analysis",
                refs=list(
                    "ClinicoPathJamoviModule"))
            self$add(jmvcore::Html$new(
                options=options,
                name="guidance",
                title="BMJ Best Practices Guidance",
                visible="(showGuidance)",
                clearWith=list(
                    "predictor",
                    "outcome")))
            self$add(jmvcore::Html$new(
                options=options,
                name="warningMessage",
                title="Important Warnings",
                visible=FALSE))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelFormula",
                title="Model Formula",
                visible="(showModel)",
                clearWith=list(
                    "predictor",
                    "outcome",
                    "modelType",
                    "nKnots")))
            self$add(jmvcore::Table$new(
                options=options,
                name="linearityTest",
                title="Test for Non-linearity",
                visible="(testLinearity)",
                clearWith=list(
                    "predictor",
                    "outcome",
                    "modelType"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Test Statistic", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelFit",
                title="Model Fit Statistics",
                visible="(showModelFit)",
                clearWith=list(
                    "predictor",
                    "outcome",
                    "modelType"),
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number"),
                    list(
                        `name`="loglik", 
                        `title`="Log Likelihood", 
                        `type`="number"),
                    list(
                        `name`="r2", 
                        `title`="R\u00B2", 
                        `type`="number", 
                        `visible`=FALSE))))
            self$add(jmvcore::Image$new(
                options=options,
                name="doseResponsePlot",
                title="Dose-Response Relationship",
                renderFun=".doseResponsePlot",
                visible="(plotType:doseresponse)",
                clearWith=list(
                    "predictor",
                    "outcome",
                    "modelType",
                    "referenceValue"),
                height=500,
                width=700))
            self$add(jmvcore::Image$new(
                options=options,
                name="partialEffectPlot",
                title="Partial Effect Plot",
                renderFun=".partialEffectPlot",
                visible="(plotType:partial)",
                clearWith=list(
                    "predictor",
                    "outcome",
                    "modelType",
                    "covariates"),
                height=500,
                width=700))
            self$add(jmvcore::Image$new(
                options=options,
                name="comparisonPlot",
                title="Model Comparison Plot",
                renderFun=".comparisonPlot",
                visible="(plotType:comparison || compareWithLinear)",
                clearWith=list(
                    "predictor",
                    "outcome",
                    "modelType"),
                height=600,
                width=800))
            self$add(jmvcore::Image$new(
                options=options,
                name="categorizedPlot",
                title="Categorization Pitfall Demonstration",
                renderFun=".categorizedPlot",
                visible="(showCategorizedPitfall)",
                clearWith=list(
                    "predictor",
                    "outcome"),
                height=500,
                width=700))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="interpretationGuide",
                title="Interpretation Guide",
                visible="(showGuidance)",
                clearWith=list(
                    "predictor",
                    "outcome",
                    "modelType")))}))

continuousrelationshipBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "continuousrelationshipBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "continuousrelationship",
                version = c(0,0,3),
                options = options,
                results = continuousrelationshipResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Continuous Variable Relationship Analysis
#'
#' Analyzes relationships between continuous variables in clinical research 
#' using  evidence-based approaches from BMJ best practices. Avoids common 
#' pitfalls like  arbitrary categorization and linear assumptions.
#' 
#'
#' @examples
#' # Example: Analyzing BMI vs mortality risk
#' continuousrelationship(
#'     data = clinical_data,
#'     outcome = "mortality",
#'     predictor = "bmi",
#'     modelType = "spline",
#'     nKnots = 4,
#'     showGuidance = TRUE
#' )
#'
#' @param data The dataset containing clinical variables
#' @param outcome The outcome/dependent variable (can be continuous or binary)
#' @param predictor The continuous predictor variable to analyze
#' @param covariates Variables to adjust for in the analysis
#' @param modelType Statistical approach for modeling the relationship.
#'   Splines are recommended for most clinical applications.
#' @param nKnots Number of knots for spline models. More knots = more
#'   flexibility
#' @param knotPositions How to position knots across the predictor range
#' @param plotType Type of visualization to create
#' @param referenceValue Reference value for the predictor (e.g., BMI=25).  If
#'   not specified, uses median value.
#' @param showCI Display 95\% confidence intervals on plots
#' @param showRug Show rug plot of actual data points
#' @param showGuidance Display educational guidance based on BMJ best
#'   practices to help interpret results and avoid common mistakes
#' @param compareWithLinear Show comparison with simple linear model to
#'   demonstrate the importance of flexible modeling
#' @param showCategorizedPitfall Educational: Show what happens when
#'   continuous variables are inappropriately categorized (with warning)
#' @param testLinearity Perform statistical test for non-linear relationship
#' @param showModelFit Display AIC, BIC, and other fit statistics
#' @param showModel Display the model formula as HTML in the results
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$guidance} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$warningMessage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelFormula} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$linearityTest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelFit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$doseResponsePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$partialEffectPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$comparisonPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$categorizedPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interpretationGuide} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$linearityTest$asDF}
#'
#' \code{as.data.frame(results$linearityTest)}
#'
#' @export
continuousrelationship <- function(
    data,
    outcome,
    predictor,
    covariates = NULL,
    modelType = "spline",
    nKnots = "4",
    knotPositions = "quantile",
    plotType = "doseresponse",
    referenceValue,
    showCI = TRUE,
    showRug = TRUE,
    showGuidance = TRUE,
    compareWithLinear = TRUE,
    showCategorizedPitfall = FALSE,
    testLinearity = TRUE,
    showModelFit = TRUE,
    showModel = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("continuousrelationship requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(predictor)) predictor <- jmvcore::resolveQuo(jmvcore::enquo(predictor))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(predictor), predictor, NULL),
            `if`( ! missing(covariates), covariates, NULL))


    options <- continuousrelationshipOptions$new(
        outcome = outcome,
        predictor = predictor,
        covariates = covariates,
        modelType = modelType,
        nKnots = nKnots,
        knotPositions = knotPositions,
        plotType = plotType,
        referenceValue = referenceValue,
        showCI = showCI,
        showRug = showRug,
        showGuidance = showGuidance,
        compareWithLinear = compareWithLinear,
        showCategorizedPitfall = showCategorizedPitfall,
        testLinearity = testLinearity,
        showModelFit = showModelFit,
        showModel = showModel)

    analysis <- continuousrelationshipClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

