
# This file is automatically generated, you probably don't want to edit this

coxphwOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "coxphwOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            elapsedtime = NULL,
            outcome = NULL,
            covariates = NULL,
            outcomeLevel = "1",
            weight_method = "average",
            alpha = 0.5,
            offset_variable = NULL,
            stratify_variable = NULL,
            cluster_variable = NULL,
            confidence_level = 0.95,
            max_iterations = 100,
            convergence_tolerance = 0.000001,
            bootstrap_ci = FALSE,
            bootstrap_samples = 500,
            show_model_summary = TRUE,
            show_coefficients = TRUE,
            show_weights = TRUE,
            show_diagnostics = TRUE,
            show_comparison = TRUE,
            show_weight_plots = TRUE,
            show_residual_plots = TRUE,
            show_survival_plots = TRUE,
            show_forest_plot = TRUE,
            showSummaries = FALSE,
            showExplanations = FALSE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="coxphw",
                requiresData=TRUE,
                ...)

            private$..elapsedtime <- jmvcore::OptionVariable$new(
                "elapsedtime",
                elapsedtime,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..outcomeLevel <- jmvcore::OptionString$new(
                "outcomeLevel",
                outcomeLevel,
                default="1")
            private$..weight_method <- jmvcore::OptionList$new(
                "weight_method",
                weight_method,
                options=list(
                    "average",
                    "schoenfeld",
                    "prentice",
                    "logrankvar"),
                default="average")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                max=1,
                default=0.5)
            private$..offset_variable <- jmvcore::OptionVariable$new(
                "offset_variable",
                offset_variable,
                permitted=list(
                    "numeric"))
            private$..stratify_variable <- jmvcore::OptionVariable$new(
                "stratify_variable",
                stratify_variable,
                permitted=list(
                    "factor",
                    "numeric"))
            private$..cluster_variable <- jmvcore::OptionVariable$new(
                "cluster_variable",
                cluster_variable,
                permitted=list(
                    "factor",
                    "numeric"))
            private$..confidence_level <- jmvcore::OptionNumber$new(
                "confidence_level",
                confidence_level,
                min=0.5,
                max=0.99,
                default=0.95)
            private$..max_iterations <- jmvcore::OptionNumber$new(
                "max_iterations",
                max_iterations,
                min=10,
                max=1000,
                default=100)
            private$..convergence_tolerance <- jmvcore::OptionNumber$new(
                "convergence_tolerance",
                convergence_tolerance,
                min=1e-8,
                max=0.01,
                default=0.000001)
            private$..bootstrap_ci <- jmvcore::OptionBool$new(
                "bootstrap_ci",
                bootstrap_ci,
                default=FALSE)
            private$..bootstrap_samples <- jmvcore::OptionNumber$new(
                "bootstrap_samples",
                bootstrap_samples,
                min=100,
                max=2000,
                default=500)
            private$..show_model_summary <- jmvcore::OptionBool$new(
                "show_model_summary",
                show_model_summary,
                default=TRUE)
            private$..show_coefficients <- jmvcore::OptionBool$new(
                "show_coefficients",
                show_coefficients,
                default=TRUE)
            private$..show_weights <- jmvcore::OptionBool$new(
                "show_weights",
                show_weights,
                default=TRUE)
            private$..show_diagnostics <- jmvcore::OptionBool$new(
                "show_diagnostics",
                show_diagnostics,
                default=TRUE)
            private$..show_comparison <- jmvcore::OptionBool$new(
                "show_comparison",
                show_comparison,
                default=TRUE)
            private$..show_weight_plots <- jmvcore::OptionBool$new(
                "show_weight_plots",
                show_weight_plots,
                default=TRUE)
            private$..show_residual_plots <- jmvcore::OptionBool$new(
                "show_residual_plots",
                show_residual_plots,
                default=TRUE)
            private$..show_survival_plots <- jmvcore::OptionBool$new(
                "show_survival_plots",
                show_survival_plots,
                default=TRUE)
            private$..show_forest_plot <- jmvcore::OptionBool$new(
                "show_forest_plot",
                show_forest_plot,
                default=TRUE)
            private$..showSummaries <- jmvcore::OptionBool$new(
                "showSummaries",
                showSummaries,
                default=FALSE)
            private$..showExplanations <- jmvcore::OptionBool$new(
                "showExplanations",
                showExplanations,
                default=FALSE)

            self$.addOption(private$..elapsedtime)
            self$.addOption(private$..outcome)
            self$.addOption(private$..covariates)
            self$.addOption(private$..outcomeLevel)
            self$.addOption(private$..weight_method)
            self$.addOption(private$..alpha)
            self$.addOption(private$..offset_variable)
            self$.addOption(private$..stratify_variable)
            self$.addOption(private$..cluster_variable)
            self$.addOption(private$..confidence_level)
            self$.addOption(private$..max_iterations)
            self$.addOption(private$..convergence_tolerance)
            self$.addOption(private$..bootstrap_ci)
            self$.addOption(private$..bootstrap_samples)
            self$.addOption(private$..show_model_summary)
            self$.addOption(private$..show_coefficients)
            self$.addOption(private$..show_weights)
            self$.addOption(private$..show_diagnostics)
            self$.addOption(private$..show_comparison)
            self$.addOption(private$..show_weight_plots)
            self$.addOption(private$..show_residual_plots)
            self$.addOption(private$..show_survival_plots)
            self$.addOption(private$..show_forest_plot)
            self$.addOption(private$..showSummaries)
            self$.addOption(private$..showExplanations)
        }),
    active = list(
        elapsedtime = function() private$..elapsedtime$value,
        outcome = function() private$..outcome$value,
        covariates = function() private$..covariates$value,
        outcomeLevel = function() private$..outcomeLevel$value,
        weight_method = function() private$..weight_method$value,
        alpha = function() private$..alpha$value,
        offset_variable = function() private$..offset_variable$value,
        stratify_variable = function() private$..stratify_variable$value,
        cluster_variable = function() private$..cluster_variable$value,
        confidence_level = function() private$..confidence_level$value,
        max_iterations = function() private$..max_iterations$value,
        convergence_tolerance = function() private$..convergence_tolerance$value,
        bootstrap_ci = function() private$..bootstrap_ci$value,
        bootstrap_samples = function() private$..bootstrap_samples$value,
        show_model_summary = function() private$..show_model_summary$value,
        show_coefficients = function() private$..show_coefficients$value,
        show_weights = function() private$..show_weights$value,
        show_diagnostics = function() private$..show_diagnostics$value,
        show_comparison = function() private$..show_comparison$value,
        show_weight_plots = function() private$..show_weight_plots$value,
        show_residual_plots = function() private$..show_residual_plots$value,
        show_survival_plots = function() private$..show_survival_plots$value,
        show_forest_plot = function() private$..show_forest_plot$value,
        showSummaries = function() private$..showSummaries$value,
        showExplanations = function() private$..showExplanations$value),
    private = list(
        ..elapsedtime = NA,
        ..outcome = NA,
        ..covariates = NA,
        ..outcomeLevel = NA,
        ..weight_method = NA,
        ..alpha = NA,
        ..offset_variable = NA,
        ..stratify_variable = NA,
        ..cluster_variable = NA,
        ..confidence_level = NA,
        ..max_iterations = NA,
        ..convergence_tolerance = NA,
        ..bootstrap_ci = NA,
        ..bootstrap_samples = NA,
        ..show_model_summary = NA,
        ..show_coefficients = NA,
        ..show_weights = NA,
        ..show_diagnostics = NA,
        ..show_comparison = NA,
        ..show_weight_plots = NA,
        ..show_residual_plots = NA,
        ..show_survival_plots = NA,
        ..show_forest_plot = NA,
        ..showSummaries = NA,
        ..showExplanations = NA)
)

coxphwResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "coxphwResults",
    inherit = jmvcore::Group,
    active = list(
        modelSummary = function() private$.items[["modelSummary"]],
        coefficients = function() private$.items[["coefficients"]],
        weightAnalysis = function() private$.items[["weightAnalysis"]],
        diagnostics = function() private$.items[["diagnostics"]],
        modelComparison = function() private$.items[["modelComparison"]],
        convergenceInfo = function() private$.items[["convergenceInfo"]],
        rareEventAnalysis = function() private$.items[["rareEventAnalysis"]],
        weightPlots = function() private$.items[["weightPlots"]],
        residualPlots = function() private$.items[["residualPlots"]],
        survivalPlots = function() private$.items[["survivalPlots"]],
        forestPlot = function() private$.items[["forestPlot"]],
        comparisonPlots = function() private$.items[["comparisonPlots"]],
        summaryTable = function() private$.items[["summaryTable"]],
        methodExplanation = function() private$.items[["methodExplanation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Weighted Cox Regression")
            self$add(jmvcore::Table$new(
                options=options,
                name="modelSummary",
                title="Model Summary",
                visible="(show_model_summary)",
                columns=list(
                    list(
                        `name`="term", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coefficients",
                title="Weighted Cox Coefficients",
                visible="(show_coefficients)",
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="z", 
                        `title`="z", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pvalue", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ciLower", 
                        `title`="Lower CI", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciUpper", 
                        `title`="Upper CI", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="hazard_ratio", 
                        `title`="HR", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="hr_lower", 
                        `title`="HR Lower", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="hr_upper", 
                        `title`="HR Upper", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="weightAnalysis",
                title="Weight Distribution Analysis",
                visible="(show_weights)",
                columns=list(
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="diagnostics",
                title="Model Diagnostics",
                visible="(show_diagnostics)",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelComparison",
                title="Model Comparison",
                visible="(show_comparison)",
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="loglik", 
                        `title`="Log-Likelihood", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="concordance", 
                        `title`="C-Index", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="events", 
                        `title`="Events", 
                        `type`="integer"),
                    list(
                        `name`="weight_effect", 
                        `title`="Weight Effect", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="convergenceInfo",
                title="Convergence Information",
                visible="(show_model_summary)",
                columns=list(
                    list(
                        `name`="criterion", 
                        `title`="Criterion", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rareEventAnalysis",
                title="Rare Event Analysis",
                visible="(show_weights)",
                columns=list(
                    list(
                        `name`="covariate", 
                        `title`="Covariate", 
                        `type`="text"),
                    list(
                        `name`="event_rate", 
                        `title`="Event Rate", 
                        `type`="number", 
                        `format`="zto,pc"),
                    list(
                        `name`="imbalance_ratio", 
                        `title`="Imbalance Ratio", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="weight_impact", 
                        `title`="Weight Impact", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="weightPlots",
                title="Weight Distribution Plots",
                visible="(show_weight_plots)",
                width=800,
                height=600))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualPlots",
                title="Residual Diagnostic Plots",
                visible="(show_residual_plots)",
                width=800,
                height=600))
            self$add(jmvcore::Image$new(
                options=options,
                name="survivalPlots",
                title="Survival Curves",
                visible="(show_survival_plots)",
                width=800,
                height=600))
            self$add(jmvcore::Image$new(
                options=options,
                name="forestPlot",
                title="Forest Plot",
                visible="(show_forest_plot)",
                width=800,
                height=600))
            self$add(jmvcore::Image$new(
                options=options,
                name="comparisonPlots",
                title="Model Comparison Plots",
                visible="(show_comparison)",
                width=800,
                height=600))
            self$add(jmvcore::Html$new(
                options=options,
                name="summaryTable",
                title="Analysis Summary",
                visible="(showSummaries)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodExplanation",
                title="Method Explanation",
                visible="(showExplanations)"))}))

coxphwBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "coxphwBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "coxphw",
                version = c(1,0,0),
                options = options,
                results = coxphwResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Weighted Cox Regression
#'
#' Implements weighted Cox proportional hazards regression models specifically 
#' designed for rare events and imbalanced survival data. Uses average hazard 
#' weights to improve estimation accuracy when events are rare or covariates 
#' are imbalanced, providing more reliable hazard ratios and confidence 
#' intervals in challenging clinical research scenarios.
#'
#' @examples
#' # Example: Weighted Cox regression for rare events
#' library(survival)
#' library(coxphw)
#'
#' coxphw(
#'     data = rare_event_data,
#'     elapsedtime = "time",
#'     outcome = "status",
#'     outcomeLevel = "1",
#'     covariates = c("age", "treatment", "biomarker"),
#'     weight_method = "average",
#'     alpha = 0.5
#' )
#'
#' @param data the data as a data frame
#' @param elapsedtime Survival time or follow-up duration variable
#' @param outcome Event indicator variable (0/1, FALSE/TRUE, or factor)
#' @param covariates Predictor variables for the Cox model
#' @param outcomeLevel Level of outcome variable indicating event occurrence
#' @param weight_method Weighting method for the partial likelihood
#' @param alpha Weight parameter (0=log-rank, 0.5=average, 1=Breslow)
#' @param offset_variable Optional offset variable for the model
#' @param stratify_variable Variable for stratified analysis
#' @param cluster_variable Variable defining clusters for robust variance
#' @param confidence_level Confidence level for intervals
#' @param max_iterations Maximum number of iterations
#' @param convergence_tolerance Convergence tolerance for estimation
#' @param bootstrap_ci Compute bootstrap confidence intervals
#' @param bootstrap_samples Number of bootstrap samples
#' @param show_model_summary Display comprehensive model summary
#' @param show_coefficients Display coefficient estimates table
#' @param show_weights Display weight distribution analysis
#' @param show_diagnostics Display model diagnostics
#' @param show_comparison Compare weighted vs standard Cox models
#' @param show_weight_plots Display weight distribution plots
#' @param show_residual_plots Display residual diagnostic plots
#' @param show_survival_plots Display survival curves
#' @param show_forest_plot Display forest plot of hazard ratios
#' @param showSummaries Generate natural language summaries
#' @param showExplanations Show detailed methodology explanations
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$weightAnalysis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$diagnostics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelComparison} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$convergenceInfo} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rareEventAnalysis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$weightPlots} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualPlots} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$survivalPlots} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$forestPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$comparisonPlots} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$methodExplanation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$modelSummary$asDF}
#'
#' \code{as.data.frame(results$modelSummary)}
#'
#' @export
coxphw <- function(
    data,
    elapsedtime,
    outcome,
    covariates,
    outcomeLevel = "1",
    weight_method = "average",
    alpha = 0.5,
    offset_variable,
    stratify_variable,
    cluster_variable,
    confidence_level = 0.95,
    max_iterations = 100,
    convergence_tolerance = 0.000001,
    bootstrap_ci = FALSE,
    bootstrap_samples = 500,
    show_model_summary = TRUE,
    show_coefficients = TRUE,
    show_weights = TRUE,
    show_diagnostics = TRUE,
    show_comparison = TRUE,
    show_weight_plots = TRUE,
    show_residual_plots = TRUE,
    show_survival_plots = TRUE,
    show_forest_plot = TRUE,
    showSummaries = FALSE,
    showExplanations = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("coxphw requires jmvcore to be installed (restart may be required)")

    if ( ! missing(elapsedtime)) elapsedtime <- jmvcore::resolveQuo(jmvcore::enquo(elapsedtime))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(offset_variable)) offset_variable <- jmvcore::resolveQuo(jmvcore::enquo(offset_variable))
    if ( ! missing(stratify_variable)) stratify_variable <- jmvcore::resolveQuo(jmvcore::enquo(stratify_variable))
    if ( ! missing(cluster_variable)) cluster_variable <- jmvcore::resolveQuo(jmvcore::enquo(cluster_variable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(elapsedtime), elapsedtime, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(offset_variable), offset_variable, NULL),
            `if`( ! missing(stratify_variable), stratify_variable, NULL),
            `if`( ! missing(cluster_variable), cluster_variable, NULL))


    options <- coxphwOptions$new(
        elapsedtime = elapsedtime,
        outcome = outcome,
        covariates = covariates,
        outcomeLevel = outcomeLevel,
        weight_method = weight_method,
        alpha = alpha,
        offset_variable = offset_variable,
        stratify_variable = stratify_variable,
        cluster_variable = cluster_variable,
        confidence_level = confidence_level,
        max_iterations = max_iterations,
        convergence_tolerance = convergence_tolerance,
        bootstrap_ci = bootstrap_ci,
        bootstrap_samples = bootstrap_samples,
        show_model_summary = show_model_summary,
        show_coefficients = show_coefficients,
        show_weights = show_weights,
        show_diagnostics = show_diagnostics,
        show_comparison = show_comparison,
        show_weight_plots = show_weight_plots,
        show_residual_plots = show_residual_plots,
        show_survival_plots = show_survival_plots,
        show_forest_plot = show_forest_plot,
        showSummaries = showSummaries,
        showExplanations = showExplanations)

    analysis <- coxphwClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

