
# This file is automatically generated, you probably don't want to edit this

ggflowchartOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ggflowchartOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            from_var = NULL,
            to_var = NULL,
            group_var = NULL,
            node_fill_palette = "clinical_blue",
            plot_title = "Study Flowchart",
            show_interpretation = TRUE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="ggflowchart",
                requiresData=TRUE,
                ...)

            private$..from_var <- jmvcore::OptionVariable$new(
                "from_var",
                from_var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..to_var <- jmvcore::OptionVariable$new(
                "to_var",
                to_var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group_var <- jmvcore::OptionVariable$new(
                "group_var",
                group_var,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..node_fill_palette <- jmvcore::OptionList$new(
                "node_fill_palette",
                node_fill_palette,
                options=list(
                    "clinical_blue",
                    "modern_gray",
                    "viridis",
                    "set1",
                    "pastel"),
                default="clinical_blue")
            private$..plot_title <- jmvcore::OptionString$new(
                "plot_title",
                plot_title,
                default="Study Flowchart")
            private$..show_interpretation <- jmvcore::OptionBool$new(
                "show_interpretation",
                show_interpretation,
                default=TRUE)

            self$.addOption(private$..from_var)
            self$.addOption(private$..to_var)
            self$.addOption(private$..group_var)
            self$.addOption(private$..node_fill_palette)
            self$.addOption(private$..plot_title)
            self$.addOption(private$..show_interpretation)
        }),
    active = list(
        from_var = function() private$..from_var$value,
        to_var = function() private$..to_var$value,
        group_var = function() private$..group_var$value,
        node_fill_palette = function() private$..node_fill_palette$value,
        plot_title = function() private$..plot_title$value,
        show_interpretation = function() private$..show_interpretation$value),
    private = list(
        ..from_var = NA,
        ..to_var = NA,
        ..group_var = NA,
        ..node_fill_palette = NA,
        ..plot_title = NA,
        ..show_interpretation = NA)
)

ggflowchartResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ggflowchartResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        plot = function() private$.items[["plot"]],
        interpretation = function() private$.items[["interpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ggFlowchart")
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="Instructions",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="ggFlowchart",
                width=800,
                height=600,
                renderFun=".plot"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Usage Guide",
                visible="(show_interpretation)"))}))

ggflowchartBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ggflowchartBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "ggflowchart",
                version = c(0,0,3),
                options = options,
                results = ggflowchartResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' ggFlowchart
#'
#' Creates modern flowcharts using ggflowchart package with ggplot2 styling.
#' This module provides an alternative flowchart approach using the 
#' ggflowchart 
#' package for creating publication-ready flowcharts with ggplot2 aesthetics.
#' Complements the existing DiagrammeR-based flowchart module with modern 
#' ggplot2 integration and customizable styling options.
#' 
#'
#' @examples
#' \donttest{
#' # Example:
#' # 1. Prepare data with 'from' and 'to' node connections.
#' # 2. Customize with ggplot2-style themes and colors.
#' # 3. Generate modern flowcharts with publication quality.
#'}
#' @param data The data as a data frame.
#' @param from_var Variable defining the starting nodes for flowchart
#'   connections.
#' @param to_var Variable defining the ending nodes for flowchart connections.
#' @param group_var Optional variable for grouping nodes by categories.
#' @param node_fill_palette Color palette for node filling.
#' @param plot_title Title for the flowchart.
#' @param show_interpretation If TRUE, displays usage guidelines.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
ggflowchart <- function(
    data,
    from_var,
    to_var,
    group_var,
    node_fill_palette = "clinical_blue",
    plot_title = "Study Flowchart",
    show_interpretation = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ggflowchart requires jmvcore to be installed (restart may be required)")

    if ( ! missing(from_var)) from_var <- jmvcore::resolveQuo(jmvcore::enquo(from_var))
    if ( ! missing(to_var)) to_var <- jmvcore::resolveQuo(jmvcore::enquo(to_var))
    if ( ! missing(group_var)) group_var <- jmvcore::resolveQuo(jmvcore::enquo(group_var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(from_var), from_var, NULL),
            `if`( ! missing(to_var), to_var, NULL),
            `if`( ! missing(group_var), group_var, NULL))

    for (v in from_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in to_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ggflowchartOptions$new(
        from_var = from_var,
        to_var = to_var,
        group_var = group_var,
        node_fill_palette = node_fill_palette,
        plot_title = plot_title,
        show_interpretation = show_interpretation)

    analysis <- ggflowchartClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

