
# This file is automatically generated, you probably don't want to edit this

jjpiestatsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jjpiestatsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            grvar = NULL,
            typestatistics = "parametric",
            originaltheme = FALSE,
            resultssubtitle = TRUE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="jjpiestats",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..grvar <- jmvcore::OptionVariable$new(
                "grvar",
                grvar,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..typestatistics <- jmvcore::OptionList$new(
                "typestatistics",
                typestatistics,
                options=list(
                    "parametric",
                    "nonparametric",
                    "robust",
                    "bayes"),
                default="parametric")
            private$..originaltheme <- jmvcore::OptionBool$new(
                "originaltheme",
                originaltheme,
                default=FALSE)
            private$..resultssubtitle <- jmvcore::OptionBool$new(
                "resultssubtitle",
                resultssubtitle,
                default=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..grvar)
            self$.addOption(private$..typestatistics)
            self$.addOption(private$..originaltheme)
            self$.addOption(private$..resultssubtitle)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        grvar = function() private$..grvar$value,
        typestatistics = function() private$..typestatistics$value,
        originaltheme = function() private$..originaltheme$value,
        resultssubtitle = function() private$..resultssubtitle$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..grvar = NA,
        ..typestatistics = NA,
        ..originaltheme = NA,
        ..resultssubtitle = NA)
)

jjpiestatsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jjpiestatsResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        plot4 = function() private$.items[["plot4"]],
        plot2 = function() private$.items[["plot2"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Pie Charts",
                refs=list(
                    "ggplot2",
                    "ggstatsplot",
                    "ClinicoPathJamoviModule"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do",
                clearWith=list(
                    "dep",
                    "group",
                    "grvar",
                    "direction",
                    "originaltheme")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot4",
                title="`${group} - {dep} by {grvar}`",
                width=800,
                height=300,
                renderFun=".plot4",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "group",
                    "grvar",
                    "direction",
                    "originaltheme"),
                visible="(grvar)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="`${group} - {dep}`",
                width=400,
                height=300,
                renderFun=".plot2",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "group",
                    "grvar",
                    "direction",
                    "originaltheme"),
                visible="(group)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="`${dep}`",
                width=400,
                height=300,
                renderFun=".plot1",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "group",
                    "grvar",
                    "direction",
                    "originaltheme"),
                visible="(dep)"))}))

jjpiestatsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jjpiestatsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "jjpiestats",
                version = c(0,0,3),
                options = options,
                results = jjpiestatsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Pie Charts
#'
#' 
#'
#' @examples
#' \donttest{
#' # example will be added
#'}
#' @param data The data as a data frame.
#' @param dep .
#' @param group .
#' @param grvar .
#' @param typestatistics .
#' @param originaltheme .
#' @param resultssubtitle .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot4} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
jjpiestats <- function(
    data,
    dep,
    group,
    grvar,
    typestatistics = "parametric",
    originaltheme = FALSE,
    resultssubtitle = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jjpiestats requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(grvar)) grvar <- jmvcore::resolveQuo(jmvcore::enquo(grvar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(grvar), grvar, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in grvar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jjpiestatsOptions$new(
        dep = dep,
        group = group,
        grvar = grvar,
        typestatistics = typestatistics,
        originaltheme = originaltheme,
        resultssubtitle = resultssubtitle)

    analysis <- jjpiestatsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

