
# This file is automatically generated, you probably don't want to edit this

jjwithinstats3Options <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jjwithinstats3Options",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            excl = TRUE,
            originaltheme = FALSE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="jjwithinstats3",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariables$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..excl <- jmvcore::OptionBool$new(
                "excl",
                excl,
                default=TRUE)
            private$..originaltheme <- jmvcore::OptionBool$new(
                "originaltheme",
                originaltheme,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..excl)
            self$.addOption(private$..originaltheme)
        }),
    active = list(
        dep = function() private$..dep$value,
        excl = function() private$..excl$value,
        originaltheme = function() private$..originaltheme$value),
    private = list(
        ..dep = NA,
        ..excl = NA,
        ..originaltheme = NA)
)

jjwithinstats3Results <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jjwithinstats3Results",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        text1 = function() private$.items[["text1"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Violin Plots to Compare Repeated Measurements for Continuous Variables",
                refs=list(
                    "ggplot2",
                    "ggstatsplot",
                    "ClinicoPathJamoviModule"),
                clearWith=list(
                    "pairs",
                    "excl",
                    "originaltheme"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title="text1"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Violin Plots",
                width=800,
                height=600,
                renderFun=".plot",
                requiresData=TRUE))}))

jjwithinstats3Base <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jjwithinstats3Base",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "jjwithinstats3",
                version = c(1,0,0),
                options = options,
                results = jjwithinstats3Results$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Violin Plots to Compare Repeated Measurements for Continuous Variables
#'
#' 
#'
#' @examples
#' \dontrun{
#' # example will be added
#'}
#' @param data The data as a data frame.
#' @param dep .
#' @param excl .
#' @param originaltheme .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
jjwithinstats3 <- function(
    data,
    dep,
    excl = TRUE,
    originaltheme = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jjwithinstats3 requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- jjwithinstats3Options$new(
        dep = dep,
        excl = excl,
        originaltheme = originaltheme)

    analysis <- jjwithinstats3Class$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

