
# This file is automatically generated, you probably don't want to edit this

ordinalmixedmodelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ordinalmixedmodelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            fixedFactors = NULL,
            fixedCovs = NULL,
            randomTerms = NULL,
            link = "logit",
            threshold = "flexible",
            propOddsTest = TRUE,
            oddsRatios = TRUE,
            confInt = TRUE,
            confLevel = 0.95,
            randomEffectsTable = TRUE,
            thresholdsTable = TRUE,
            modelFit = TRUE,
            conditionMeans = FALSE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="ordinalmixedmodel",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..fixedFactors <- jmvcore::OptionVariables$new(
                "fixedFactors",
                fixedFactors,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..fixedCovs <- jmvcore::OptionVariables$new(
                "fixedCovs",
                fixedCovs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..randomTerms <- jmvcore::OptionVariables$new(
                "randomTerms",
                randomTerms,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..link <- jmvcore::OptionList$new(
                "link",
                link,
                options=list(
                    "logit",
                    "probit",
                    "cloglog",
                    "loglog",
                    "cauchit"),
                default="logit")
            private$..threshold <- jmvcore::OptionList$new(
                "threshold",
                threshold,
                options=list(
                    "flexible",
                    "symmetric",
                    "equidistant"),
                default="flexible")
            private$..propOddsTest <- jmvcore::OptionBool$new(
                "propOddsTest",
                propOddsTest,
                default=TRUE)
            private$..oddsRatios <- jmvcore::OptionBool$new(
                "oddsRatios",
                oddsRatios,
                default=TRUE)
            private$..confInt <- jmvcore::OptionBool$new(
                "confInt",
                confInt,
                default=TRUE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                min=0.5,
                max=0.99,
                default=0.95)
            private$..randomEffectsTable <- jmvcore::OptionBool$new(
                "randomEffectsTable",
                randomEffectsTable,
                default=TRUE)
            private$..thresholdsTable <- jmvcore::OptionBool$new(
                "thresholdsTable",
                thresholdsTable,
                default=TRUE)
            private$..modelFit <- jmvcore::OptionBool$new(
                "modelFit",
                modelFit,
                default=TRUE)
            private$..conditionMeans <- jmvcore::OptionBool$new(
                "conditionMeans",
                conditionMeans,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..fixedFactors)
            self$.addOption(private$..fixedCovs)
            self$.addOption(private$..randomTerms)
            self$.addOption(private$..link)
            self$.addOption(private$..threshold)
            self$.addOption(private$..propOddsTest)
            self$.addOption(private$..oddsRatios)
            self$.addOption(private$..confInt)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..randomEffectsTable)
            self$.addOption(private$..thresholdsTable)
            self$.addOption(private$..modelFit)
            self$.addOption(private$..conditionMeans)
        }),
    active = list(
        dep = function() private$..dep$value,
        fixedFactors = function() private$..fixedFactors$value,
        fixedCovs = function() private$..fixedCovs$value,
        randomTerms = function() private$..randomTerms$value,
        link = function() private$..link$value,
        threshold = function() private$..threshold$value,
        propOddsTest = function() private$..propOddsTest$value,
        oddsRatios = function() private$..oddsRatios$value,
        confInt = function() private$..confInt$value,
        confLevel = function() private$..confLevel$value,
        randomEffectsTable = function() private$..randomEffectsTable$value,
        thresholdsTable = function() private$..thresholdsTable$value,
        modelFit = function() private$..modelFit$value,
        conditionMeans = function() private$..conditionMeans$value),
    private = list(
        ..dep = NA,
        ..fixedFactors = NA,
        ..fixedCovs = NA,
        ..randomTerms = NA,
        ..link = NA,
        ..threshold = NA,
        ..propOddsTest = NA,
        ..oddsRatios = NA,
        ..confInt = NA,
        ..confLevel = NA,
        ..randomEffectsTable = NA,
        ..thresholdsTable = NA,
        ..modelFit = NA,
        ..conditionMeans = NA)
)

ordinalmixedmodelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ordinalmixedmodelResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        modelFitTable = function() private$.items[["modelFitTable"]],
        fixedEffects = function() private$.items[["fixedEffects"]],
        thresholds = function() private$.items[["thresholds"]],
        randomEffects = function() private$.items[["randomEffects"]],
        propOddsTestTable = function() private$.items[["propOddsTestTable"]],
        conditionProbs = function() private$.items[["conditionProbs"]],
        methodExplanation = function() private$.items[["methodExplanation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Ordinal Mixed Models (Cumulative Link)",
                refs=list(
                    "ClinicoPathJamoviModule"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Analysis Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelFitTable",
                title="Model Fit",
                visible="(modelFit)",
                rows=1,
                clearWith=list(
                    "dep",
                    "fixedFactors",
                    "fixedCovs",
                    "randomTerms",
                    "link",
                    "threshold"),
                columns=list(
                    list(
                        `name`="stat", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto:3"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fixedEffects",
                title="Fixed Effects",
                visible=TRUE,
                rows=1,
                clearWith=list(
                    "dep",
                    "fixedFactors",
                    "fixedCovs",
                    "randomTerms",
                    "link",
                    "threshold"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto:4"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto:4"),
                    list(
                        `name`="z", 
                        `title`="z", 
                        `type`="number", 
                        `format`="zto:3"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="or", 
                        `title`="OR", 
                        `type`="number", 
                        `format`="zto:3", 
                        `visible`="(oddsRatios)"),
                    list(
                        `name`="ciLower", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="zto:3", 
                        `visible`="(confInt)"),
                    list(
                        `name`="ciUpper", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="zto:3", 
                        `visible`="(confInt)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="thresholds",
                title="Threshold Coefficients",
                visible="(thresholdsTable)",
                rows=1,
                clearWith=list(
                    "dep",
                    "fixedFactors",
                    "fixedCovs",
                    "randomTerms",
                    "link",
                    "threshold"),
                columns=list(
                    list(
                        `name`="threshold", 
                        `title`="Threshold", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto:4"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto:4"),
                    list(
                        `name`="z", 
                        `title`="z", 
                        `type`="number", 
                        `format`="zto:3"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="randomEffects",
                title="Random Effects",
                visible="(randomEffectsTable)",
                rows=1,
                clearWith=list(
                    "dep",
                    "fixedFactors",
                    "fixedCovs",
                    "randomTerms",
                    "link",
                    "threshold"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="variance", 
                        `title`="Variance", 
                        `type`="number", 
                        `format`="zto:4"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number", 
                        `format`="zto:4"),
                    list(
                        `name`="nLevels", 
                        `title`="N Levels", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="propOddsTestTable",
                title="Proportional Odds Assumption Test",
                visible="(propOddsTest)",
                rows=1,
                clearWith=list(
                    "dep",
                    "fixedFactors",
                    "fixedCovs",
                    "randomTerms",
                    "link",
                    "threshold"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="Chi-Square", 
                        `type`="number", 
                        `format`="zto:3"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="conclusion", 
                        `title`="Conclusion", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="conditionProbs",
                title="Predicted Marginal Probabilities",
                visible="(conditionMeans)",
                rows=1,
                clearWith=list(
                    "dep",
                    "fixedFactors",
                    "fixedCovs",
                    "randomTerms",
                    "link",
                    "threshold"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="probabilities", 
                        `title`="P(Y = category)", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodExplanation",
                title="Method and Clinical Context",
                visible=TRUE))}))

ordinalmixedmodelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ordinalmixedmodelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "ordinalmixedmodel",
                version = c(1,0,0),
                options = options,
                results = ordinalmixedmodelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Ordinal Mixed Models (Cumulative Link)
#'
#' Cumulative link mixed models (CLMM) for ordinal response data with random 
#' effects. Appropriate for Likert-scale data, ordered categorical outcomes 
#' (e.g., tumor grades, disease severity), and repeated-measures designs with 
#' ordinal endpoints. Uses the ordinal package for fitting cumulative link 
#' mixed models with logit, probit, or complementary log-log links.
#' 
#'
#' @examples
#' \dontrun{
#' data |>
#' ordinalmixedmodel(
#'     dep = "rating",
#'     fixedFactors = "scanner",
#'     randomTerms = "pathologist"
#' )
#'}
#' @param data the data as a data frame
#' @param dep Ordinal dependent variable (e.g., Likert scale, tumor grade,
#'   severity level)
#' @param fixedFactors Categorical fixed-effect predictors
#' @param fixedCovs Continuous fixed-effect predictors
#' @param randomTerms Random effects grouping variables (e.g., subject ID,
#'   rater, site)
#' @param link Link function for the cumulative model
#' @param threshold Threshold parameterization
#' @param propOddsTest Test the proportional odds (parallel lines) assumption
#'   using nominal_test
#' @param oddsRatios Display exponentiated coefficients as odds ratios
#' @param confInt Show confidence intervals for coefficients
#' @param confLevel Confidence level for intervals
#' @param randomEffectsTable Show random effects variance components
#' @param thresholdsTable Show threshold (intercept) coefficients
#' @param modelFit Show AIC, BIC, log-likelihood, and deviance
#' @param conditionMeans Show predicted marginal probabilities for each factor
#'   level
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelFitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fixedEffects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$thresholds} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$randomEffects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$propOddsTestTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$conditionProbs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$methodExplanation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$modelFitTable$asDF}
#'
#' \code{as.data.frame(results$modelFitTable)}
#'
#' @export
ordinalmixedmodel <- function(
    data,
    dep,
    fixedFactors = NULL,
    fixedCovs = NULL,
    randomTerms,
    link = "logit",
    threshold = "flexible",
    propOddsTest = TRUE,
    oddsRatios = TRUE,
    confInt = TRUE,
    confLevel = 0.95,
    randomEffectsTable = TRUE,
    thresholdsTable = TRUE,
    modelFit = TRUE,
    conditionMeans = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ordinalmixedmodel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(fixedFactors)) fixedFactors <- jmvcore::resolveQuo(jmvcore::enquo(fixedFactors))
    if ( ! missing(fixedCovs)) fixedCovs <- jmvcore::resolveQuo(jmvcore::enquo(fixedCovs))
    if ( ! missing(randomTerms)) randomTerms <- jmvcore::resolveQuo(jmvcore::enquo(randomTerms))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(fixedFactors), fixedFactors, NULL),
            `if`( ! missing(fixedCovs), fixedCovs, NULL),
            `if`( ! missing(randomTerms), randomTerms, NULL))

    for (v in fixedFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in randomTerms) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ordinalmixedmodelOptions$new(
        dep = dep,
        fixedFactors = fixedFactors,
        fixedCovs = fixedCovs,
        randomTerms = randomTerms,
        link = link,
        threshold = threshold,
        propOddsTest = propOddsTest,
        oddsRatios = oddsRatios,
        confInt = confInt,
        confLevel = confLevel,
        randomEffectsTable = randomEffectsTable,
        thresholdsTable = thresholdsTable,
        modelFit = modelFit,
        conditionMeans = conditionMeans)

    analysis <- ordinalmixedmodelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

