
# This file is automatically generated, you probably don't want to edit this

plscoxOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "plscoxOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            time = NULL,
            status = NULL,
            predictors = NULL,
            pls_components = 5,
            cross_validation = "k10",
            component_selection = "cv_loglik",
            scaling_method = "standardize",
            pls_algorithm = "nipals",
            max_iterations = 100,
            tolerance = 0.000001,
            bootstrap_validation = FALSE,
            n_bootstrap = 200,
            permutation_test = FALSE,
            n_permutations = 100,
            plot_components = TRUE,
            plot_loadings = TRUE,
            plot_scores = TRUE,
            plot_validation = TRUE,
            plot_survival = TRUE,
            risk_groups = 3,
            confidence_intervals = TRUE,
            feature_importance = TRUE,
            prediction_accuracy = TRUE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="plscox",
                requiresData=FALSE,
                ...)

            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..status <- jmvcore::OptionVariable$new(
                "status",
                status,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..predictors <- jmvcore::OptionVariables$new(
                "predictors",
                predictors,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..pls_components <- jmvcore::OptionInteger$new(
                "pls_components",
                pls_components,
                default=5,
                min=1,
                max=50)
            private$..cross_validation <- jmvcore::OptionList$new(
                "cross_validation",
                cross_validation,
                options=list(
                    "loo",
                    "k10",
                    "k5",
                    "none"),
                default="k10")
            private$..component_selection <- jmvcore::OptionList$new(
                "component_selection",
                component_selection,
                options=list(
                    "cv_loglik",
                    "cv_cindex",
                    "bic",
                    "aic",
                    "manual"),
                default="cv_loglik")
            private$..scaling_method <- jmvcore::OptionList$new(
                "scaling_method",
                scaling_method,
                options=list(
                    "standardize",
                    "unit_variance",
                    "minmax",
                    "none"),
                default="standardize")
            private$..pls_algorithm <- jmvcore::OptionList$new(
                "pls_algorithm",
                pls_algorithm,
                options=list(
                    "nipals",
                    "kernel",
                    "widekernelpls"),
                default="nipals")
            private$..max_iterations <- jmvcore::OptionInteger$new(
                "max_iterations",
                max_iterations,
                default=100,
                min=50,
                max=1000)
            private$..tolerance <- jmvcore::OptionNumber$new(
                "tolerance",
                tolerance,
                default=0.000001,
                min=1e-10,
                max=0.001)
            private$..bootstrap_validation <- jmvcore::OptionBool$new(
                "bootstrap_validation",
                bootstrap_validation,
                default=FALSE)
            private$..n_bootstrap <- jmvcore::OptionInteger$new(
                "n_bootstrap",
                n_bootstrap,
                default=200,
                min=50,
                max=2000)
            private$..permutation_test <- jmvcore::OptionBool$new(
                "permutation_test",
                permutation_test,
                default=FALSE)
            private$..n_permutations <- jmvcore::OptionInteger$new(
                "n_permutations",
                n_permutations,
                default=100,
                min=50,
                max=1000)
            private$..plot_components <- jmvcore::OptionBool$new(
                "plot_components",
                plot_components,
                default=TRUE)
            private$..plot_loadings <- jmvcore::OptionBool$new(
                "plot_loadings",
                plot_loadings,
                default=TRUE)
            private$..plot_scores <- jmvcore::OptionBool$new(
                "plot_scores",
                plot_scores,
                default=TRUE)
            private$..plot_validation <- jmvcore::OptionBool$new(
                "plot_validation",
                plot_validation,
                default=TRUE)
            private$..plot_survival <- jmvcore::OptionBool$new(
                "plot_survival",
                plot_survival,
                default=TRUE)
            private$..risk_groups <- jmvcore::OptionInteger$new(
                "risk_groups",
                risk_groups,
                default=3,
                min=2,
                max=5)
            private$..confidence_intervals <- jmvcore::OptionBool$new(
                "confidence_intervals",
                confidence_intervals,
                default=TRUE)
            private$..feature_importance <- jmvcore::OptionBool$new(
                "feature_importance",
                feature_importance,
                default=TRUE)
            private$..prediction_accuracy <- jmvcore::OptionBool$new(
                "prediction_accuracy",
                prediction_accuracy,
                default=TRUE)

            self$.addOption(private$..time)
            self$.addOption(private$..status)
            self$.addOption(private$..predictors)
            self$.addOption(private$..pls_components)
            self$.addOption(private$..cross_validation)
            self$.addOption(private$..component_selection)
            self$.addOption(private$..scaling_method)
            self$.addOption(private$..pls_algorithm)
            self$.addOption(private$..max_iterations)
            self$.addOption(private$..tolerance)
            self$.addOption(private$..bootstrap_validation)
            self$.addOption(private$..n_bootstrap)
            self$.addOption(private$..permutation_test)
            self$.addOption(private$..n_permutations)
            self$.addOption(private$..plot_components)
            self$.addOption(private$..plot_loadings)
            self$.addOption(private$..plot_scores)
            self$.addOption(private$..plot_validation)
            self$.addOption(private$..plot_survival)
            self$.addOption(private$..risk_groups)
            self$.addOption(private$..confidence_intervals)
            self$.addOption(private$..feature_importance)
            self$.addOption(private$..prediction_accuracy)
        }),
    active = list(
        time = function() private$..time$value,
        status = function() private$..status$value,
        predictors = function() private$..predictors$value,
        pls_components = function() private$..pls_components$value,
        cross_validation = function() private$..cross_validation$value,
        component_selection = function() private$..component_selection$value,
        scaling_method = function() private$..scaling_method$value,
        pls_algorithm = function() private$..pls_algorithm$value,
        max_iterations = function() private$..max_iterations$value,
        tolerance = function() private$..tolerance$value,
        bootstrap_validation = function() private$..bootstrap_validation$value,
        n_bootstrap = function() private$..n_bootstrap$value,
        permutation_test = function() private$..permutation_test$value,
        n_permutations = function() private$..n_permutations$value,
        plot_components = function() private$..plot_components$value,
        plot_loadings = function() private$..plot_loadings$value,
        plot_scores = function() private$..plot_scores$value,
        plot_validation = function() private$..plot_validation$value,
        plot_survival = function() private$..plot_survival$value,
        risk_groups = function() private$..risk_groups$value,
        confidence_intervals = function() private$..confidence_intervals$value,
        feature_importance = function() private$..feature_importance$value,
        prediction_accuracy = function() private$..prediction_accuracy$value),
    private = list(
        ..time = NA,
        ..status = NA,
        ..predictors = NA,
        ..pls_components = NA,
        ..cross_validation = NA,
        ..component_selection = NA,
        ..scaling_method = NA,
        ..pls_algorithm = NA,
        ..max_iterations = NA,
        ..tolerance = NA,
        ..bootstrap_validation = NA,
        ..n_bootstrap = NA,
        ..permutation_test = NA,
        ..n_permutations = NA,
        ..plot_components = NA,
        ..plot_loadings = NA,
        ..plot_scores = NA,
        ..plot_validation = NA,
        ..plot_survival = NA,
        ..risk_groups = NA,
        ..confidence_intervals = NA,
        ..feature_importance = NA,
        ..prediction_accuracy = NA)
)

plscoxResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "plscoxResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        modelSummary = function() private$.items[["modelSummary"]],
        componentSelection = function() private$.items[["componentSelection"]],
        modelCoefficients = function() private$.items[["modelCoefficients"]],
        variableLoadings = function() private$.items[["variableLoadings"]],
        modelPerformance = function() private$.items[["modelPerformance"]],
        riskStratification = function() private$.items[["riskStratification"]],
        componentPlot = function() private$.items[["componentPlot"]],
        loadingsPlot = function() private$.items[["loadingsPlot"]],
        scoresPlot = function() private$.items[["scoresPlot"]],
        validationPlot = function() private$.items[["validationPlot"]],
        survivalPlot = function() private$.items[["survivalPlot"]],
        bootstrapResults = function() private$.items[["bootstrapResults"]],
        permutationResults = function() private$.items[["permutationResults"]],
        clinicalGuidance = function() private$.items[["clinicalGuidance"]],
        technicalNotes = function() private$.items[["technicalNotes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Partial Least Squares Cox Models",
                refs=list(
                    "ClinicoPathJamoviModule"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="Instructions",
                clearWith=list(
                    "time",
                    "status",
                    "predictors")))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelSummary",
                title="Model Summary",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="componentSelection",
                title="Component Selection Results",
                visible=TRUE,
                columns=list(
                    list(
                        `name`="n_components", 
                        `title`="Components", 
                        `type`="integer"),
                    list(
                        `name`="cv_score", 
                        `title`="CV Score", 
                        `type`="number"),
                    list(
                        `name`="se_cv_score", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="c_index", 
                        `title`="C-Index", 
                        `type`="number"),
                    list(
                        `name`="selected", 
                        `title`="Selected", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelCoefficients",
                title="PLS Cox Model Coefficients",
                visible=TRUE,
                columns=list(
                    list(
                        `name`="component", 
                        `title`="PLS Component", 
                        `type`="text"),
                    list(
                        `name`="coefficient", 
                        `title`="Coefficient", 
                        `type`="number"),
                    list(
                        `name`="hr", 
                        `title`="Hazard Ratio", 
                        `type`="number"),
                    list(
                        `name`="hr_lower", 
                        `title`="HR Lower CI", 
                        `type`="number"),
                    list(
                        `name`="hr_upper", 
                        `title`="HR Upper CI", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Standard Error", 
                        `type`="number"),
                    list(
                        `name`="z_value", 
                        `title`="Z-value", 
                        `type`="number"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="variableLoadings",
                title="Variable Loadings on PLS Components",
                visible="(feature_importance)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="component_1", 
                        `title`="Component 1", 
                        `type`="number"),
                    list(
                        `name`="component_2", 
                        `title`="Component 2", 
                        `type`="number"),
                    list(
                        `name`="component_3", 
                        `title`="Component 3", 
                        `type`="number"),
                    list(
                        `name`="importance_score", 
                        `title`="Importance", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelPerformance",
                title="Model Performance Metrics",
                visible="(prediction_accuracy)",
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Standard Error", 
                        `type`="number"),
                    list(
                        `name`="lower_ci", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upper_ci", 
                        `title`="Upper CI", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="riskStratification",
                title="Risk Group Stratification",
                visible=TRUE,
                columns=list(
                    list(
                        `name`="risk_group", 
                        `title`="Risk Group", 
                        `type`="text"),
                    list(
                        `name`="n_subjects", 
                        `title`="N Subjects", 
                        `type`="integer"),
                    list(
                        `name`="n_events", 
                        `title`="N Events", 
                        `type`="integer"),
                    list(
                        `name`="median_survival", 
                        `title`="Median Survival", 
                        `type`="number"),
                    list(
                        `name`="survival_se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="hr_vs_low", 
                        `title`="HR vs Low Risk", 
                        `type`="number"),
                    list(
                        `name`="hr_p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="componentPlot",
                title="PLS Component Analysis",
                width=800,
                height=600,
                renderFun=".plotComponents",
                visible="(plot_components)",
                clearWith=list(
                    "time",
                    "status",
                    "predictors",
                    "pls_components")))
            self$add(jmvcore::Image$new(
                options=options,
                name="loadingsPlot",
                title="Variable Loadings Plot",
                width=800,
                height=600,
                renderFun=".plotLoadings",
                visible="(plot_loadings)",
                clearWith=list(
                    "time",
                    "status",
                    "predictors",
                    "pls_components")))
            self$add(jmvcore::Image$new(
                options=options,
                name="scoresPlot",
                title="Component Scores vs Survival",
                width=800,
                height=600,
                renderFun=".plotScores",
                visible="(plot_scores)",
                clearWith=list(
                    "time",
                    "status",
                    "predictors")))
            self$add(jmvcore::Image$new(
                options=options,
                name="validationPlot",
                title="Cross-Validation Results",
                width=800,
                height=500,
                renderFun=".plotValidation",
                visible="(plot_validation)",
                clearWith=list(
                    "cross_validation",
                    "component_selection")))
            self$add(jmvcore::Image$new(
                options=options,
                name="survivalPlot",
                title="Risk-Stratified Survival Curves",
                width=800,
                height=600,
                renderFun=".plotSurvival",
                visible="(plot_survival)",
                clearWith=list(
                    "time",
                    "status",
                    "risk_groups")))
            self$add(jmvcore::Html$new(
                options=options,
                name="bootstrapResults",
                title="Bootstrap Validation Results",
                visible="(bootstrap_validation)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="permutationResults",
                title="Permutation Test Results",
                visible="(permutation_test)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="clinicalGuidance",
                title="Clinical Interpretation Guide",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="technicalNotes",
                title="Technical Notes and Assumptions",
                visible=TRUE))}))

plscoxBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "plscoxBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "plscox",
                version = c(0,0,3),
                options = options,
                results = plscoxResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Partial Least Squares Cox Models
#'
#' Partial Least Squares Cox regression for high-dimensional survival data.
#' Combines PLS dimensionality reduction with Cox proportional hazards 
#' modeling
#' for analysis of genomic, proteomic, and other high-dimensional datasets.
#' 
#' @param time .
#' @param status .
#' @param predictors .
#' @param pls_components Number of PLS components to extract
#' @param cross_validation Cross-validation method for component selection
#' @param component_selection Method for selecting optimal number of
#'   components
#' @param scaling_method Method for scaling predictor variables
#' @param pls_algorithm Algorithm for PLS computation
#' @param max_iterations Maximum iterations for PLS algorithm convergence
#' @param tolerance Tolerance for algorithm convergence
#' @param bootstrap_validation Perform bootstrap validation of model
#'   performance
#' @param n_bootstrap Number of bootstrap replications
#' @param permutation_test Perform permutation test for variable importance
#' @param n_permutations Number of permutations for significance testing
#' @param plot_components Create PLS component visualization plots
#' @param plot_loadings Display variable loadings for PLS components
#' @param plot_scores Show component scores and survival relationships
#' @param plot_validation Display cross-validation curves for component
#'   selection
#' @param plot_survival Generate risk-stratified survival curves
#' @param risk_groups Number of risk groups for survival stratification
#' @param confidence_intervals Calculate confidence intervals for hazard
#'   ratios
#' @param feature_importance Calculate and display variable importance scores
#' @param prediction_accuracy Assess model prediction accuracy using C-index
#'   and other metrics
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$componentSelection} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelCoefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variableLoadings} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelPerformance} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$riskStratification} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$componentPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$loadingsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$scoresPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$validationPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$survivalPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$bootstrapResults} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$permutationResults} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$clinicalGuidance} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$technicalNotes} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$componentSelection$asDF}
#'
#' \code{as.data.frame(results$componentSelection)}
#'
#' @export
plscox <- function(
    time,
    status,
    predictors,
    pls_components = 5,
    cross_validation = "k10",
    component_selection = "cv_loglik",
    scaling_method = "standardize",
    pls_algorithm = "nipals",
    max_iterations = 100,
    tolerance = 0.000001,
    bootstrap_validation = FALSE,
    n_bootstrap = 200,
    permutation_test = FALSE,
    n_permutations = 100,
    plot_components = TRUE,
    plot_loadings = TRUE,
    plot_scores = TRUE,
    plot_validation = TRUE,
    plot_survival = TRUE,
    risk_groups = 3,
    confidence_intervals = TRUE,
    feature_importance = TRUE,
    prediction_accuracy = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("plscox requires jmvcore to be installed (restart may be required)")

    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if ( ! missing(status)) status <- jmvcore::resolveQuo(jmvcore::enquo(status))
    if ( ! missing(predictors)) predictors <- jmvcore::resolveQuo(jmvcore::enquo(predictors))

    options <- plscoxOptions$new(
        time = time,
        status = status,
        predictors = predictors,
        pls_components = pls_components,
        cross_validation = cross_validation,
        component_selection = component_selection,
        scaling_method = scaling_method,
        pls_algorithm = pls_algorithm,
        max_iterations = max_iterations,
        tolerance = tolerance,
        bootstrap_validation = bootstrap_validation,
        n_bootstrap = n_bootstrap,
        permutation_test = permutation_test,
        n_permutations = n_permutations,
        plot_components = plot_components,
        plot_loadings = plot_loadings,
        plot_scores = plot_scores,
        plot_validation = plot_validation,
        plot_survival = plot_survival,
        risk_groups = risk_groups,
        confidence_intervals = confidence_intervals,
        feature_importance = feature_importance,
        prediction_accuracy = prediction_accuracy)

    analysis <- plscoxClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

