
# This file is automatically generated, you probably don't want to edit this

screeningevaluationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "screeningevaluationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            screening_result = NULL,
            disease_status = NULL,
            participant_id = NULL,
            age_var = NULL,
            sex_var = NULL,
            screening_date = NULL,
            screening_round = NULL,
            risk_factors = NULL,
            location_var = NULL,
            screening_type = "population_based",
            target_disease = "cancer",
            screening_test_type = "laboratory",
            diagnostic_accuracy = TRUE,
            program_coverage = TRUE,
            detection_rates = TRUE,
            interval_cancer_analysis = FALSE,
            lead_time_analysis = FALSE,
            length_bias_analysis = FALSE,
            age_stratified_analysis = TRUE,
            age_group_breaks = "40,50,60,70,80",
            risk_stratified_analysis = FALSE,
            geographic_analysis = FALSE,
            calculate_predictive_values = TRUE,
            likelihood_ratios = TRUE,
            roc_analysis = FALSE,
            optimal_cutpoint = FALSE,
            quality_indicators = TRUE,
            participation_rates = TRUE,
            recall_rates = TRUE,
            completion_rates = TRUE,
            cost_effectiveness = FALSE,
            cost_per_case_detected = FALSE,
            screening_cost_var = NULL,
            followup_cost_var = NULL,
            time_to_diagnosis = FALSE,
            diagnosis_date_var = NULL,
            survival_analysis = FALSE,
            survival_time_var = NULL,
            death_indicator = NULL,
            overdiagnosis_analysis = FALSE,
            false_positive_impact = FALSE,
            screening_adherence = FALSE,
            performance_plots = TRUE,
            coverage_plots = TRUE,
            trend_analysis_plots = FALSE,
            comprehensive_report = TRUE,
            quality_assurance_report = TRUE,
            public_health_indicators = TRUE,
            international_standards = TRUE,
            export_for_registry = FALSE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="screeningevaluation",
                requiresData=TRUE,
                ...)

            private$..screening_result <- jmvcore::OptionVariable$new(
                "screening_result",
                screening_result,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..disease_status <- jmvcore::OptionVariable$new(
                "disease_status",
                disease_status,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..participant_id <- jmvcore::OptionVariable$new(
                "participant_id",
                participant_id,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..age_var <- jmvcore::OptionVariable$new(
                "age_var",
                age_var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sex_var <- jmvcore::OptionVariable$new(
                "sex_var",
                sex_var,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..screening_date <- jmvcore::OptionVariable$new(
                "screening_date",
                screening_date,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..screening_round <- jmvcore::OptionVariable$new(
                "screening_round",
                screening_round,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..risk_factors <- jmvcore::OptionVariables$new(
                "risk_factors",
                risk_factors,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..location_var <- jmvcore::OptionVariable$new(
                "location_var",
                location_var,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..screening_type <- jmvcore::OptionList$new(
                "screening_type",
                screening_type,
                options=list(
                    "population_based",
                    "opportunistic",
                    "high_risk",
                    "workplace",
                    "mass_screening"),
                default="population_based")
            private$..target_disease <- jmvcore::OptionList$new(
                "target_disease",
                target_disease,
                options=list(
                    "cancer",
                    "cardiovascular",
                    "diabetes",
                    "infectious",
                    "chronic_disease",
                    "other"),
                default="cancer")
            private$..screening_test_type <- jmvcore::OptionList$new(
                "screening_test_type",
                screening_test_type,
                options=list(
                    "laboratory",
                    "imaging",
                    "clinical_exam",
                    "questionnaire",
                    "biomarker"),
                default="laboratory")
            private$..diagnostic_accuracy <- jmvcore::OptionBool$new(
                "diagnostic_accuracy",
                diagnostic_accuracy,
                default=TRUE)
            private$..program_coverage <- jmvcore::OptionBool$new(
                "program_coverage",
                program_coverage,
                default=TRUE)
            private$..detection_rates <- jmvcore::OptionBool$new(
                "detection_rates",
                detection_rates,
                default=TRUE)
            private$..interval_cancer_analysis <- jmvcore::OptionBool$new(
                "interval_cancer_analysis",
                interval_cancer_analysis,
                default=FALSE)
            private$..lead_time_analysis <- jmvcore::OptionBool$new(
                "lead_time_analysis",
                lead_time_analysis,
                default=FALSE)
            private$..length_bias_analysis <- jmvcore::OptionBool$new(
                "length_bias_analysis",
                length_bias_analysis,
                default=FALSE)
            private$..age_stratified_analysis <- jmvcore::OptionBool$new(
                "age_stratified_analysis",
                age_stratified_analysis,
                default=TRUE)
            private$..age_group_breaks <- jmvcore::OptionString$new(
                "age_group_breaks",
                age_group_breaks,
                default="40,50,60,70,80")
            private$..risk_stratified_analysis <- jmvcore::OptionBool$new(
                "risk_stratified_analysis",
                risk_stratified_analysis,
                default=FALSE)
            private$..geographic_analysis <- jmvcore::OptionBool$new(
                "geographic_analysis",
                geographic_analysis,
                default=FALSE)
            private$..calculate_predictive_values <- jmvcore::OptionBool$new(
                "calculate_predictive_values",
                calculate_predictive_values,
                default=TRUE)
            private$..likelihood_ratios <- jmvcore::OptionBool$new(
                "likelihood_ratios",
                likelihood_ratios,
                default=TRUE)
            private$..roc_analysis <- jmvcore::OptionBool$new(
                "roc_analysis",
                roc_analysis,
                default=FALSE)
            private$..optimal_cutpoint <- jmvcore::OptionBool$new(
                "optimal_cutpoint",
                optimal_cutpoint,
                default=FALSE)
            private$..quality_indicators <- jmvcore::OptionBool$new(
                "quality_indicators",
                quality_indicators,
                default=TRUE)
            private$..participation_rates <- jmvcore::OptionBool$new(
                "participation_rates",
                participation_rates,
                default=TRUE)
            private$..recall_rates <- jmvcore::OptionBool$new(
                "recall_rates",
                recall_rates,
                default=TRUE)
            private$..completion_rates <- jmvcore::OptionBool$new(
                "completion_rates",
                completion_rates,
                default=TRUE)
            private$..cost_effectiveness <- jmvcore::OptionBool$new(
                "cost_effectiveness",
                cost_effectiveness,
                default=FALSE)
            private$..cost_per_case_detected <- jmvcore::OptionBool$new(
                "cost_per_case_detected",
                cost_per_case_detected,
                default=FALSE)
            private$..screening_cost_var <- jmvcore::OptionVariable$new(
                "screening_cost_var",
                screening_cost_var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..followup_cost_var <- jmvcore::OptionVariable$new(
                "followup_cost_var",
                followup_cost_var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..time_to_diagnosis <- jmvcore::OptionBool$new(
                "time_to_diagnosis",
                time_to_diagnosis,
                default=FALSE)
            private$..diagnosis_date_var <- jmvcore::OptionVariable$new(
                "diagnosis_date_var",
                diagnosis_date_var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..survival_analysis <- jmvcore::OptionBool$new(
                "survival_analysis",
                survival_analysis,
                default=FALSE)
            private$..survival_time_var <- jmvcore::OptionVariable$new(
                "survival_time_var",
                survival_time_var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..death_indicator <- jmvcore::OptionVariable$new(
                "death_indicator",
                death_indicator,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..overdiagnosis_analysis <- jmvcore::OptionBool$new(
                "overdiagnosis_analysis",
                overdiagnosis_analysis,
                default=FALSE)
            private$..false_positive_impact <- jmvcore::OptionBool$new(
                "false_positive_impact",
                false_positive_impact,
                default=FALSE)
            private$..screening_adherence <- jmvcore::OptionBool$new(
                "screening_adherence",
                screening_adherence,
                default=FALSE)
            private$..performance_plots <- jmvcore::OptionBool$new(
                "performance_plots",
                performance_plots,
                default=TRUE)
            private$..coverage_plots <- jmvcore::OptionBool$new(
                "coverage_plots",
                coverage_plots,
                default=TRUE)
            private$..trend_analysis_plots <- jmvcore::OptionBool$new(
                "trend_analysis_plots",
                trend_analysis_plots,
                default=FALSE)
            private$..comprehensive_report <- jmvcore::OptionBool$new(
                "comprehensive_report",
                comprehensive_report,
                default=TRUE)
            private$..quality_assurance_report <- jmvcore::OptionBool$new(
                "quality_assurance_report",
                quality_assurance_report,
                default=TRUE)
            private$..public_health_indicators <- jmvcore::OptionBool$new(
                "public_health_indicators",
                public_health_indicators,
                default=TRUE)
            private$..international_standards <- jmvcore::OptionBool$new(
                "international_standards",
                international_standards,
                default=TRUE)
            private$..export_for_registry <- jmvcore::OptionBool$new(
                "export_for_registry",
                export_for_registry,
                default=FALSE)

            self$.addOption(private$..screening_result)
            self$.addOption(private$..disease_status)
            self$.addOption(private$..participant_id)
            self$.addOption(private$..age_var)
            self$.addOption(private$..sex_var)
            self$.addOption(private$..screening_date)
            self$.addOption(private$..screening_round)
            self$.addOption(private$..risk_factors)
            self$.addOption(private$..location_var)
            self$.addOption(private$..screening_type)
            self$.addOption(private$..target_disease)
            self$.addOption(private$..screening_test_type)
            self$.addOption(private$..diagnostic_accuracy)
            self$.addOption(private$..program_coverage)
            self$.addOption(private$..detection_rates)
            self$.addOption(private$..interval_cancer_analysis)
            self$.addOption(private$..lead_time_analysis)
            self$.addOption(private$..length_bias_analysis)
            self$.addOption(private$..age_stratified_analysis)
            self$.addOption(private$..age_group_breaks)
            self$.addOption(private$..risk_stratified_analysis)
            self$.addOption(private$..geographic_analysis)
            self$.addOption(private$..calculate_predictive_values)
            self$.addOption(private$..likelihood_ratios)
            self$.addOption(private$..roc_analysis)
            self$.addOption(private$..optimal_cutpoint)
            self$.addOption(private$..quality_indicators)
            self$.addOption(private$..participation_rates)
            self$.addOption(private$..recall_rates)
            self$.addOption(private$..completion_rates)
            self$.addOption(private$..cost_effectiveness)
            self$.addOption(private$..cost_per_case_detected)
            self$.addOption(private$..screening_cost_var)
            self$.addOption(private$..followup_cost_var)
            self$.addOption(private$..time_to_diagnosis)
            self$.addOption(private$..diagnosis_date_var)
            self$.addOption(private$..survival_analysis)
            self$.addOption(private$..survival_time_var)
            self$.addOption(private$..death_indicator)
            self$.addOption(private$..overdiagnosis_analysis)
            self$.addOption(private$..false_positive_impact)
            self$.addOption(private$..screening_adherence)
            self$.addOption(private$..performance_plots)
            self$.addOption(private$..coverage_plots)
            self$.addOption(private$..trend_analysis_plots)
            self$.addOption(private$..comprehensive_report)
            self$.addOption(private$..quality_assurance_report)
            self$.addOption(private$..public_health_indicators)
            self$.addOption(private$..international_standards)
            self$.addOption(private$..export_for_registry)
        }),
    active = list(
        screening_result = function() private$..screening_result$value,
        disease_status = function() private$..disease_status$value,
        participant_id = function() private$..participant_id$value,
        age_var = function() private$..age_var$value,
        sex_var = function() private$..sex_var$value,
        screening_date = function() private$..screening_date$value,
        screening_round = function() private$..screening_round$value,
        risk_factors = function() private$..risk_factors$value,
        location_var = function() private$..location_var$value,
        screening_type = function() private$..screening_type$value,
        target_disease = function() private$..target_disease$value,
        screening_test_type = function() private$..screening_test_type$value,
        diagnostic_accuracy = function() private$..diagnostic_accuracy$value,
        program_coverage = function() private$..program_coverage$value,
        detection_rates = function() private$..detection_rates$value,
        interval_cancer_analysis = function() private$..interval_cancer_analysis$value,
        lead_time_analysis = function() private$..lead_time_analysis$value,
        length_bias_analysis = function() private$..length_bias_analysis$value,
        age_stratified_analysis = function() private$..age_stratified_analysis$value,
        age_group_breaks = function() private$..age_group_breaks$value,
        risk_stratified_analysis = function() private$..risk_stratified_analysis$value,
        geographic_analysis = function() private$..geographic_analysis$value,
        calculate_predictive_values = function() private$..calculate_predictive_values$value,
        likelihood_ratios = function() private$..likelihood_ratios$value,
        roc_analysis = function() private$..roc_analysis$value,
        optimal_cutpoint = function() private$..optimal_cutpoint$value,
        quality_indicators = function() private$..quality_indicators$value,
        participation_rates = function() private$..participation_rates$value,
        recall_rates = function() private$..recall_rates$value,
        completion_rates = function() private$..completion_rates$value,
        cost_effectiveness = function() private$..cost_effectiveness$value,
        cost_per_case_detected = function() private$..cost_per_case_detected$value,
        screening_cost_var = function() private$..screening_cost_var$value,
        followup_cost_var = function() private$..followup_cost_var$value,
        time_to_diagnosis = function() private$..time_to_diagnosis$value,
        diagnosis_date_var = function() private$..diagnosis_date_var$value,
        survival_analysis = function() private$..survival_analysis$value,
        survival_time_var = function() private$..survival_time_var$value,
        death_indicator = function() private$..death_indicator$value,
        overdiagnosis_analysis = function() private$..overdiagnosis_analysis$value,
        false_positive_impact = function() private$..false_positive_impact$value,
        screening_adherence = function() private$..screening_adherence$value,
        performance_plots = function() private$..performance_plots$value,
        coverage_plots = function() private$..coverage_plots$value,
        trend_analysis_plots = function() private$..trend_analysis_plots$value,
        comprehensive_report = function() private$..comprehensive_report$value,
        quality_assurance_report = function() private$..quality_assurance_report$value,
        public_health_indicators = function() private$..public_health_indicators$value,
        international_standards = function() private$..international_standards$value,
        export_for_registry = function() private$..export_for_registry$value),
    private = list(
        ..screening_result = NA,
        ..disease_status = NA,
        ..participant_id = NA,
        ..age_var = NA,
        ..sex_var = NA,
        ..screening_date = NA,
        ..screening_round = NA,
        ..risk_factors = NA,
        ..location_var = NA,
        ..screening_type = NA,
        ..target_disease = NA,
        ..screening_test_type = NA,
        ..diagnostic_accuracy = NA,
        ..program_coverage = NA,
        ..detection_rates = NA,
        ..interval_cancer_analysis = NA,
        ..lead_time_analysis = NA,
        ..length_bias_analysis = NA,
        ..age_stratified_analysis = NA,
        ..age_group_breaks = NA,
        ..risk_stratified_analysis = NA,
        ..geographic_analysis = NA,
        ..calculate_predictive_values = NA,
        ..likelihood_ratios = NA,
        ..roc_analysis = NA,
        ..optimal_cutpoint = NA,
        ..quality_indicators = NA,
        ..participation_rates = NA,
        ..recall_rates = NA,
        ..completion_rates = NA,
        ..cost_effectiveness = NA,
        ..cost_per_case_detected = NA,
        ..screening_cost_var = NA,
        ..followup_cost_var = NA,
        ..time_to_diagnosis = NA,
        ..diagnosis_date_var = NA,
        ..survival_analysis = NA,
        ..survival_time_var = NA,
        ..death_indicator = NA,
        ..overdiagnosis_analysis = NA,
        ..false_positive_impact = NA,
        ..screening_adherence = NA,
        ..performance_plots = NA,
        ..coverage_plots = NA,
        ..trend_analysis_plots = NA,
        ..comprehensive_report = NA,
        ..quality_assurance_report = NA,
        ..public_health_indicators = NA,
        ..international_standards = NA,
        ..export_for_registry = NA)
)

screeningevaluationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "screeningevaluationResults",
    inherit = jmvcore::Group,
    active = list(
        screening_overview = function() private$.items[["screening_overview"]],
        diagnostic_accuracy_summary = function() private$.items[["diagnostic_accuracy_summary"]],
        program_coverage = function() private$.items[["program_coverage"]],
        detection_rates = function() private$.items[["detection_rates"]],
        age_stratified_results = function() private$.items[["age_stratified_results"]],
        quality_indicators = function() private$.items[["quality_indicators"]],
        recall_analysis = function() private$.items[["recall_analysis"]],
        interval_cancer_results = function() private$.items[["interval_cancer_results"]],
        cost_effectiveness_summary = function() private$.items[["cost_effectiveness_summary"]],
        geographic_analysis = function() private$.items[["geographic_analysis"]],
        time_trends = function() private$.items[["time_trends"]],
        overdiagnosis_assessment = function() private$.items[["overdiagnosis_assessment"]],
        survival_comparison = function() private$.items[["survival_comparison"]],
        adherence_analysis = function() private$.items[["adherence_analysis"]],
        diagnostic_performance_plot = function() private$.items[["diagnostic_performance_plot"]],
        coverage_participation_plot = function() private$.items[["coverage_participation_plot"]],
        detection_rate_plot = function() private$.items[["detection_rate_plot"]],
        age_stratified_plot = function() private$.items[["age_stratified_plot"]],
        time_trend_plot = function() private$.items[["time_trend_plot"]],
        roc_curve_plot = function() private$.items[["roc_curve_plot"]],
        cost_effectiveness_plot = function() private$.items[["cost_effectiveness_plot"]],
        comprehensive_report = function() private$.items[["comprehensive_report"]],
        quality_assurance_report = function() private$.items[["quality_assurance_report"]],
        public_health_report = function() private$.items[["public_health_report"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Screening Program Evaluation & Performance Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="screening_overview",
                title="Screening Program Overview",
                columns=list(
                    list(
                        `name`="characteristic", 
                        `title`="Characteristic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="diagnostic_accuracy_summary",
                title="Diagnostic Accuracy Summary",
                visible="(diagnostic_accuracy)",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Diagnostic Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_lower", 
                        `title`="95% CI Lower", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_upper", 
                        `title`="95% CI Upper", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="interpretation", 
                        `title`="Clinical Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="program_coverage",
                title="Program Coverage & Participation",
                visible="(program_coverage)",
                columns=list(
                    list(
                        `name`="coverage_type", 
                        `title`="Coverage Type", 
                        `type`="text"),
                    list(
                        `name`="numerator", 
                        `title`="Numerator", 
                        `type`="integer"),
                    list(
                        `name`="denominator", 
                        `title`="Denominator", 
                        `type`="integer"),
                    list(
                        `name`="percentage", 
                        `title`="Percentage (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="target_percentage", 
                        `title`="Target (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="performance_status", 
                        `title`="Performance Status", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="detection_rates",
                title="Disease Detection Rates",
                visible="(detection_rates)",
                columns=list(
                    list(
                        `name`="subgroup", 
                        `title`="Subgroup", 
                        `type`="text"),
                    list(
                        `name`="screened_n", 
                        `title`="Screened (N)", 
                        `type`="integer"),
                    list(
                        `name`="cases_detected", 
                        `title`="Cases Detected", 
                        `type`="integer"),
                    list(
                        `name`="detection_rate", 
                        `title`="Detection Rate (per 1000)", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="dr_ci_lower", 
                        `title`="DR 95% CI Lower", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="dr_ci_upper", 
                        `title`="DR 95% CI Upper", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="expected_rate", 
                        `title`="Expected Rate", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="age_stratified_results",
                title="Age-Stratified Analysis Results",
                visible="(age_stratified_analysis)",
                columns=list(
                    list(
                        `name`="age_group", 
                        `title`="Age Group", 
                        `type`="text"),
                    list(
                        `name`="sensitivity", 
                        `title`="Sensitivity (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="specificity", 
                        `title`="Specificity (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="ppv", 
                        `title`="PPV (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="npv", 
                        `title`="NPV (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="detection_rate", 
                        `title`="Detection Rate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="participation_rate", 
                        `title`="Participation (%)", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="quality_indicators",
                title="Screening Quality Indicators",
                visible="(quality_indicators)",
                columns=list(
                    list(
                        `name`="indicator", 
                        `title`="Quality Indicator", 
                        `type`="text"),
                    list(
                        `name`="observed_value", 
                        `title`="Observed Value", 
                        `type`="text"),
                    list(
                        `name`="target_value", 
                        `title`="Target Value", 
                        `type`="text"),
                    list(
                        `name`="performance_level", 
                        `title`="Performance Level", 
                        `type`="text"),
                    list(
                        `name`="recommendation", 
                        `title`="Recommendation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="recall_analysis",
                title="Recall Rate Analysis",
                visible="(recall_rates)",
                columns=list(
                    list(
                        `name`="recall_category", 
                        `title`="Recall Category", 
                        `type`="text"),
                    list(
                        `name`="recalled_n", 
                        `title`="Recalled (N)", 
                        `type`="integer"),
                    list(
                        `name`="total_screened", 
                        `title`="Total Screened", 
                        `type`="integer"),
                    list(
                        `name`="recall_rate", 
                        `title`="Recall Rate (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="acceptable_range", 
                        `title`="Acceptable Range (%)", 
                        `type`="text"),
                    list(
                        `name`="cancer_detection_rate_recalled", 
                        `title`="CDR in Recalled (%)", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="interval_cancer_results",
                title="Interval Cancer Analysis",
                visible="(interval_cancer_analysis)",
                columns=list(
                    list(
                        `name`="time_period", 
                        `title`="Time Period (months)", 
                        `type`="text"),
                    list(
                        `name`="interval_cancers", 
                        `title`="Interval Cancers", 
                        `type`="integer"),
                    list(
                        `name`="screen_detected_cancers", 
                        `title`="Screen-Detected Cancers", 
                        `type`="integer"),
                    list(
                        `name`="interval_cancer_rate", 
                        `title`="Interval Cancer Rate (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="sensitivity_estimate", 
                        `title`="Sensitivity Estimate (%)", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cost_effectiveness_summary",
                title="Cost-Effectiveness Analysis",
                visible="(cost_effectiveness)",
                columns=list(
                    list(
                        `name`="cost_component", 
                        `title`="Cost Component", 
                        `type`="text"),
                    list(
                        `name`="cost_per_person", 
                        `title`="Cost per Person Screened", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="cost_per_case_detected", 
                        `title`="Cost per Case Detected", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="incremental_cost", 
                        `title`="Incremental Cost", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="cost_effectiveness_ratio", 
                        `title`="Cost-Effectiveness Ratio", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="geographic_analysis",
                title="Geographic Performance Analysis",
                visible="(geographic_analysis && location_var)",
                columns=list(
                    list(
                        `name`="location", 
                        `title`="Location/Site", 
                        `type`="text"),
                    list(
                        `name`="participation_rate", 
                        `title`="Participation (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="detection_rate", 
                        `title`="Detection Rate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="recall_rate", 
                        `title`="Recall Rate (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="ppv", 
                        `title`="PPV (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="performance_score", 
                        `title`="Overall Performance Score", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="time_trends",
                title="Time Trend Analysis",
                visible="(screening_date)",
                columns=list(
                    list(
                        `name`="time_period", 
                        `title`="Time Period", 
                        `type`="text"),
                    list(
                        `name`="participation_rate", 
                        `title`="Participation (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="detection_rate", 
                        `title`="Detection Rate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="recall_rate", 
                        `title`="Recall Rate (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="trend_direction", 
                        `title`="Trend", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="overdiagnosis_assessment",
                title="Overdiagnosis Assessment",
                visible="(overdiagnosis_analysis)",
                columns=list(
                    list(
                        `name`="assessment_method", 
                        `title`="Assessment Method", 
                        `type`="text"),
                    list(
                        `name`="estimated_overdiagnosis", 
                        `title`="Estimated Overdiagnosis (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="confidence_interval", 
                        `title`="95% CI", 
                        `type`="text"),
                    list(
                        `name`="interpretation", 
                        `title`="Clinical Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="survival_comparison",
                title="Survival Comparison",
                visible="(survival_analysis)",
                columns=list(
                    list(
                        `name`="detection_mode", 
                        `title`="Detection Mode", 
                        `type`="text"),
                    list(
                        `name`="cases_n", 
                        `title`="Cases (N)", 
                        `type`="integer"),
                    list(
                        `name`="median_survival", 
                        `title`="Median Survival (months)", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="survival_5yr", 
                        `title`="5-Year Survival (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="hazard_ratio", 
                        `title`="Hazard Ratio", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="hr_ci_lower", 
                        `title`="HR 95% CI Lower", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="hr_ci_upper", 
                        `title`="HR 95% CI Upper", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="adherence_analysis",
                title="Screening Adherence Analysis",
                visible="(screening_adherence)",
                columns=list(
                    list(
                        `name`="adherence_measure", 
                        `title`="Adherence Measure", 
                        `type`="text"),
                    list(
                        `name`="adherent_n", 
                        `title`="Adherent (N)", 
                        `type`="integer"),
                    list(
                        `name`="total_eligible", 
                        `title`="Total Eligible", 
                        `type`="integer"),
                    list(
                        `name`="adherence_rate", 
                        `title`="Adherence Rate (%)", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="factors_associated", 
                        `title`="Associated Factors", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="diagnostic_performance_plot",
                title="Diagnostic Performance Visualization",
                visible="(performance_plots)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="coverage_participation_plot",
                title="Coverage and Participation Analysis",
                visible="(coverage_plots)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="detection_rate_plot",
                title="Detection Rates by Subgroup",
                visible="(detection_rates)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="age_stratified_plot",
                title="Age-Stratified Performance",
                visible="(age_stratified_analysis)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="time_trend_plot",
                title="Performance Trends Over Time",
                visible="(trend_analysis_plots && screening_date)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="roc_curve_plot",
                title="ROC Curve Analysis",
                visible="(roc_analysis)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="cost_effectiveness_plot",
                title="Cost-Effectiveness Analysis Plot",
                visible="(cost_effectiveness)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="comprehensive_report",
                title="Comprehensive Screening Evaluation Report",
                visible="(comprehensive_report)",
                clearWith=list(
                    "screening_result",
                    "disease_status",
                    "screening_type")))
            self$add(jmvcore::Html$new(
                options=options,
                name="quality_assurance_report",
                title="Quality Assurance & Improvement Report",
                visible="(quality_assurance_report)",
                clearWith=list(
                    "screening_result",
                    "disease_status")))
            self$add(jmvcore::Html$new(
                options=options,
                name="public_health_report",
                title="Public Health Indicators Report",
                visible="(public_health_indicators)",
                clearWith=list(
                    "screening_result",
                    "disease_status")))}))

screeningevaluationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "screeningevaluationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "screeningevaluation",
                version = c(1,0,0),
                options = options,
                results = screeningevaluationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Screening Program Evaluation & Performance Analysis
#'
#' Comprehensive evaluation of screening programs and diagnostic test 
#' performance from tabular
#' screening data. Analyzes screening outcomes, program effectiveness, 
#' population coverage,
#' diagnostic accuracy, and cost-effectiveness. Essential for public health 
#' screening program
#' assessment, quality improvement, and evidence-based screening policy 
#' development using
#' standardized epidemiological methods and performance indicators.
#' 
#'
#' @examples
#' data('screening_data')
#'
#' screeningevaluation(
#'     data = screening_data,
#'     screening_result = "screen_positive",
#'     disease_status = "true_disease",
#'     age_var = "age",
#'     screening_round = "round_number"
#' )
#'
#' @param data the data as a data frame
#' @param screening_result Binary screening test result (positive/negative)
#' @param disease_status True disease status from gold standard or follow-up
#' @param participant_id Unique identifier for screening participants
#' @param age_var Age of screening participants
#' @param sex_var Sex/gender of screening participants
#' @param screening_date Date of screening test
#' @param screening_round Screening round number (for repeated screening)
#' @param risk_factors Risk factor variables for stratified analysis
#' @param location_var Geographic location or screening site
#' @param screening_type Type of screening program
#' @param target_disease Target disease or condition being screened
#' @param screening_test_type Type of screening test used
#' @param diagnostic_accuracy Calculate diagnostic accuracy measures from
#'   tabular data
#' @param program_coverage Analyze screening program coverage and
#'   participation
#' @param detection_rates Calculate disease detection rates by subgroups
#' @param interval_cancer_analysis Analyze interval cancers (for cancer
#'   screening programs)
#' @param lead_time_analysis Estimate lead time and lead time bias
#' @param length_bias_analysis Assess potential length bias in screening
#' @param age_stratified_analysis Perform analysis stratified by age groups
#' @param age_group_breaks Age boundaries for stratified analysis
#'   (comma-separated)
#' @param risk_stratified_analysis Perform analysis stratified by risk factors
#' @param geographic_analysis Analyze screening performance by geographic
#'   location
#' @param calculate_predictive_values Calculate positive and negative
#'   predictive values
#' @param likelihood_ratios Calculate likelihood ratios and post-test
#'   probabilities
#' @param roc_analysis Perform ROC curve analysis (for continuous test
#'   results)
#' @param optimal_cutpoint Determine optimal cutpoint for continuous screening
#'   tests
#' @param quality_indicators Calculate standard screening quality indicators
#' @param participation_rates Analyze participation rates and demographic
#'   factors
#' @param recall_rates Calculate recall rates for further investigation
#' @param completion_rates Analyze completion of recommended follow-up
#' @param cost_effectiveness Basic cost-effectiveness analysis
#' @param cost_per_case_detected Calculate cost per case detected
#' @param screening_cost_var Variable containing screening costs per
#'   individual
#' @param followup_cost_var Variable containing follow-up diagnostic costs
#' @param time_to_diagnosis Analyze time from screening to diagnosis
#' @param diagnosis_date_var Date of disease diagnosis
#' @param survival_analysis Compare survival between screen-detected and
#'   symptomatic cases
#' @param survival_time_var Time to death or last follow-up
#' @param death_indicator Death indicator (0=alive, 1=dead)
#' @param overdiagnosis_analysis Assess potential overdiagnosis in screening
#'   program
#' @param false_positive_impact Analyze impact of false positive results
#' @param screening_adherence Analyze adherence to screening recommendations
#' @param performance_plots Generate diagnostic performance plots
#' @param coverage_plots Generate coverage and participation plots
#' @param trend_analysis_plots Generate time trend analysis plots
#' @param comprehensive_report Generate comprehensive screening evaluation
#'   report
#' @param quality_assurance_report Generate quality assurance and improvement
#'   report
#' @param public_health_indicators Generate public health screening indicators
#'   report
#' @param international_standards Assess compliance with international
#'   screening standards
#' @param export_for_registry Export results in cancer registry compatible
#'   format
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$screening_overview} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$diagnostic_accuracy_summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$program_coverage} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$detection_rates} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$age_stratified_results} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$quality_indicators} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$recall_analysis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$interval_cancer_results} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cost_effectiveness_summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$geographic_analysis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$time_trends} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$overdiagnosis_assessment} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$survival_comparison} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$adherence_analysis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$diagnostic_performance_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$coverage_participation_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$detection_rate_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$age_stratified_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$time_trend_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$roc_curve_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cost_effectiveness_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$comprehensive_report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$quality_assurance_report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$public_health_report} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$screening_overview$asDF}
#'
#' \code{as.data.frame(results$screening_overview)}
#'
#' @export
screeningevaluation <- function(
    data,
    screening_result,
    disease_status,
    participant_id,
    age_var,
    sex_var,
    screening_date,
    screening_round,
    risk_factors,
    location_var,
    screening_type = "population_based",
    target_disease = "cancer",
    screening_test_type = "laboratory",
    diagnostic_accuracy = TRUE,
    program_coverage = TRUE,
    detection_rates = TRUE,
    interval_cancer_analysis = FALSE,
    lead_time_analysis = FALSE,
    length_bias_analysis = FALSE,
    age_stratified_analysis = TRUE,
    age_group_breaks = "40,50,60,70,80",
    risk_stratified_analysis = FALSE,
    geographic_analysis = FALSE,
    calculate_predictive_values = TRUE,
    likelihood_ratios = TRUE,
    roc_analysis = FALSE,
    optimal_cutpoint = FALSE,
    quality_indicators = TRUE,
    participation_rates = TRUE,
    recall_rates = TRUE,
    completion_rates = TRUE,
    cost_effectiveness = FALSE,
    cost_per_case_detected = FALSE,
    screening_cost_var,
    followup_cost_var,
    time_to_diagnosis = FALSE,
    diagnosis_date_var,
    survival_analysis = FALSE,
    survival_time_var,
    death_indicator,
    overdiagnosis_analysis = FALSE,
    false_positive_impact = FALSE,
    screening_adherence = FALSE,
    performance_plots = TRUE,
    coverage_plots = TRUE,
    trend_analysis_plots = FALSE,
    comprehensive_report = TRUE,
    quality_assurance_report = TRUE,
    public_health_indicators = TRUE,
    international_standards = TRUE,
    export_for_registry = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("screeningevaluation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(screening_result)) screening_result <- jmvcore::resolveQuo(jmvcore::enquo(screening_result))
    if ( ! missing(disease_status)) disease_status <- jmvcore::resolveQuo(jmvcore::enquo(disease_status))
    if ( ! missing(participant_id)) participant_id <- jmvcore::resolveQuo(jmvcore::enquo(participant_id))
    if ( ! missing(age_var)) age_var <- jmvcore::resolveQuo(jmvcore::enquo(age_var))
    if ( ! missing(sex_var)) sex_var <- jmvcore::resolveQuo(jmvcore::enquo(sex_var))
    if ( ! missing(screening_date)) screening_date <- jmvcore::resolveQuo(jmvcore::enquo(screening_date))
    if ( ! missing(screening_round)) screening_round <- jmvcore::resolveQuo(jmvcore::enquo(screening_round))
    if ( ! missing(risk_factors)) risk_factors <- jmvcore::resolveQuo(jmvcore::enquo(risk_factors))
    if ( ! missing(location_var)) location_var <- jmvcore::resolveQuo(jmvcore::enquo(location_var))
    if ( ! missing(screening_cost_var)) screening_cost_var <- jmvcore::resolveQuo(jmvcore::enquo(screening_cost_var))
    if ( ! missing(followup_cost_var)) followup_cost_var <- jmvcore::resolveQuo(jmvcore::enquo(followup_cost_var))
    if ( ! missing(diagnosis_date_var)) diagnosis_date_var <- jmvcore::resolveQuo(jmvcore::enquo(diagnosis_date_var))
    if ( ! missing(survival_time_var)) survival_time_var <- jmvcore::resolveQuo(jmvcore::enquo(survival_time_var))
    if ( ! missing(death_indicator)) death_indicator <- jmvcore::resolveQuo(jmvcore::enquo(death_indicator))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(screening_result), screening_result, NULL),
            `if`( ! missing(disease_status), disease_status, NULL),
            `if`( ! missing(participant_id), participant_id, NULL),
            `if`( ! missing(age_var), age_var, NULL),
            `if`( ! missing(sex_var), sex_var, NULL),
            `if`( ! missing(screening_date), screening_date, NULL),
            `if`( ! missing(screening_round), screening_round, NULL),
            `if`( ! missing(risk_factors), risk_factors, NULL),
            `if`( ! missing(location_var), location_var, NULL),
            `if`( ! missing(screening_cost_var), screening_cost_var, NULL),
            `if`( ! missing(followup_cost_var), followup_cost_var, NULL),
            `if`( ! missing(diagnosis_date_var), diagnosis_date_var, NULL),
            `if`( ! missing(survival_time_var), survival_time_var, NULL),
            `if`( ! missing(death_indicator), death_indicator, NULL))

    for (v in screening_result) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in disease_status) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in sex_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in location_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in death_indicator) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- screeningevaluationOptions$new(
        screening_result = screening_result,
        disease_status = disease_status,
        participant_id = participant_id,
        age_var = age_var,
        sex_var = sex_var,
        screening_date = screening_date,
        screening_round = screening_round,
        risk_factors = risk_factors,
        location_var = location_var,
        screening_type = screening_type,
        target_disease = target_disease,
        screening_test_type = screening_test_type,
        diagnostic_accuracy = diagnostic_accuracy,
        program_coverage = program_coverage,
        detection_rates = detection_rates,
        interval_cancer_analysis = interval_cancer_analysis,
        lead_time_analysis = lead_time_analysis,
        length_bias_analysis = length_bias_analysis,
        age_stratified_analysis = age_stratified_analysis,
        age_group_breaks = age_group_breaks,
        risk_stratified_analysis = risk_stratified_analysis,
        geographic_analysis = geographic_analysis,
        calculate_predictive_values = calculate_predictive_values,
        likelihood_ratios = likelihood_ratios,
        roc_analysis = roc_analysis,
        optimal_cutpoint = optimal_cutpoint,
        quality_indicators = quality_indicators,
        participation_rates = participation_rates,
        recall_rates = recall_rates,
        completion_rates = completion_rates,
        cost_effectiveness = cost_effectiveness,
        cost_per_case_detected = cost_per_case_detected,
        screening_cost_var = screening_cost_var,
        followup_cost_var = followup_cost_var,
        time_to_diagnosis = time_to_diagnosis,
        diagnosis_date_var = diagnosis_date_var,
        survival_analysis = survival_analysis,
        survival_time_var = survival_time_var,
        death_indicator = death_indicator,
        overdiagnosis_analysis = overdiagnosis_analysis,
        false_positive_impact = false_positive_impact,
        screening_adherence = screening_adherence,
        performance_plots = performance_plots,
        coverage_plots = coverage_plots,
        trend_analysis_plots = trend_analysis_plots,
        comprehensive_report = comprehensive_report,
        quality_assurance_report = quality_assurance_report,
        public_health_indicators = public_health_indicators,
        international_standards = international_standards,
        export_for_registry = export_for_registry)

    analysis <- screeningevaluationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

