
# This file is automatically generated, you probably don't want to edit this

statsplot2Options <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "statsplot2Options",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            grvar = NULL,
            subjectID = NULL,
            direction = "independent",
            distribution = "p",
            forceContinuous = FALSE,
            alluvsty = "t1",
            showSummary = FALSE,
            showExplanations = FALSE,
            excl = FALSE,
            sampleLarge = FALSE,
            sampleThreshold = 10000,
            sampleSize = 5000,
            seed = 42, ...) {

            super$initialize(
                package="ClinicoPath",
                name="statsplot2",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                default=NULL)
            private$..grvar <- jmvcore::OptionVariable$new(
                "grvar",
                grvar,
                default=NULL)
            private$..subjectID <- jmvcore::OptionVariable$new(
                "subjectID",
                subjectID,
                default=NULL)
            private$..direction <- jmvcore::OptionList$new(
                "direction",
                direction,
                options=list(
                    "independent",
                    "repeated"),
                default="independent")
            private$..distribution <- jmvcore::OptionList$new(
                "distribution",
                distribution,
                options=list(
                    "p",
                    "np",
                    "r",
                    "bf"),
                default="p")
            private$..forceContinuous <- jmvcore::OptionBool$new(
                "forceContinuous",
                forceContinuous,
                default=FALSE)
            private$..alluvsty <- jmvcore::OptionList$new(
                "alluvsty",
                alluvsty,
                options=list(
                    "t1",
                    "t2"),
                default="t1")
            private$..showSummary <- jmvcore::OptionBool$new(
                "showSummary",
                showSummary,
                default=FALSE)
            private$..showExplanations <- jmvcore::OptionBool$new(
                "showExplanations",
                showExplanations,
                default=FALSE)
            private$..excl <- jmvcore::OptionBool$new(
                "excl",
                excl,
                default=FALSE)
            private$..sampleLarge <- jmvcore::OptionBool$new(
                "sampleLarge",
                sampleLarge,
                default=FALSE)
            private$..sampleThreshold <- jmvcore::OptionInteger$new(
                "sampleThreshold",
                sampleThreshold,
                default=10000,
                min=1000,
                max=1000000)
            private$..sampleSize <- jmvcore::OptionInteger$new(
                "sampleSize",
                sampleSize,
                default=5000,
                min=100,
                max=1000000)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..grvar)
            self$.addOption(private$..subjectID)
            self$.addOption(private$..direction)
            self$.addOption(private$..distribution)
            self$.addOption(private$..forceContinuous)
            self$.addOption(private$..alluvsty)
            self$.addOption(private$..showSummary)
            self$.addOption(private$..showExplanations)
            self$.addOption(private$..excl)
            self$.addOption(private$..sampleLarge)
            self$.addOption(private$..sampleThreshold)
            self$.addOption(private$..sampleSize)
            self$.addOption(private$..seed)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        grvar = function() private$..grvar$value,
        subjectID = function() private$..subjectID$value,
        direction = function() private$..direction$value,
        distribution = function() private$..distribution$value,
        forceContinuous = function() private$..forceContinuous$value,
        alluvsty = function() private$..alluvsty$value,
        showSummary = function() private$..showSummary$value,
        showExplanations = function() private$..showExplanations$value,
        excl = function() private$..excl$value,
        sampleLarge = function() private$..sampleLarge$value,
        sampleThreshold = function() private$..sampleThreshold$value,
        sampleSize = function() private$..sampleSize$value,
        seed = function() private$..seed$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..grvar = NA,
        ..subjectID = NA,
        ..direction = NA,
        ..distribution = NA,
        ..forceContinuous = NA,
        ..alluvsty = NA,
        ..showSummary = NA,
        ..showExplanations = NA,
        ..excl = NA,
        ..sampleLarge = NA,
        ..sampleThreshold = NA,
        ..sampleSize = NA,
        ..seed = NA)
)

statsplot2Results <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "statsplot2Results",
    inherit = jmvcore::Group,
    active = list(
        notices = function() private$.items[["notices"]],
        summary = function() private$.items[["summary"]],
        todo = function() private$.items[["todo"]],
        ExplanationMessage = function() private$.items[["ExplanationMessage"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Plot Selection Based on Variable Types",
                refs=list(
                    "ggstatsplot",
                    "ggalluvial",
                    "easyalluvial",
                    "ClinicoPathJamoviModule",
                    "patchwork",
                    "cowplot"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="notices",
                title="Important Information",
                clearWith=list(
                    "dep",
                    "group",
                    "direction",
                    "subjectID",
                    "distribution",
                    "forceContinuous",
                    "excl",
                    "grvar",
                    "sampleLarge",
                    "sampleThreshold",
                    "sampleSize",
                    "seed")))
            self$add(jmvcore::Html$new(
                options=options,
                name="summary",
                title="Result sentence",
                visible="(showSummary)",
                clearWith=list(
                    "dep",
                    "group",
                    "direction",
                    "subjectID",
                    "distribution",
                    "forceContinuous",
                    "alluvsty",
                    "excl",
                    "grvar",
                    "sampleLarge",
                    "sampleThreshold",
                    "sampleSize",
                    "seed")))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do",
                clearWith=list(
                    "dep",
                    "group",
                    "direction",
                    "subjectID",
                    "distribution",
                    "forceContinuous",
                    "excl",
                    "grvar",
                    "sampleLarge",
                    "sampleThreshold",
                    "sampleSize")))
            self$add(jmvcore::Html$new(
                options=options,
                name="ExplanationMessage",
                title="Explanation",
                visible="(showExplanations)",
                clearWith=list(
                    "dep",
                    "group",
                    "direction",
                    "subjectID",
                    "distribution",
                    "forceContinuous",
                    "excl",
                    "grvar",
                    "sampleLarge",
                    "sampleThreshold",
                    "sampleSize",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                title="Automatically Selected Plot",
                name="plot",
                width=800,
                height=600,
                renderFun=".plot",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "group",
                    "direction",
                    "subjectID",
                    "distribution",
                    "forceContinuous",
                    "alluvsty",
                    "excl",
                    "grvar",
                    "sampleLarge",
                    "sampleThreshold",
                    "sampleSize",
                    "seed")))}))

statsplot2Base <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "statsplot2Base",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "statsplot2",
                version = c(1,0,8),
                options = options,
                results = statsplot2Results$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Plot Selection
#'
#' Automatically selects and generates the most appropriate statistical 
#' visualization based on variable data types. Features enhanced error 
#' messages with contextual guidance, robust data validation, and 
#' comprehensive fallback options. Supports both independent and repeated 
#' measures designs with various plot types including violin plots, scatter 
#' plots, bar charts, and alluvial diagrams.
#'
#' @examples
#' \donttest{
#' # Continuous outcome across groups: Grade is stored as the numbers
#' # 1-3, so it is read as categorical (a notice says so) and a violin
#' # plot with a nonparametric comparison is drawn.
#' statsplot2(
#'     data = histopathology,
#'     dep = "Age",
#'     group = "Grade",
#'     distribution = "np",
#'     showSummary = TRUE
#' )
#'
#' # One panel per level of a third variable
#' statsplot2(
#'     data = histopathology,
#'     dep = "Age",
#'     group = "Grade",
#'     grvar = "Sex"
#' )
#'
#' # Long-format repeated continuous outcomes need a Subject ID:
#' # statsplot2(data = long, dep = "score", group = "visit",
#' #            subjectID = "patient_id", direction = "repeated")
#'}
#' @param data The data as a data frame.
#' @param dep The dependent variable (y-axis, 1st measurement). Can be
#'   continuous or categorical.
#' @param group The grouping variable (x-axis, 2nd measurement). Can be
#'   continuous or categorical.
#' @param grvar Optional grouping variable for creating grouped plots across
#'   multiple panels.
#' @param subjectID Subject identifier for long-format repeated continuous
#'   outcomes. Each subject must have one row per condition; incomplete subjects
#'   are excluded. Sampling retains whole subjects. Not used for wide-format
#'   alluvial data.
#' @param direction Measurement design type. "independent" for
#'   between-subjects comparisons,  "repeated" for within-subjects/repeated
#'   measures comparisons.
#' @param distribution Statistical approach: "p" = parametric, "np" =
#'   nonparametric,  "r" = robust, "bf" = Bayes factor.
#' @param forceContinuous If TRUE, every numeric variable is treated as
#'   continuous. By default a numeric variable with 15 or fewer distinct
#'   whole-number values is treated as categorical (a notice reports this),
#'   which changes the plot type and the test used.
#' @param alluvsty Style for alluvial diagrams: "t1" = ggalluvial with stratum
#'   labels,  "t2" = easyalluvial with automatic variable selection.
#' @param showSummary If TRUE, a plain-language result sentence with the test
#'   statistic, p-value, effect size and sample size is added to the output.
#' @param showExplanations If TRUE, an explanation panel describing the
#'   selected plot, its clinical interpretation and the assumptions of the
#'   statistical approach is shown.
#' @param excl If TRUE, excludes rows with missing values before analysis.
#' @param sampleLarge If TRUE, randomly samples large datasets for plotting
#'   speed (by default those above 10,000 rows are reduced to 5,000; see
#'   sampleThreshold and sampleSize). Statistics are computed on the retained
#'   rows only.
#' @param sampleThreshold Row count above which sampling is applied, when
#'   'Sample large datasets' is enabled. Datasets at or below this size are
#'   always analysed in full.
#' @param sampleSize Number of rows to retain when sampling. Larger values
#'   keep more statistical power at the cost of plotting speed. Statistics are
#'   computed on the retained rows only.
#' @param seed Random seed used for the sampling of large datasets (when
#'   'Sample large datasets' is enabled) and for any resampling inside the plot
#'   statistics (robust and Bayesian approaches). Change it to draw a different
#'   sample; the default (42) reproduces the previous fixed behaviour.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$notices} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ExplanationMessage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
statsplot2 <- function(
    data,
    dep = NULL,
    group = NULL,
    grvar = NULL,
    subjectID = NULL,
    direction = "independent",
    distribution = "p",
    forceContinuous = FALSE,
    alluvsty = "t1",
    showSummary = FALSE,
    showExplanations = FALSE,
    excl = FALSE,
    sampleLarge = FALSE,
    sampleThreshold = 10000,
    sampleSize = 5000,
    seed = 42) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("statsplot2 requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(grvar)) grvar <- jmvcore::resolveQuo(jmvcore::enquo(grvar))
    if ( ! missing(subjectID)) subjectID <- jmvcore::resolveQuo(jmvcore::enquo(subjectID))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(grvar), grvar, NULL),
            `if`( ! missing(subjectID), subjectID, NULL))


    options <- statsplot2Options$new(
        dep = dep,
        group = group,
        grvar = grvar,
        subjectID = subjectID,
        direction = direction,
        distribution = distribution,
        forceContinuous = forceContinuous,
        alluvsty = alluvsty,
        showSummary = showSummary,
        showExplanations = showExplanations,
        excl = excl,
        sampleLarge = sampleLarge,
        sampleThreshold = sampleThreshold,
        sampleSize = sampleSize,
        seed = seed)

    analysis <- statsplot2Class$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

