
# This file is automatically generated, you probably don't want to edit this

summarydataOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "summarydataOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            date_vars = NULL,
            distr = FALSE,
            sumvar_style = FALSE,
            grvar = NULL, ...) {

            super$initialize(
                package="ClinicoPath",
                name="summarydata",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..date_vars <- jmvcore::OptionVariables$new(
                "date_vars",
                date_vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..distr <- jmvcore::OptionBool$new(
                "distr",
                distr,
                default=FALSE)
            private$..sumvar_style <- jmvcore::OptionBool$new(
                "sumvar_style",
                sumvar_style,
                default=FALSE)
            private$..grvar <- jmvcore::OptionVariable$new(
                "grvar",
                grvar,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))

            self$.addOption(private$..vars)
            self$.addOption(private$..date_vars)
            self$.addOption(private$..distr)
            self$.addOption(private$..sumvar_style)
            self$.addOption(private$..grvar)
        }),
    active = list(
        vars = function() private$..vars$value,
        date_vars = function() private$..date_vars$value,
        distr = function() private$..distr$value,
        sumvar_style = function() private$..sumvar_style$value,
        grvar = function() private$..grvar$value),
    private = list(
        ..vars = NA,
        ..date_vars = NA,
        ..distr = NA,
        ..sumvar_style = NA,
        ..grvar = NA)
)

summarydataResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "summarydataResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        text = function() private$.items[["text"]],
        text1 = function() private$.items[["text1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Summary of Continuous Variables",
                refs=list(
                    "gtExtras",
                    "ClinicoPathJamoviModule"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Html$new(
                options=options,
                name="text1",
                title="Continuous Data Plots"))}))

summarydataBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "summarydataBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "summarydata",
                version = c(0,0,3),
                options = options,
                results = summarydataResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Summary of Continuous Variables
#'
#' This module generates descriptive statistics for continuous variables.
#' It provides both a textual summary and a visually appealing summary table.
#' Optionally, you can enable distribution diagnostics to examine normality, 
#' skewness, and kurtosis.
#' 
#'
#' @examples
#' \donttest{
#' # Example:
#' # 1. Load your data frame.
#' # 2. Select one or more continuous variables.
#' # 3. (Optional) Enable Distribution Diagnostics to view additional tests.
#' # 4. Run the summarydata module to see descriptive statistics and distribution characteristics.
#'}
#' @param data The data as a data frame.
#' @param vars a string naming the variables from \code{data} that contains
#'   the continuous values used for the report
#' @param date_vars Variables containing date/time data to be analyzed with
#'   date-specific statistics (similar to sumvar's dist_date function)
#' @param distr If TRUE, additional distribution diagnostics (Shapiro-Wilk
#'   test, skewness, and kurtosis) will be computed and explained.
#' @param sumvar_style If TRUE, provides comprehensive summary statistics
#'   including quartiles,  confidence intervals, and missing value details in
#'   sumvar package style.
#' @param grvar Optional grouping variable to stratify the summary statistics
#'   by categories.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
summarydata <- function(
    data,
    vars,
    date_vars,
    distr = FALSE,
    sumvar_style = FALSE,
    grvar) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("summarydata requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(date_vars)) date_vars <- jmvcore::resolveQuo(jmvcore::enquo(date_vars))
    if ( ! missing(grvar)) grvar <- jmvcore::resolveQuo(jmvcore::enquo(grvar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(date_vars), date_vars, NULL),
            `if`( ! missing(grvar), grvar, NULL))

    for (v in grvar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- summarydataOptions$new(
        vars = vars,
        date_vars = date_vars,
        distr = distr,
        sumvar_style = sumvar_style,
        grvar = grvar)

    analysis <- summarydataClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

