
# This file is automatically generated, you probably don't want to edit this

treatmenteffectsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "treatmenteffectsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            treatment_var = NULL,
            outcome_var = NULL,
            covariates = NULL,
            patient_id = NULL,
            time_var = NULL,
            event_var = NULL,
            cluster_var = NULL,
            causal_method = "propensity_score",
            outcome_type = "continuous",
            estimand = "ate",
            ps_method = "logistic",
            ps_specification = "main_effects",
            balance_threshold = 0.1,
            matching_method = "nearest_neighbor",
            matching_ratio = "1to1",
            caliper_width = 0.2,
            replacement_matching = FALSE,
            weight_trimming = TRUE,
            trim_quantiles = 0.05,
            stabilized_weights = TRUE,
            weight_normalization = "sum_to_n",
            outcome_model = "linear",
            include_ps_in_outcome = TRUE,
            balance_assessment = TRUE,
            balance_methods = "standardized_differences",
            overlap_assessment = TRUE,
            sensitivity_analysis = TRUE,
            sensitivity_method = "rosenbaum_bounds",
            gamma_values = "1.1,1.2,1.3,1.5,2.0",
            heterogeneous_effects = FALSE,
            effect_modifiers = NULL,
            causal_tree = FALSE,
            causal_forest = FALSE,
            instrument_var = NULL,
            iv_method = "two_stage_least_squares",
            model_diagnostics = TRUE,
            bootstrap_inference = TRUE,
            n_bootstrap = 1000,
            cross_validation = FALSE,
            comprehensive_report = TRUE,
            individual_effects = FALSE,
            save_weights = FALSE,
            save_matched_data = FALSE,
            regulatory_documentation = TRUE, ...) {

            super$initialize(
                package="ClinicoPath",
                name="treatmenteffects",
                requiresData=TRUE,
                ...)

            private$..treatment_var <- jmvcore::OptionVariable$new(
                "treatment_var",
                treatment_var,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..outcome_var <- jmvcore::OptionVariable$new(
                "outcome_var",
                outcome_var,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..patient_id <- jmvcore::OptionVariable$new(
                "patient_id",
                patient_id,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..time_var <- jmvcore::OptionVariable$new(
                "time_var",
                time_var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..event_var <- jmvcore::OptionVariable$new(
                "event_var",
                event_var,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..cluster_var <- jmvcore::OptionVariable$new(
                "cluster_var",
                cluster_var,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..causal_method <- jmvcore::OptionList$new(
                "causal_method",
                causal_method,
                options=list(
                    "propensity_score",
                    "inverse_weighting",
                    "matching",
                    "doubly_robust",
                    "instrumental_variable",
                    "regression_discontinuity",
                    "difference_in_differences"),
                default="propensity_score")
            private$..outcome_type <- jmvcore::OptionList$new(
                "outcome_type",
                outcome_type,
                options=list(
                    "continuous",
                    "binary",
                    "survival",
                    "count"),
                default="continuous")
            private$..estimand <- jmvcore::OptionList$new(
                "estimand",
                estimand,
                options=list(
                    "ate",
                    "att",
                    "atc",
                    "ate_subgroup"),
                default="ate")
            private$..ps_method <- jmvcore::OptionList$new(
                "ps_method",
                ps_method,
                options=list(
                    "logistic",
                    "probit",
                    "gam",
                    "random_forest",
                    "gradient_boosting",
                    "super_learner"),
                default="logistic")
            private$..ps_specification <- jmvcore::OptionList$new(
                "ps_specification",
                ps_specification,
                options=list(
                    "main_effects",
                    "interactions",
                    "polynomial",
                    "splines",
                    "automated"),
                default="main_effects")
            private$..balance_threshold <- jmvcore::OptionNumber$new(
                "balance_threshold",
                balance_threshold,
                min=0.05,
                max=0.25,
                default=0.1)
            private$..matching_method <- jmvcore::OptionList$new(
                "matching_method",
                matching_method,
                options=list(
                    "nearest_neighbor",
                    "optimal",
                    "genetic",
                    "coarsened_exact",
                    "mahalanobis",
                    "propensity_caliper"),
                default="nearest_neighbor")
            private$..matching_ratio <- jmvcore::OptionList$new(
                "matching_ratio",
                matching_ratio,
                options=list(
                    "1to1",
                    "1to2",
                    "1to3",
                    "1to5",
                    "variable"),
                default="1to1")
            private$..caliper_width <- jmvcore::OptionNumber$new(
                "caliper_width",
                caliper_width,
                min=0.01,
                max=0.5,
                default=0.2)
            private$..replacement_matching <- jmvcore::OptionBool$new(
                "replacement_matching",
                replacement_matching,
                default=FALSE)
            private$..weight_trimming <- jmvcore::OptionBool$new(
                "weight_trimming",
                weight_trimming,
                default=TRUE)
            private$..trim_quantiles <- jmvcore::OptionNumber$new(
                "trim_quantiles",
                trim_quantiles,
                min=0.01,
                max=0.1,
                default=0.05)
            private$..stabilized_weights <- jmvcore::OptionBool$new(
                "stabilized_weights",
                stabilized_weights,
                default=TRUE)
            private$..weight_normalization <- jmvcore::OptionList$new(
                "weight_normalization",
                weight_normalization,
                options=list(
                    "none",
                    "sum_to_n",
                    "mean_one"),
                default="sum_to_n")
            private$..outcome_model <- jmvcore::OptionList$new(
                "outcome_model",
                outcome_model,
                options=list(
                    "linear",
                    "logistic",
                    "cox",
                    "poisson",
                    "gam",
                    "random_forest",
                    "super_learner"),
                default="linear")
            private$..include_ps_in_outcome <- jmvcore::OptionBool$new(
                "include_ps_in_outcome",
                include_ps_in_outcome,
                default=TRUE)
            private$..balance_assessment <- jmvcore::OptionBool$new(
                "balance_assessment",
                balance_assessment,
                default=TRUE)
            private$..balance_methods <- jmvcore::OptionList$new(
                "balance_methods",
                balance_methods,
                options=list(
                    "standardized_differences",
                    "variance_ratios",
                    "ks_statistics",
                    "emd",
                    "all_methods"),
                default="standardized_differences")
            private$..overlap_assessment <- jmvcore::OptionBool$new(
                "overlap_assessment",
                overlap_assessment,
                default=TRUE)
            private$..sensitivity_analysis <- jmvcore::OptionBool$new(
                "sensitivity_analysis",
                sensitivity_analysis,
                default=TRUE)
            private$..sensitivity_method <- jmvcore::OptionList$new(
                "sensitivity_method",
                sensitivity_method,
                options=list(
                    "rosenbaum_bounds",
                    "bias_functions",
                    "e_values",
                    "placebo_tests",
                    "multiple_methods"),
                default="rosenbaum_bounds")
            private$..gamma_values <- jmvcore::OptionString$new(
                "gamma_values",
                gamma_values,
                default="1.1,1.2,1.3,1.5,2.0")
            private$..heterogeneous_effects <- jmvcore::OptionBool$new(
                "heterogeneous_effects",
                heterogeneous_effects,
                default=FALSE)
            private$..effect_modifiers <- jmvcore::OptionVariables$new(
                "effect_modifiers",
                effect_modifiers,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..causal_tree <- jmvcore::OptionBool$new(
                "causal_tree",
                causal_tree,
                default=FALSE)
            private$..causal_forest <- jmvcore::OptionBool$new(
                "causal_forest",
                causal_forest,
                default=FALSE)
            private$..instrument_var <- jmvcore::OptionVariable$new(
                "instrument_var",
                instrument_var,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..iv_method <- jmvcore::OptionList$new(
                "iv_method",
                iv_method,
                options=list(
                    "two_stage_least_squares",
                    "limited_information",
                    "generalized_method_moments"),
                default="two_stage_least_squares")
            private$..model_diagnostics <- jmvcore::OptionBool$new(
                "model_diagnostics",
                model_diagnostics,
                default=TRUE)
            private$..bootstrap_inference <- jmvcore::OptionBool$new(
                "bootstrap_inference",
                bootstrap_inference,
                default=TRUE)
            private$..n_bootstrap <- jmvcore::OptionInteger$new(
                "n_bootstrap",
                n_bootstrap,
                min=100,
                max=2000,
                default=1000)
            private$..cross_validation <- jmvcore::OptionBool$new(
                "cross_validation",
                cross_validation,
                default=FALSE)
            private$..comprehensive_report <- jmvcore::OptionBool$new(
                "comprehensive_report",
                comprehensive_report,
                default=TRUE)
            private$..individual_effects <- jmvcore::OptionBool$new(
                "individual_effects",
                individual_effects,
                default=FALSE)
            private$..save_weights <- jmvcore::OptionBool$new(
                "save_weights",
                save_weights,
                default=FALSE)
            private$..save_matched_data <- jmvcore::OptionBool$new(
                "save_matched_data",
                save_matched_data,
                default=FALSE)
            private$..regulatory_documentation <- jmvcore::OptionBool$new(
                "regulatory_documentation",
                regulatory_documentation,
                default=TRUE)

            self$.addOption(private$..treatment_var)
            self$.addOption(private$..outcome_var)
            self$.addOption(private$..covariates)
            self$.addOption(private$..patient_id)
            self$.addOption(private$..time_var)
            self$.addOption(private$..event_var)
            self$.addOption(private$..cluster_var)
            self$.addOption(private$..causal_method)
            self$.addOption(private$..outcome_type)
            self$.addOption(private$..estimand)
            self$.addOption(private$..ps_method)
            self$.addOption(private$..ps_specification)
            self$.addOption(private$..balance_threshold)
            self$.addOption(private$..matching_method)
            self$.addOption(private$..matching_ratio)
            self$.addOption(private$..caliper_width)
            self$.addOption(private$..replacement_matching)
            self$.addOption(private$..weight_trimming)
            self$.addOption(private$..trim_quantiles)
            self$.addOption(private$..stabilized_weights)
            self$.addOption(private$..weight_normalization)
            self$.addOption(private$..outcome_model)
            self$.addOption(private$..include_ps_in_outcome)
            self$.addOption(private$..balance_assessment)
            self$.addOption(private$..balance_methods)
            self$.addOption(private$..overlap_assessment)
            self$.addOption(private$..sensitivity_analysis)
            self$.addOption(private$..sensitivity_method)
            self$.addOption(private$..gamma_values)
            self$.addOption(private$..heterogeneous_effects)
            self$.addOption(private$..effect_modifiers)
            self$.addOption(private$..causal_tree)
            self$.addOption(private$..causal_forest)
            self$.addOption(private$..instrument_var)
            self$.addOption(private$..iv_method)
            self$.addOption(private$..model_diagnostics)
            self$.addOption(private$..bootstrap_inference)
            self$.addOption(private$..n_bootstrap)
            self$.addOption(private$..cross_validation)
            self$.addOption(private$..comprehensive_report)
            self$.addOption(private$..individual_effects)
            self$.addOption(private$..save_weights)
            self$.addOption(private$..save_matched_data)
            self$.addOption(private$..regulatory_documentation)
        }),
    active = list(
        treatment_var = function() private$..treatment_var$value,
        outcome_var = function() private$..outcome_var$value,
        covariates = function() private$..covariates$value,
        patient_id = function() private$..patient_id$value,
        time_var = function() private$..time_var$value,
        event_var = function() private$..event_var$value,
        cluster_var = function() private$..cluster_var$value,
        causal_method = function() private$..causal_method$value,
        outcome_type = function() private$..outcome_type$value,
        estimand = function() private$..estimand$value,
        ps_method = function() private$..ps_method$value,
        ps_specification = function() private$..ps_specification$value,
        balance_threshold = function() private$..balance_threshold$value,
        matching_method = function() private$..matching_method$value,
        matching_ratio = function() private$..matching_ratio$value,
        caliper_width = function() private$..caliper_width$value,
        replacement_matching = function() private$..replacement_matching$value,
        weight_trimming = function() private$..weight_trimming$value,
        trim_quantiles = function() private$..trim_quantiles$value,
        stabilized_weights = function() private$..stabilized_weights$value,
        weight_normalization = function() private$..weight_normalization$value,
        outcome_model = function() private$..outcome_model$value,
        include_ps_in_outcome = function() private$..include_ps_in_outcome$value,
        balance_assessment = function() private$..balance_assessment$value,
        balance_methods = function() private$..balance_methods$value,
        overlap_assessment = function() private$..overlap_assessment$value,
        sensitivity_analysis = function() private$..sensitivity_analysis$value,
        sensitivity_method = function() private$..sensitivity_method$value,
        gamma_values = function() private$..gamma_values$value,
        heterogeneous_effects = function() private$..heterogeneous_effects$value,
        effect_modifiers = function() private$..effect_modifiers$value,
        causal_tree = function() private$..causal_tree$value,
        causal_forest = function() private$..causal_forest$value,
        instrument_var = function() private$..instrument_var$value,
        iv_method = function() private$..iv_method$value,
        model_diagnostics = function() private$..model_diagnostics$value,
        bootstrap_inference = function() private$..bootstrap_inference$value,
        n_bootstrap = function() private$..n_bootstrap$value,
        cross_validation = function() private$..cross_validation$value,
        comprehensive_report = function() private$..comprehensive_report$value,
        individual_effects = function() private$..individual_effects$value,
        save_weights = function() private$..save_weights$value,
        save_matched_data = function() private$..save_matched_data$value,
        regulatory_documentation = function() private$..regulatory_documentation$value),
    private = list(
        ..treatment_var = NA,
        ..outcome_var = NA,
        ..covariates = NA,
        ..patient_id = NA,
        ..time_var = NA,
        ..event_var = NA,
        ..cluster_var = NA,
        ..causal_method = NA,
        ..outcome_type = NA,
        ..estimand = NA,
        ..ps_method = NA,
        ..ps_specification = NA,
        ..balance_threshold = NA,
        ..matching_method = NA,
        ..matching_ratio = NA,
        ..caliper_width = NA,
        ..replacement_matching = NA,
        ..weight_trimming = NA,
        ..trim_quantiles = NA,
        ..stabilized_weights = NA,
        ..weight_normalization = NA,
        ..outcome_model = NA,
        ..include_ps_in_outcome = NA,
        ..balance_assessment = NA,
        ..balance_methods = NA,
        ..overlap_assessment = NA,
        ..sensitivity_analysis = NA,
        ..sensitivity_method = NA,
        ..gamma_values = NA,
        ..heterogeneous_effects = NA,
        ..effect_modifiers = NA,
        ..causal_tree = NA,
        ..causal_forest = NA,
        ..instrument_var = NA,
        ..iv_method = NA,
        ..model_diagnostics = NA,
        ..bootstrap_inference = NA,
        ..n_bootstrap = NA,
        ..cross_validation = NA,
        ..comprehensive_report = NA,
        ..individual_effects = NA,
        ..save_weights = NA,
        ..save_matched_data = NA,
        ..regulatory_documentation = NA)
)

treatmenteffectsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "treatmenteffectsResults",
    inherit = jmvcore::Group,
    active = list(
        overview = function() private$.items[["overview"]],
        treatment_effect_estimates = function() private$.items[["treatment_effect_estimates"]],
        balance_assessment = function() private$.items[["balance_assessment"]],
        propensity_summary = function() private$.items[["propensity_summary"]],
        matching_summary = function() private$.items[["matching_summary"]],
        weight_summary = function() private$.items[["weight_summary"]],
        model_diagnostics = function() private$.items[["model_diagnostics"]],
        sensitivity_analysis = function() private$.items[["sensitivity_analysis"]],
        heterogeneity_analysis = function() private$.items[["heterogeneity_analysis"]],
        individual_effects = function() private$.items[["individual_effects"]],
        overlap_plot = function() private$.items[["overlap_plot"]],
        balance_plot = function() private$.items[["balance_plot"]],
        effect_plot = function() private$.items[["effect_plot"]],
        sensitivity_plot = function() private$.items[["sensitivity_plot"]],
        causal_report = function() private$.items[["causal_report"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Causal Inference & Treatment Effects Analysis",
                refs=list(
                    "ClinicoPathJamoviModule"))
            self$add(jmvcore::Table$new(
                options=options,
                name="overview",
                title="Treatment Effects Analysis Overview",
                columns=list(
                    list(
                        `name`="characteristic", 
                        `title`="Characteristic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="treatment_effect_estimates",
                title="Treatment Effect Estimates",
                columns=list(
                    list(
                        `name`="estimand", 
                        `title`="Estimand", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Effect Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="std_error", 
                        `title`="Standard Error", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_lower", 
                        `title`="95% CI Lower", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_upper", 
                        `title`="95% CI Upper", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="interpretation", 
                        `title`="Clinical Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="balance_assessment",
                title="Covariate Balance Assessment",
                visible="(balance_assessment)",
                columns=list(
                    list(
                        `name`="covariate", 
                        `title`="Covariate", 
                        `type`="text"),
                    list(
                        `name`="treatment_mean", 
                        `title`="Treatment Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="control_mean", 
                        `title`="Control Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="std_diff_unadj", 
                        `title`="Std Diff (Unadj)", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="std_diff_adj", 
                        `title`="Std Diff (Adj)", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="balance_status", 
                        `title`="Balance Status", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="propensity_summary",
                title="Propensity Score Summary",
                visible="(causal_method:propensity_score || causal_method:inverse_weighting || causal_method:matching)",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="ps_mean", 
                        `title`="PS Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ps_sd", 
                        `title`="PS SD", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ps_min", 
                        `title`="PS Min", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ps_max", 
                        `title`="PS Max", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="matching_summary",
                title="Matching Summary",
                visible="(causal_method:matching)",
                columns=list(
                    list(
                        `name`="match_type", 
                        `title`="Match Type", 
                        `type`="text"),
                    list(
                        `name`="matched_pairs", 
                        `title`="Matched Pairs", 
                        `type`="integer"),
                    list(
                        `name`="unmatched_treated", 
                        `title`="Unmatched Treated", 
                        `type`="integer"),
                    list(
                        `name`="unmatched_control", 
                        `title`="Unmatched Control", 
                        `type`="integer"),
                    list(
                        `name`="matching_ratio", 
                        `title`="Matching Ratio", 
                        `type`="text"),
                    list(
                        `name`="caliper_width", 
                        `title`="Caliper Width", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="weight_summary",
                title="IPTW Weight Summary",
                visible="(causal_method:inverse_weighting)",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="weight_mean", 
                        `title`="Weight Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="weight_sd", 
                        `title`="Weight SD", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="weight_min", 
                        `title`="Weight Min", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="weight_max", 
                        `title`="Weight Max", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="extreme_weights", 
                        `title`="Extreme Weights (>10)", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="model_diagnostics",
                title="Model Diagnostics",
                visible="(model_diagnostics)",
                columns=list(
                    list(
                        `name`="diagnostic", 
                        `title`="Diagnostic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="sensitivity_analysis",
                title="Sensitivity Analysis",
                visible="(sensitivity_analysis)",
                columns=list(
                    list(
                        `name`="gamma", 
                        `title`="Gamma", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="lower_bound", 
                        `title`="Lower Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="upper_bound", 
                        `title`="Upper Bound", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p_value_lower", 
                        `title`="p-value (Lower)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="p_value_upper", 
                        `title`="p-value (Upper)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="conclusion", 
                        `title`="Conclusion", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="heterogeneity_analysis",
                title="Treatment Effect Heterogeneity",
                visible="(heterogeneous_effects)",
                columns=list(
                    list(
                        `name`="subgroup", 
                        `title`="Subgroup", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="effect_estimate", 
                        `title`="Effect Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_lower", 
                        `title`="95% CI Lower", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_upper", 
                        `title`="95% CI Upper", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="individual_effects",
                title="Individual Treatment Effects",
                visible="(individual_effects)",
                columns=list(
                    list(
                        `name`="patient_id", 
                        `title`="Patient ID", 
                        `type`="text"),
                    list(
                        `name`="observed_outcome", 
                        `title`="Observed Outcome", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="predicted_treated", 
                        `title`="Predicted if Treated", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="predicted_control", 
                        `title`="Predicted if Control", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="individual_effect", 
                        `title`="Individual Effect", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="confidence", 
                        `title`="Confidence", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="overlap_plot",
                title="Propensity Score Overlap",
                visible="(overlap_assessment)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="balance_plot",
                title="Covariate Balance Plot",
                visible="(balance_assessment)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="effect_plot",
                title="Treatment Effects Forest Plot",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="sensitivity_plot",
                title="Sensitivity Analysis Plot",
                visible="(sensitivity_analysis)",
                width=600,
                height=400,
                requiresData=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="causal_report",
                title="Comprehensive Causal Inference Report",
                visible="(comprehensive_report)",
                clearWith=list(
                    "treatment_var",
                    "outcome_var",
                    "covariates",
                    "causal_method")))}))

treatmenteffectsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "treatmenteffectsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPath",
                name = "treatmenteffects",
                version = c(1,0,0),
                options = options,
                results = treatmenteffectsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Causal Inference & Treatment Effects Analysis
#'
#' Comprehensive causal inference analysis for estimating treatment effects in 
#' observational studies.
#' Implements propensity score methods, inverse probability of treatment 
#' weighting (IPTW),
#' matching techniques, and doubly robust estimation. Includes covariate 
#' balance assessment,
#' sensitivity analysis, and causal effect estimation with confidence 
#' intervals. Essential for
#' comparative effectiveness research, real-world evidence studies, and 
#' observational research
#' where randomized controlled trials are not feasible.
#' 
#'
#' @examples
#' data('treatment_data')
#'
#' treatmenteffects(
#'     data = treatment_data,
#'     treatment_var = "treatment",
#'     outcome_var = "outcome",
#'     covariates = c("age", "sex", "baseline_severity"),
#'     causal_method = "propensity_score",
#'     estimand = "ate"
#' )
#'
#' @param data the data as a data frame
#' @param treatment_var Binary treatment variable (treated vs. control)
#' @param outcome_var Primary outcome variable of interest
#' @param covariates Confounding variables to adjust for in causal analysis
#' @param patient_id Patient identifier for tracking matched pairs
#' @param time_var Time to event variable for survival outcomes
#' @param event_var Event indicator for survival outcomes
#' @param cluster_var Clustering variable (e.g., hospital, physician) for
#'   robust standard errors
#' @param causal_method Primary method for causal inference
#' @param outcome_type Type of outcome variable
#' @param estimand Target causal estimand
#' @param ps_method Method for estimating propensity scores
#' @param ps_specification Complexity of propensity score model
#' @param balance_threshold Maximum standardized mean difference for adequate
#'   balance
#' @param matching_method Specific matching algorithm to use
#' @param matching_ratio Ratio of controls to treated units
#' @param caliper_width Maximum distance for matching (in standard deviations)
#' @param replacement_matching Allow controls to be matched to multiple
#'   treated units
#' @param weight_trimming Trim extreme propensity score weights
#' @param trim_quantiles Quantiles for weight trimming (e.g., 0.05 = trim
#'   top/bottom 5\%)
#' @param stabilized_weights Use stabilized inverse probability weights
#' @param weight_normalization Method for normalizing weights
#' @param outcome_model Model for outcome regression
#' @param include_ps_in_outcome Include propensity score in outcome model
#'   (doubly robust)
#' @param balance_assessment Assess covariate balance before and after
#'   adjustment
#' @param balance_methods Methods for assessing covariate balance
#' @param overlap_assessment Assess propensity score overlap between treatment
#'   groups
#' @param sensitivity_analysis Perform sensitivity analysis for unmeasured
#'   confounding
#' @param sensitivity_method Method for sensitivity analysis
#' @param gamma_values Gamma values for Rosenbaum bounds (comma-separated)
#' @param heterogeneous_effects Analyze treatment effect heterogeneity
#' @param effect_modifiers Variables for subgroup analysis and effect
#'   modification
#' @param causal_tree Use causal trees to identify effect heterogeneity
#' @param causal_forest Use causal random forests for individualized treatment
#'   effects
#' @param instrument_var Instrumental variable for IV analysis
#' @param iv_method Method for instrumental variable estimation
#' @param model_diagnostics Perform comprehensive model diagnostics
#' @param bootstrap_inference Use bootstrap for confidence intervals
#' @param n_bootstrap Number of bootstrap samples
#' @param cross_validation Use cross-validation for model selection
#' @param comprehensive_report Generate comprehensive causal inference report
#' @param individual_effects Estimate individual treatment effects
#' @param save_weights Save propensity scores and weights to dataset
#' @param save_matched_data Save matched dataset for further analysis
#' @param regulatory_documentation Include regulatory compliance documentation
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$overview} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$treatment_effect_estimates} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$balance_assessment} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$propensity_summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$matching_summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$weight_summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$model_diagnostics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sensitivity_analysis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$heterogeneity_analysis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$individual_effects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$overlap_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$balance_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$effect_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$sensitivity_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$causal_report} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$overview$asDF}
#'
#' \code{as.data.frame(results$overview)}
#'
#' @export
treatmenteffects <- function(
    data,
    treatment_var,
    outcome_var,
    covariates,
    patient_id,
    time_var,
    event_var,
    cluster_var,
    causal_method = "propensity_score",
    outcome_type = "continuous",
    estimand = "ate",
    ps_method = "logistic",
    ps_specification = "main_effects",
    balance_threshold = 0.1,
    matching_method = "nearest_neighbor",
    matching_ratio = "1to1",
    caliper_width = 0.2,
    replacement_matching = FALSE,
    weight_trimming = TRUE,
    trim_quantiles = 0.05,
    stabilized_weights = TRUE,
    weight_normalization = "sum_to_n",
    outcome_model = "linear",
    include_ps_in_outcome = TRUE,
    balance_assessment = TRUE,
    balance_methods = "standardized_differences",
    overlap_assessment = TRUE,
    sensitivity_analysis = TRUE,
    sensitivity_method = "rosenbaum_bounds",
    gamma_values = "1.1,1.2,1.3,1.5,2.0",
    heterogeneous_effects = FALSE,
    effect_modifiers,
    causal_tree = FALSE,
    causal_forest = FALSE,
    instrument_var,
    iv_method = "two_stage_least_squares",
    model_diagnostics = TRUE,
    bootstrap_inference = TRUE,
    n_bootstrap = 1000,
    cross_validation = FALSE,
    comprehensive_report = TRUE,
    individual_effects = FALSE,
    save_weights = FALSE,
    save_matched_data = FALSE,
    regulatory_documentation = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("treatmenteffects requires jmvcore to be installed (restart may be required)")

    if ( ! missing(treatment_var)) treatment_var <- jmvcore::resolveQuo(jmvcore::enquo(treatment_var))
    if ( ! missing(outcome_var)) outcome_var <- jmvcore::resolveQuo(jmvcore::enquo(outcome_var))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(patient_id)) patient_id <- jmvcore::resolveQuo(jmvcore::enquo(patient_id))
    if ( ! missing(time_var)) time_var <- jmvcore::resolveQuo(jmvcore::enquo(time_var))
    if ( ! missing(event_var)) event_var <- jmvcore::resolveQuo(jmvcore::enquo(event_var))
    if ( ! missing(cluster_var)) cluster_var <- jmvcore::resolveQuo(jmvcore::enquo(cluster_var))
    if ( ! missing(effect_modifiers)) effect_modifiers <- jmvcore::resolveQuo(jmvcore::enquo(effect_modifiers))
    if ( ! missing(instrument_var)) instrument_var <- jmvcore::resolveQuo(jmvcore::enquo(instrument_var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(treatment_var), treatment_var, NULL),
            `if`( ! missing(outcome_var), outcome_var, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(patient_id), patient_id, NULL),
            `if`( ! missing(time_var), time_var, NULL),
            `if`( ! missing(event_var), event_var, NULL),
            `if`( ! missing(cluster_var), cluster_var, NULL),
            `if`( ! missing(effect_modifiers), effect_modifiers, NULL),
            `if`( ! missing(instrument_var), instrument_var, NULL))

    for (v in treatment_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in event_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cluster_var) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- treatmenteffectsOptions$new(
        treatment_var = treatment_var,
        outcome_var = outcome_var,
        covariates = covariates,
        patient_id = patient_id,
        time_var = time_var,
        event_var = event_var,
        cluster_var = cluster_var,
        causal_method = causal_method,
        outcome_type = outcome_type,
        estimand = estimand,
        ps_method = ps_method,
        ps_specification = ps_specification,
        balance_threshold = balance_threshold,
        matching_method = matching_method,
        matching_ratio = matching_ratio,
        caliper_width = caliper_width,
        replacement_matching = replacement_matching,
        weight_trimming = weight_trimming,
        trim_quantiles = trim_quantiles,
        stabilized_weights = stabilized_weights,
        weight_normalization = weight_normalization,
        outcome_model = outcome_model,
        include_ps_in_outcome = include_ps_in_outcome,
        balance_assessment = balance_assessment,
        balance_methods = balance_methods,
        overlap_assessment = overlap_assessment,
        sensitivity_analysis = sensitivity_analysis,
        sensitivity_method = sensitivity_method,
        gamma_values = gamma_values,
        heterogeneous_effects = heterogeneous_effects,
        effect_modifiers = effect_modifiers,
        causal_tree = causal_tree,
        causal_forest = causal_forest,
        instrument_var = instrument_var,
        iv_method = iv_method,
        model_diagnostics = model_diagnostics,
        bootstrap_inference = bootstrap_inference,
        n_bootstrap = n_bootstrap,
        cross_validation = cross_validation,
        comprehensive_report = comprehensive_report,
        individual_effects = individual_effects,
        save_weights = save_weights,
        save_matched_data = save_matched_data,
        regulatory_documentation = regulatory_documentation)

    analysis <- treatmenteffectsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

